#!/usr/bin/env python3
"""Uploads the Champignons collection's sprites as the bot's own emojis, then writes their ids
into ProjectSYNCS/Helpers/Emotes.Mushrooms.cs.

They are *application* emojis: owned by the bot's application rather than by a server, so the
bot can show them in any server it is in, and no server's emoji slots are spent. Each 16x16
sprite is scaled up 8x without smoothing (128x128, still crisp pixel art) before upload.

Usage — with the token of the bot that runs in production (application emojis belong to one
application; a dev bot that is a different application will show them as plain text):

    set DISCORD_TOKEN=...            (PowerShell: $env:DISCORD_TOKEN = "...")
    python tools/mushroom-emojis/upload.py

The token is read from DISCORD_TOKEN, or asked for without echo. It is never written anywhere.
An emoji that already exists under the same name is reused, not uploaded again, so the script
is safe to run twice; to replace a picture, delete that emoji in the developer portal first.

    python tools/mushroom-emojis/upload.py --offline

writes the file with every emoji falling back to 🍄, which is what the repository ships until
the upload has been done.

Needs Pillow (already required by tools/plynling-art).
"""
import argparse
import base64
import getpass
import io
import json
import os
import sys
import time
import urllib.error
import urllib.request
from pathlib import Path

from PIL import Image

HERE = Path(__file__).resolve().parent
SPRITES = HERE / "sprites"
OUT = HERE.parent.parent / "ProjectSYNCS" / "Helpers" / "Emotes.Mushrooms.cs"
API = "https://discord.com/api/v10"
USER_AGENT = "DiscordBot (https://github.com/RMelisen/DiscordBot.SessionOrganizer, 1.0)"
SCALE = 8
PREFIX = "shroom_"
FALLBACK = "🍄"


def slugs():
    return sorted(p.stem for p in SPRITES.glob("*.png"))


def const_name(slug):
    return "Shroom" + "".join(word.capitalize() for word in slug.split("_"))


def request(method, path, token, body=None):
    data = json.dumps(body).encode() if body is not None else None
    while True:
        req = urllib.request.Request(API + path, data=data, method=method, headers={
            "Authorization": f"Bot {token}",
            "Content-Type": "application/json",
            "User-Agent": USER_AGENT,
        })
        try:
            with urllib.request.urlopen(req) as response:
                return json.load(response)
        except urllib.error.HTTPError as error:
            text = error.read().decode(errors="replace")
            if error.code == 429:                       # rate limited: wait as told, then retry
                time.sleep(float(json.loads(text).get("retry_after", 1)) + 0.2)
                continue
            sys.exit(f"{method} {path} failed: {error.code} {text}")


def data_uri(path):
    image = Image.open(path).convert("RGBA")
    image = image.resize((image.width * SCALE, image.height * SCALE), Image.NEAREST)
    buffer = io.BytesIO()
    image.save(buffer, "PNG")
    return "data:image/png;base64," + base64.b64encode(buffer.getvalue()).decode()


def write_cs(ids):
    """ids: slug -> emoji id, or None for the 🍄 fallback."""
    uploaded = all(ids.values())
    lines = [
        "// <auto-generated>",
        "// Written by tools/mushroom-emojis/upload.py — do not edit by hand; run the script again.",
        "// </auto-generated>",
        "namespace ProjectSYNCS.Helpers;",
        "",
        "// The Champignons collection's pictures: the bot's *application* emojis — owned by its",
        "// application rather than by a server, so it can show them anywhere it is — uploaded from",
        "// tools/mushroom-emojis/sprites. Until that script has run, every one falls back to 🍄 and",
        "// MushroomsUploaded is false. Only ever used in text (embeds, messages), never as a reaction.",
        "public static partial class Emotes",
        "{",
        f"    public const bool MushroomsUploaded = {'true' if uploaded else 'false'};",
    ]
    for slug in slugs():
        name, emoji_id = const_name(slug), ids.get(slug)
        lines.append("")
        lines.append(f"    /// <summary>`:{PREFIX}{slug}:`</summary>")
        if emoji_id:
            lines.append(f'    public const string {name}Id = "{emoji_id}";')
            lines.append(f'    public const string {name} = $"<:{PREFIX}{slug}:{{{name}Id}}>";')
        else:
            lines.append(f'    public const string {name}Id = "";')
            lines.append(f'    public const string {name} = "{FALLBACK}";')
    lines.append("}")
    OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"Wrote {OUT} ({'uploaded' if uploaded else 'fallback'} emojis).")


def main():
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--offline", action="store_true", help="write the 🍄 fallback file, upload nothing")
    args = parser.parse_args()

    names = slugs()
    too_long = [s for s in names if len(PREFIX + s) > 32]
    if too_long:
        sys.exit(f"Emoji names must be 32 characters at most: {too_long}")

    if args.offline:
        write_cs({slug: None for slug in names})
        return

    token = os.environ.get("DISCORD_TOKEN") or getpass.getpass("Bot token: ")
    app_id = request("GET", "/applications/@me", token)["id"]
    existing = {e["name"]: e["id"] for e in request("GET", f"/applications/{app_id}/emojis", token).get("items", [])}

    ids = {}
    for slug in names:
        name = PREFIX + slug
        if name in existing:
            ids[slug] = existing[name]
            print(f"  = {name} (already there)")
            continue
        created = request("POST", f"/applications/{app_id}/emojis", token,
                          {"name": name, "image": data_uri(SPRITES / f"{slug}.png")})
        ids[slug] = created["id"]
        print(f"  + {name}")
    write_cs(ids)
    print("Now rebuild the bot and commit Emotes.Mushrooms.cs.")


if __name__ == "__main__":
    main()
