"""Every item icon as a 16×16 grid in palette characters (palette.py), keyed by its icon key: the
item key (col.galet, cos.accessory.noeud) or set.<set key>. GROUPS orders them into the batches
the owner judges, one sheet each. name and unicode are only for the sheet: the bot's catalog is
the truth for both."""
from dataclasses import dataclass


@dataclass(frozen=True)
class Icon:
    name: str
    unicode: str
    grid: tuple


ICONS: dict = {}
GROUPS: dict = {}


def icon(group, key, name, unicode, *rows):
    assert key not in ICONS, f"{key} drawn twice"
    ICONS[key] = Icon(name, unicode, tuple(rows))
    GROUPS.setdefault(group, []).append(key)


# ---- Cailloux ---------------------------------------------------------------------------------

icon("cailloux", "col.galet", "Galet", "🪨",
     "................",
     "................",
     ".....######.....",
     "...##swsssG##...",
     "..#sswssGGGGG#..",
     ".#sswsGGGGGGGg#.",
     ".#ssGGGGgGGGgg#.",
     ".#sGGgGGGGGGgg#.",
     ".#GGGGGGGgGggg#.",
     ".#GGGGGGGGgggk#.",
     ".#GgGGGGGggggk#.",
     "..#GGGGggggkk#..",
     "...##gggggk##...",
     ".....######.....",
     "................",
     "................")

icon("cailloux", "col.caillou_plat", "Caillou plat", "🥏",
     "................",
     "................",
     "................",
     "....########....",
     "..##sswwsssh##..",
     ".#sswssshhhhGG#.",
     ".#shsshhhhGGGG#.",
     ".#hhhhhGGGGGGg#.",
     ".#GhhGGGGGGGgg#.",
     ".#gGGGGGGGGggT#.",
     "..#ggggggggTT#..",
     "...##TTTTTT##...",
     ".....######.....",
     "................",
     "................",
     "................")

icon("cailloux", "col.silex", "Silex", "🔪",
     "................",
     "................",
     "......#####.....",
     "....##wwssJ#....",
     "...#wwsJsJkk#...",
     "..#wsJsJkTTgk#..",
     "..#sJsJkTGTTk#..",
     ".#wsJsJkThTTTk#.",
     ".#sJsJkTGhTGTk#.",
     ".#JsJkTTGTTGTk#.",
     ".#sJJkTGTTGTkk#.",
     "..#JjkTTGTTkk#..",
     "..#jjjkTTTkkk#..",
     "...##jjkkkk##...",
     ".....######.....",
     "................")

icon("cailloux", "col.quartz", "Quartz", "🔷",
     "................",
     ".....##.........",
     "....#ww#........",
     "...#wwsh#.......",
     "..#wwwshh#......",
     "..#wwwshD####...",
     "..#wwwshD#wsh#..",
     "..#wswshD#wsh#..",
     "..#wwwshD#wsD#..",
     "..#wwsshD#whD#..",
     "..#wwwshD#shD#..",
     "..#swwshD#shD#..",
     "..#sswsDD#sDD#..",
     "..#ssssDD#sDd#..",
     "...##########...",
     "................")

icon("cailloux", "col.agate", "Agate", "🟠",
     "................",
     "................",
     ".....######.....",
     "...##awoooa##...",
     "..#aJwaaaaJJa#..",
     ".#JJJJJJJJJaoR#.",
     ".#aaaaaaaaaoRo#.",
     ".#oooooooooRoa#.",
     ".#oRRRRRoRRoaJ#.",
     ".#RooooRRooaJo#.",
     ".#oaaaaoooaJoo#.",
     "..#JJJaaaaJoo#..",
     "...##aJJJJo##...",
     ".....######.....",
     "................",
     "................")

icon("cailloux", "col.amethyste", "Améthyste", "🟣",
     "................",
     ".......##.......",
     "......#IC#......",
     ".....#ICnV#.....",
     ".....#CCnV####..",
     "..##.#CCnV#InV#.",
     ".#IC##CCnV#CnV#.",
     ".#Cn##CCnV#CnV#.",
     ".#Cn##CCnV#CnV#.",
     ".#CV##CnnV#nnV#.",
     ".#nV##nnVV#nVz#.",
     ".#GGssGGGGGGGg#.",
     ".#sGGGGGGgggkk#.",
     "..############..",
     "................",
     "................")

icon("cailloux", "col.opale", "Opale", "🌈",
     "................",
     "................",
     "................",
     ".....######.....",
     "...##BxxBbb##...",
     "..#wBxlxBbPbP#..",
     ".#BBxllBiibPPP#.",
     ".#bBxBiiIibbPP#.",
     ".#bbBxxibBllPp#.",
     ".#PbbBxxBlllPp#.",
     "..#PbbBBbllPp#..",
     "...##PPbbPp##...",
     ".....######.....",
     "................",
     "................",
     "................")

icon("cailloux", "col.meteorite", "Météorite", "☄️",
     "................",
     "............##..",
     "..........##w#..",
     "........##aAy#..",
     "......##EaAyy#..",
     "...####EEaAy#...",
     "..#gGgkkEEa#....",
     ".#gGwGgkgkE#....",
     ".#gGGgTgkkk#....",
     ".#GgTgggkTk#....",
     ".#gggkggkkk#....",
     ".#ggkkgTkkk#....",
     "..#gkkTkkk#.....",
     "...#######......",
     "................",
     "................")


def recolour(key, mapping, glints=()):
    """Another icon's grid with its colours swapped (mapping: char → char) and a few pixels set:
    glints is (x, y, char)."""
    rows = [list(r) for r in ICONS[key].grid]
    rows = [[mapping.get(c, c) for c in r] for r in rows]
    for x, y, c in glints:
        rows[y][x] = c
    return ["".join(r) for r in rows]


# ---- Nature -----------------------------------------------------------------------------------

icon("nature", "col.feuille_chene", "Feuille de chêne", "🍂",
     "................",
     ".......##.......",
     "......#AA#......",
     ".....#AAaa#.....",
     "....#AAaRao#....",
     "...#AAaaRaoo#...",
     "....#AaaRao#....",
     "...#AAaoRoao#...",
     "..#AAaaaRaaoo#..",
     "...#AaaoRoao#...",
     "..#AAaaaRaaoo#..",
     "...#aaaaRaoo#...",
     "....#aaaRoo#....",
     ".....###R##.....",
     "........#.......",
     "................")

icon("nature", "col.gland", "Gland", "🌰",
     "................",
     "........#.......",
     ".......#j#......",
     "....####j####...",
     "...#JjJjUjUu#...",
     "..#JjUjUjUjUu#..",
     "..#jUjUjUjUuu#..",
     "..##uuuuuuuu##..",
     "...#aAoooooR#...",
     "...#AaoooooR#...",
     "...#aoooooRR#...",
     "....#oooRRR#....",
     ".....#oRRR#.....",
     "......#RR#......",
     ".......##.......",
     "................")

icon("nature", "col.plume", "Plume", "🪶",
     "................",
     "..........###...",
     ".........#wws#..",
     "........#wwsGs#.",
     ".......#wwsGss#.",
     "......#wwsGsss#.",
     ".....#wwsGssG#..",
     "....#wwsGssG#...",
     "...#wssGssG#....",
     "...#ssGsGG#.....",
     "...#sGsGG#......",
     "..#jG####.......",
     ".#j##...........",
     "..#.............",
     "................",
     "................")

icon("nature", "col.trefle", "Trèfle", "☘️",
     "................",
     "......#####.....",
     ".....#llLLL#....",
     ".....#lLLLL#....",
     ".....#LLLLt#....",
     "..####LLtt####..",
     ".#llLL#Lt#lLLL#.",
     ".#lLLLt##LLLLt#.",
     ".#LLLLtt#LLLtt#.",
     "..#LLtt##Ltt##..",
     "...#####L####...",
     ".......#L#......",
     ".......#L#......",
     "........#L#.....",
     ".........#......",
     "................")

icon("nature", "col.pomme_pin", "Pomme de pin", "🌲",
     "................",
     "......####......",
     ".....#uUUU#.....",
     "....#uJuUuj#....",
     "...#ujjUuUuu#...",
     "...#Jujujuuu#...",
     "..#jjjuUUUuuu#..",
     "..#ujuJuUujuu#..",
     "...#ujjUuUuu#...",
     "...#Jujujuuu#...",
     "....#juUUUu#....",
     ".....#JuUu#.....",
     ".....#jUuU#.....",
     "......#uj#......",
     ".......##.......",
     "................")

icon("nature", "col.coquille_escargot", "Coquille d'escargot", "🐌",
     "................",
     ".....######.....",
     "....#AAAAaa#....",
     "...#AwRRRRRa#...",
     "..#AwRAaaaaRo#..",
     ".#AARAaaRaaoRo#.",
     ".#AARaRRaRooRo#.",
     ".#AARaRaaoRooR#.",
     ".#AaRaRRRoRooR#.",
     ".#aaRaaoooRooR#.",
     ".#RaaRoooRooRo#.",
     "..#aaoRRRoooR#..",
     "...#oooooooR#...",
     "....#RRRRRR#....",
     ".....######.....",
     "................")


icon("nature", "col.trefle_quatre", "Trèfle à quatre feuilles", "🍀",
     "................",
     "......####......",
     ".....#lwlL#.....",
     ".....#llLL#.....",
     "..####lLLt####..",
     ".#lYlL#lL#lYlL#.",
     ".#llLLtLLtlLLt#.",
     ".#LLLttLtLLLtt#.",
     "..#Ltt#tt#Ltt#..",
     "...###lLLt###...",
     ".....#lLLt#.....",
     ".....#LLtt#.....",
     "......####......",
     "................",
     "................",
     "................")

icon("nature", "col.plume_doree", "Plume dorée", "✨",
     *recolour("col.plume", {"w": "y", "s": "a", "G": "o", "j": "o"},
               glints=[(10, 2, "w"), (9, 4, "w"), (6, 7, "w"), (4, 9, "w")]))


# ---- Trésors ----------------------------------------------------------------------------------

icon("tresors", "col.bouton", "Bouton", "🔘",
     "................",
     ".....######.....",
     "...##EEEEEE##...",
     "..#EIeeeEEEcc#..",
     "..#IeeeEEEEEc#..",
     ".#EeeeEEEEEEEc#.",
     ".#EeeE#EE#EEEc#.",
     ".#EeEEEEEEEEcc#.",
     ".#EEEEEEEEEccc#.",
     ".#EEEE#EE#cccc#.",
     ".#EEEEEEEccccc#.",
     "..#cEEEEccccc#..",
     "..#ccEEcccccc#..",
     "...##cccccc##...",
     ".....######.....",
     "................")

icon("tresors", "col.bille", "Bille", "🔮",
     "................",
     ".....######.....",
     "....#BBBBBB#....",
     "...#BBBBBBbb#...",
     "..#BwwBBBbbbb#..",
     ".#BBwxBBbbbbbb#.",
     ".#BxxxxbbbbbbP#.",
     ".#BBBBbxbbbbPP#.",
     ".#BBBbbbxbbPPP#.",
     ".#BBbbbbbhhhhP#.",
     ".#BbbbbbbPhhPP#.",
     "..#bbbbbPPPPP#..",
     "...#bbbPPPPP#...",
     "....#bPPPPP#....",
     ".....######.....",
     "................")

icon("tresors", "col.cle_rouillee", "Clé rouillée", "🗝️",
     "................",
     "...####.........",
     "..#AAaa#........",
     ".#AAaaaa#.......",
     ".#Aa##ao#.......",
     ".#aa##oo#.......",
     ".#aaaooo#.......",
     "..#aooRo#.......",
     "...####oa#......",
     ".......#Ra#.....",
     "........#oo#....",
     "........#oRa#...",
     ".......#R##oa#..",
     "........##RoRo#.",
     "..........####..",
     "................")

icon("tresors", "col.piece_ancienne", "Pièce ancienne", "🪙",
     "................",
     ".....######.....",
     "...##aaaaaa##...",
     "..#awyyyyaaaa#..",
     "..#wyyyyaaaaa#..",
     ".#ayyAAAAAoaao#.",
     ".#ayyAaaaaoaao#.",
     ".#ayyAa##aoaoo#.",
     ".#ayaAa##aoooo#.",
     ".#aaaAaaaaoooo#.",
     ".#aaaooooooooo#.",
     "..#aaaaaooooo#..",
     "..#aaaaoooooo#..",
     "...##oooooo##...",
     ".....######.....",
     "................")

icon("tresors", "col.bague", "Bague", "💍",
     "................",
     ".......##.......",
     "......#Ii#......",
     ".....#Iwii#.....",
     ".....#iiCC#.....",
     ".....##CC##.....",
     "....#yyyyaa#....",
     "...#yyyyaaaa#...",
     "..#yyyyaaaaaa#..",
     ".#yyy######aoo#.",
     ".#yyy#....#ooo#.",
     "..#ya######oo#..",
     "..#aaaaaaoooo#..",
     "...##aaaooo##...",
     ".....######.....",
     "................")

icon("tresors", "col.boussole", "Boussole", "🧭",
     "................",
     ".....######.....",
     "....#aaaaaa#....",
     "...#aaawwaoo#...",
     "..#aawwEEwwoo#..",
     ".#aawwwEEwwwoo#.",
     ".#aawwwEEwwsoR#.",
     ".#awwwwE#wsssR#.",
     ".#awwww#GssssR#.",
     ".#aawwwGGsssRR#.",
     ".#aowwwGGsssRR#.",
     "..#oowsGGssRR#..",
     "...#ooossRRR#...",
     "....#oRRRRR#....",
     ".....######.....",
     "................")

icon("tresors", "col.carte_tresor", "Carte au trésor", "🗺️",
     "................",
     "................",
     "..###########...",
     ".#jJJJJJJJJJj#..",
     ".#jwJJoJJJJJj#..",
     ".#jJJJJoJJJJj#..",
     ".#jJJJJJJoJJj#..",
     ".#jJJoJJJJJJj#..",
     ".#jJoJJJJEJEj#..",
     ".#jJJoJJJJEJj#..",
     ".#jJJJJoJEJEj#..",
     ".#jJJJJJJJJJj#..",
     "..###########...",
     "................",
     "................",
     "................")

icon("tresors", "col.couronne", "Couronne", "👑",
     "................",
     "................",
     "..#....#....#...",
     ".#w#..#w#..#y#..",
     ".#y#.#yyy#.#a#..",
     ".#ya##yEya##ao#.",
     ".#yaayyyyaaaao#.",
     ".#yyayayyaaaao#.",
     ".#yEyyaEyaaEao#.",
     ".#yyyyaayaaaao#.",
     ".#aaaaaaaaaooo#.",
     ".#oooooooooooR#.",
     "..############..",
     "................",
     "................",
     "................")


# ---- Saisons ----------------------------------------------------------------------------------

icon("saisons", "col.primevere", "Primevère", "🌼",
     "................",
     "......####......",
     ".....#wwyy#.....",
     "....##wyyy##....",
     "...#wayyyyay#...",
     "..#wwyayyayyy#..",
     "..#wyyyaayyyA#..",
     "..#yyyy##yyAA#..",
     "...#aayooyaa#...",
     "...#yyyyyAAA#...",
     "...#yyyyAAAA#...",
     "...#yyyAAAAA#...",
     "..#LLL####LLL#..",
     "..#tt#....#tt#..",
     "...##......##...",
     "................")

icon("saisons", "col.cerise", "Cerise", "🍒",
     "................",
     ".........###....",
     "........#llL#...",
     ".......#L#LLt#..",
     "......#L#L###...",
     ".....#L##L#.....",
     "....#L#..#L#....",
     "...##L#..#L##...",
     "..#EEEE##EEEE#..",
     ".#EIIEEEEIIEEE#.",
     ".#EIIEEcEIIEEc#.",
     ".#EEEEccEEEEcc#.",
     ".#EEEcccEEEccc#.",
     "..#Eccc##Eccc#..",
     "...####..####...",
     "................")

icon("saisons", "col.coquelicot", "Coquelicot", "🌺",
     "................",
     "......####......",
     "....##eeeE##....",
     "...#eeppppEE#...",
     "..#eeecppcEEE#..",
     ".#eeeeEEEEEEcc#.",
     ".#eeeEEEEEEccc#.",
     ".#eeEEEEEEcccc#.",
     "..#EEEEEEcccc#..",
     "...#EEEEcccc#...",
     "....#EEcccc#....",
     ".....###L#l#....",
     ".......#LLl#....",
     ".......#L##.....",
     "........#.......",
     "................")

icon("saisons", "col.coquillage", "Coquillage", "🐚",
     "................",
     "................",
     "....########....",
     "..##IIwwIIII##..",
     ".#wwIIwwIiIIii#.",
     ".#wwIIwwiiIIii#.",
     ".#IwwIIIiIIiiI#.",
     ".#IIwIiIiIIiII#.",
     ".#IIwIiIiIiiII#.",
     ".#wwiIiIiIiIii#.",
     "..#IIiIIiiIii#..",
     "...##IiiIIi##...",
     ".....#iiii#.....",
     "....#ii##ii#....",
     ".....##..##.....",
     "................")

icon("saisons", "col.chataigne", "Châtaigne", "🌰",
     "................",
     ".......#........",
     ".....##R###.....",
     "....#AAAooo#....",
     "....#wAoooo#....",
     "...#AAoooooR#...",
     "...#AoooooRR#...",
     "..##oooooRRR##..",
     ".#l#ooooRRRR#l#.",
     ".#lllJJJJJJttt#.",
     "..#lLLJJJJttt#..",
     ".#lLLLLLLttttl#.",
     "..##LLLLtttt##..",
     "...#lLLttttl#...",
     "....########....",
     "................")

icon("saisons", "col.citrouille", "Citrouille", "🎃",
     "................",
     ".......###......",
     "......#tLl#.....",
     "......#tL#......",
     "....##AAAa##....",
     "...#oAAAaaao#...",
     "..#AoAAoaaaoa#..",
     ".#AAoAaoaaaoao#.",
     ".#AAoaaoaaaooo#.",
     ".#AAoaaoaaaooo#.",
     ".#Aaoaaoaaoooo#.",
     ".#aaoaaoaooooo#.",
     "..#aoaaoooooo#..",
     "...##aaoooo##...",
     ".....######.....",
     "................")

icon("saisons", "col.flocon", "Flocon", "❄️",
     "................",
     ".......#........",
     "......#h#.......",
     ".....#xwx#......",
     "..#.#x#w#x#.#...",
     ".#h####w####h#..",
     "..#ww##w##ww#...",
     "...##wwxww##....",
     "..#ww##w##ww#...",
     ".#h####w####h#..",
     "..#.#x#w#x#.#...",
     ".....#xwx#......",
     "......#h#.......",
     ".......#........",
     "................",
     "................")

icon("saisons", "col.cristal_givre", "Cristal de givre", "💎",
     "................",
     ".......##.......",
     "......#wx#......",
     ".....#wxBb#.....",
     "..##.#wxBb###...",
     ".#wx##wxBb#xB#..",
     ".#xB##xxBb#xb#..",
     ".#xB##xxBb#Bb#..",
     ".#xb##xBBb#Bb#..",
     ".#Bb##xBbb#Bb#..",
     ".#Bb##BBbb#bd#..",
     ".#bd##Bbbd#bd#..",
     ".#wswswswsws#...",
     "..###########...",
     "................",
     "................")


# ---- Insectes ---------------------------------------------------------------------------------

icon("insectes", "col.fourmi", "Fourmi", "🐜",
     "................",
     "................",
     "................",
     "..........#..#..",
     "...........##...",
     "...........##...",
     "...###..#.#jU#..",
     "..#jUU##U#jUwu#.",
     ".#jUUUuUUuUUuu#.",
     ".#UUUuu#u##uu#..",
     ".#UUuuu###.##...",
     "..#####.#.#.....",
     ".....#..#..#....",
     "................",
     "................",
     "................")

icon("insectes", "col.mouche", "Mouche", "🪰",
     "................",
     "................",
     ".....##..##.....",
     "....#EE##EE#....",
     "...#EIEkkIEc#...",
     "...#EEckkEcc#...",
     "...####Gg####...",
     "...###Gggg###...",
     "..#sshgggksss#..",
     "..#shhgkkksss#..",
     "..#hhhgggghss#..",
     "..#hhhkkkkhhs#..",
     "..#hhhgggghhh#..",
     "...####kk####...",
     ".......##.......",
     "................")

icon("insectes", "col.moustique", "Moustique", "🦟",
     "................",
     "................",
     "................",
     ".........###....",
     "........#whh##..",
     ".......#wwhhhh#.",
     "...#####wwhhh#..",
     "..#gEgGG#####...",
     "..##gGGGgsg###..",
     ".#..#####sgsgs#.",
     ".....#.#.###gs#.",
     "....#..#..#.##..",
     "...#...#...#....",
     "...#...#....#...",
     "................",
     "................")

icon("insectes", "col.chenille", "Chenille", "🐛",
     "................",
     "................",
     "................",
     "................",
     "......#####.....",
     ".....#llllL#....",
     "....#lYLlYLL#...",
     "...#llLLLLllL#..",
     "..#lYLLt#LYLL#..",
     "..#LLLt#.#LLt#..",
     ".#lYLt#..#llLL#.",
     ".#lLLt#..#lL#L#.",
     ".#LLtt#..#LCLL#.",
     "..####....#LL#..",
     "...........##...",
     "................")

icon("insectes", "col.coccinelle", "Coccinelle", "🐞",
     "................",
     "................",
     "......####......",
     ".....#wkkw#.....",
     "....##kkkk##....",
     "...#IIk#kkEE#...",
     "..#IIEE#EEEEE#..",
     "..#I##E#EE##c#..",
     "..#EEEE#EEEcc#..",
     "..#EEEE#EEccc#..",
     "..#E#EE#Ec##c#..",
     "..#EEEE#ccccc#..",
     "...#E#E#c#cc#...",
     "....#Ec#ccc#....",
     ".....######.....",
     "................")

icon("insectes", "col.grillon", "Grillon", "🦗",
     "................",
     "................",
     "..........#.....",
     "...........#....",
     "............#...",
     "...####......##.",
     "..#UUUU#...###..",
     "...#uuuu###LL#..",
     "..#LLLttttuL#t#.",
     "..#LLttttuuttu#.",
     "..#Lttttuuuuu#..",
     "...##ttuu####...",
     "..#.#####.#.....",
     "...#....#..#....",
     "................",
     "................")

icon("insectes", "col.abeille", "Abeille", "🐝",
     "................",
     "................",
     "......###.#.....",
     ".....#www#w#....",
     ".....#wwwwww#...",
     ".....#ssshhh#...",
     ".....#ssshhh#...",
     "..####y#yy#a#...",
     ".#kwkyy#ya#aa#..",
     ".#kk##y#aa#ao#..",
     ".#k###y#aa#oo##.",
     "..###ya#aa#oo#..",
     "...###a#ao#o#...",
     "......######....",
     "................",
     "................")

icon("insectes", "col.morpho_bleu", "Morpho bleu", "🦋",
     "................",
     "....##....##....",
     "..##d##..##d##..",
     ".#ddxBB##xxxdd#.",
     ".#xwBBBkgxxBwB#.",
     ".#xBBBbkgxBBBb#.",
     ".#BBBbbkgBBBbb#.",
     ".#dBbbbkgBBbbd#.",
     "..#ddb#kg#bdd#..",
     "...##dBkgxd##...",
     "...#xBBkgxBB#...",
     "...#wBBkgBBw#...",
     "...#BBbkgBbb#...",
     "....#db##bd#....",
     ".....##..##.....",
     "................")


# ---- Sets -------------------------------------------------------------------------------------

icon("sets", "set.cailloux", "Cailloux", "🪨",
     "................",
     "................",
     "................",
     "................",
     "....####........",
     "...#sssG#.##....",
     "..#sssGGG#JJ##..",
     "..#ssGGGG#Jjjj#.",
     "..#sGGGG#Jjjjj#.",
     "..#GGGGg#jjjjU#.",
     "...#G######jUU#.",
     "....#wwsss#UU#..",
     "....#wsssGG##...",
     ".....#ssGG#.....",
     "......####......",
     "................")

icon("sets", "set.nature", "Nature", "🍂",
     "................",
     "....##..........",
     "...#AR#.........",
     "..#AaRa#........",
     ".#AAaRao#.......",
     "..#AaRo##.#.....",
     ".#AAaRaoo#U##...",
     ".#AaaRaoo#jUj#..",
     "..#aaRoo#jUjUj#.",
     ".#AaaRao#####U#.",
     "..#aaRoo#Aaoo#..",
     "...#aRo#aaooRR#.",
     "....#R##aooRR#..",
     "....#R#.#oRRR#..",
     ".....#...####...",
     "................")

icon("sets", "set.tresors", "Trésors", "💎",
     "................",
     "..############..",
     ".#UUaUUUUUUaUU#.",
     ".#UUaUUUUUUaUU#.",
     ".#uuauuuuuuauu#.",
     ".#uuauuuuuuauu#.",
     "..############..",
     "..#yyayyayyay#..",
     ".#a##########a#.",
     ".#UUaUUyyUUaUU#.",
     ".#UUaUUyyUUaUU#.",
     ".#uuauuuuuuauu#.",
     ".#uuauuuuuuauu#.",
     ".#uuauuuuuuauu#.",
     "..############..",
     "................")

icon("sets", "set.saisons", "Saisons", "❄️",
     "................",
     ".....######.....",
     "....#ll##aa#....",
     "...#lll##aaa#...",
     "..#lllL##aaaa#..",
     ".#lllLL##yaaaa#.",
     ".#llLLL##yyaaa#.",
     ".##############.",
     ".##############.",
     ".#hhhww##aaaoo#.",
     ".#hhhhw##aaooo#.",
     "..#hhhh##aooo#..",
     "...#hhh##ooo#...",
     "....#hh##oo#....",
     ".....######.....",
     "................")

icon("sets", "set.insectes", "Insectes", "🐞",
     "................",
     "....########....",
     "...#jjjjjjjj#...",
     "...#UUUUUUUU#...",
     "...##########...",
     "...#sshhhhhD#...",
     "..#swshhhhhDD#..",
     "..#swshhhhhDD#..",
     "..#swskkkhhDD#..",
     "..#sIEE#EEEDD#..",
     "..#sE#E#E#EDD#..",
     "..#sEEE#EEcDD#..",
     "..#sscc#cchDD#..",
     "...#sshhhhhD#...",
     "....########....",
     "................")

icon("sets", "set.champignons", "Champignons", "🍄",
     "................",
     "................",
     "................",
     "...#####.####...",
     "..#EwEEE#aaao#..",
     "..#EEEwc#aaooR#.",
     "..#EEEcc#aooRR#.",
     "...#####aooRRR#.",
     "..##ws########..",
     ".#UU##UUUU##UU#.",
     ".#jJjJjJjJjJjJ#.",
     "..#jJjJjJjJjJ#..",
     "..#JjJjJjJjJj#..",
     "...#JjJjJjJj#...",
     "....########....",
     "................")


# ---- Thèmes ------------------------------------------------------------------------------------

icon("themes", "cos.theme.prairie", "Prairie", "🌿",
     "................",
     "................",
     "....#......#....",
     "...#l#.#..#w#...",
     "...#l##l##wyw#..",
     "..#lL##l#.#w##..",
     "..#lL#lL#.#L#l#.",
     ".#llL#lLl#lLlL#.",
     ".#lLLllLLllLlL#.",
     ".#lLLLLLLLLLLt#.",
     ".#LLLLLLLLLLtt#.",
     ".#LLLLLLLLLttt#.",
     "..#tLLLLLLttt#..",
     "...##########...",
     "................",
     "................")

icon("themes", "cos.theme.aurore", "Aurore", "🌸",
     "................",
     ".......##.......",
     "...#..#yy#..#...",
     "..#y#.#yy#.#y#..",
     "...#y#.##.#y#...",
     "....#.####.#....",
     "..##.#wyyA#.##..",
     ".#yy#wyyyyA#yy#.",
     "..##yyyyyAAa##..",
     "..#AAAAAAAAAa#..",
     ".#IIIIiiiiIIII#.",
     ".#iiCCCyyCCCii#.",
     ".#CCrrraarrrCC#.",
     ".#rrrrrrrrrrrr#.",
     "..############..",
     "................")

icon("themes", "cos.theme.ocean", "Océan", "🌊",
     "................",
     "................",
     "........###.....",
     "......##www##...",
     ".....#wxxBxxw#..",
     "....#wxBBBbBxw#.",
     "..##bwxBdddBxw#.",
     ".#BbBwBBdddBBw#.",
     ".#bBBwBbddd###..",
     ".#BBBwxBBBBwww#.",
     ".#BBBbwxBBbBBB#.",
     ".#BBbBBwBbBBBB#.",
     ".#DDDDDDDDDDDD#.",
     ".#DDDDDDDDDDDD#.",
     "..############..",
     "................")

icon("themes", "cos.theme.braises", "Braises", "🔥",
     "................",
     ".......#........",
     "......#E#.......",
     ".....#EE#.......",
     ".....#EaE#.#....",
     "....#EaaE##E#...",
     "....#EayaE#E#...",
     "...#EayyaEEE#...",
     "...#EayyyaaE#...",
     "..#EaayyyyaE#...",
     "..#EaaywyyaaE#..",
     ".#cRcEaaaaEcRc#.",
     ".#RcaRcRRcRacR#.",
     "..#RRRRRRRRRR#..",
     "...##########...",
     "................")

icon("themes", "cos.theme.foret", "Forêt", "🌲",
     "................",
     "......#.........",
     ".....#L#........",
     "....#lLt#.......",
     "....#lLt#.......",
     "...#LLttt#.#....",
     "...#llLtt##T#...",
     "...#lLLtt#tT#...",
     "..#LLtttt#TTT#..",
     "..#llLLtt#tTT#..",
     "..#llLLLt#TTT#..",
     ".#LLLttttt#TTT#.",
     "..####u###uu##..",
     ".....#u#.#uu#...",
     "......#...##....",
     "................")

icon("themes", "cos.theme.lavande", "Lavande", "💜",
     "................",
     ".......##.......",
     "......#hb#......",
     ".....#hbPb##....",
     "....#hb#L#bP#...",
     ".....#hbLbP#....",
     "....#hb#L#bP#...",
     ".....#hbLbP#....",
     "....#hb#L#bP#...",
     ".....###L###....",
     "....#ll#L#ll#...",
     ".....#llLll#....",
     "......##L##.....",
     ".......#L#......",
     "........#.......",
     "................")

icon("themes", "cos.theme.desert", "Désert", "🌵",
     "................",
     "................",
     "......###.......",
     ".....#lLt#......",
     "...###lLt#......",
     "..#lt#lLt###....",
     "..#lt#lLt#lt#...",
     "..#lLllLt#lt#...",
     "...#ttlLtllt#...",
     "....##lLttt#....",
     "..####lLt###....",
     ".#JJJJlLtJJJ##..",
     ".#JJJJJJJJjjjj#.",
     ".#jjjjjjjjjjj#..",
     "..###########...",
     "................")

icon("themes", "cos.theme.arc_en_ciel", "Arc-en-ciel", "🌈",
     "................",
     "................",
     "................",
     "................",
     "................",
     "......####......",
     "....##EEEE##....",
     "...#EEaaaaEE#...",
     "..#EaayyyyaaE#..",
     ".#EEayllllyaEE#.",
     ".#EaylB##BlyaE#.",
     ".####B#..#B####.",
     ".#sss##..##sss#.",
     "..#s##....##s#..",
     "...#........#...",
     "................")

icon("themes", "cos.theme.nuit_etoilee", "Nuit étoilée", "✨",
     "................",
     "......####......",
     "....##dddd##....",
     "...#ddddddyd#...",
     "..#dwwddddddd#..",
     "..#dwwddddddd#..",
     ".#dwwyddddddwd#.",
     ".#dwyydddddddd#.",
     ".#dyyydddddhdd#.",
     ".#dyyyydddhyhd#.",
     "..#dyyaaaadhd#..",
     "..#ddaaaadddd#..",
     "...#dddddwdd#...",
     "....##dddd##....",
     "......####......",
     "................")

icon("themes", "cos.theme.aurore_boreale", "Aurore boréale", "🌌",
     "................",
     "......####......",
     "....##dddd##....",
     "...#ttdtddwt#...",
     "..#tLLdttddLL#..",
     "..#LlllLtddll#..",
     ".#dlxxxlLLlxxx#.",
     ".#lxddxxllxxdd#.",
     ".#xddddxxxxddd#.",
     ".#d#ddddd#dddd#.",
     "..##dd#d###d##..",
     "..###d#d###d##..",
     "...##########...",
     "....########....",
     "......####......",
     "................")

icon("themes", "cos.theme.royal", "Royal", "👑",
     "................",
     "...#............",
     "..#y##########..",
     "..#Uyyyyyyyyyy#.",
     "..#UVVVVVVVVVn#.",
     "..#UVVyVyVyVn#..",
     "..#UVVyyyyyVn#..",
     "..#UVVyEyEyn#...",
     "..#UVVVVVVn#....",
     "..#UVVVVVn#.....",
     "..#UVVVn##......",
     "..#UVn##........",
     "..#U##..........",
     "..#U#...........",
     "...#............",
     "................")

icon("themes", "cos.theme.cerisiers", "Cerisiers", "🍒",
     "................",
     "......##.#......",
     ".....#ww#w#.....",
     "....##wIIw##....",
     "...#wCIIIICw#...",
     "..#wIICiiCIIw#..",
     ".#w#IiCiiCiI#w#.",
     ".#wIIiiyaiiIIw#.",
     "..#IICiayiCII#..",
     "...#CiiiiiiC#...",
     "..#wIIiiiiIIw#..",
     "..#wwIIIIIIww#..",
     "...##wwCCww##...",
     ".....######.....",
     "................",
     "................")

icon("themes", "cos.theme.plage", "Plage", "🏖️",
     "................",
     "......####......",
     "....##Ewyw##....",
     "...#EEwBByww#...",
     "...#EwwBByyw#...",
     "..#EwwwBByyww#..",
     "..#EEwwBByyws#..",
     "..#EEwwBByyss#..",
     "..#EEwwBByass#..",
     "..#EEwwBBaass#..",
     "...#EwwBbaas#...",
     "..##E######s##..",
     ".#JJ#JJJJJJ#JJ#.",
     ".#jjjjjjjjjjjj#.",
     "..############..",
     "................")

icon("themes", "cos.theme.feuilles_mortes", "Feuilles mortes", "🍂",
     "................",
     ".......##.......",
     "......#ff#......",
     "....##fRfe##....",
     "...#f#fRee#e#...",
     "...#fffReeee#...",
     "..#ffReReeRoo#..",
     "...#feRReRoo#...",
     "..#fR#eReo#Ro#..",
     "...#e#eRoo#o#...",
     "....##eRoo##....",
     "......#RR#......",
     "......#R#.......",
     "......#R#.......",
     ".......#........",
     "................")

icon("themes", "cos.theme.flocons", "Flocons", "❄️",
     "................",
     ".....#..........",
     "...##x##...#....",
     "..#h#w#h#.#x#...",
     "..##hwh###xwx#..",
     ".#xwwwwwx##x#...",
     "..##hwh##..#....",
     "..#h#w#h#.......",
     "...##x##.#.#.#..",
     ".....#..#x#h#x#.",
     ".........#hwh#..",
     "........#hwwwh#.",
     ".........#hwh#..",
     "........#x#h#x#.",
     ".........#.#.#..",
     "................")

icon("themes", "cos.theme.champignonniere", "Champignonnière", "🍄",
     "................",
     "......####......",
     "....##AAoo##....",
     "...#AAAwooRR#...",
     "..#AAoooooowR#..",
     "..#AwooooooRR#..",
     "...#zzzzzzzz#...",
     "..#Ao##ws##AR#..",
     ".#AowR#ws#AowR#.",
     ".#zzzz#ws#zzzz#.",
     "..#ws##ws##ws#..",
     ".#lLlLlwslLlLl#.",
     ".#LLLLLLLLLLLt#.",
     "..#tttttttttt#..",
     "...##########...",
     "................")

icon("themes", "cos.theme.caverne_tresors", "Caverne aux trésors", "💎",
     "................",
     "................",
     "......####......",
     "....##bbbh##....",
     "...#bhbbbPPP#...",
     "..#bbbbbhPPPP#..",
     "..#bhb####PhP#..",
     ".#bbb#mmmm#Ppp#.",
     ".#bh#VVVVVV#pp#.",
     ".#bb#VVVVVV#ph#.",
     ".#hP#VV#VVV#pp#.",
     ".#PP#M#x##M#hp#.",
     ".#PP##axBa##pp#.",
     ".#PP#ayayaa#pp#.",
     "..############..",
     "................")


# ---- Titres -------------------------------------------------------------------------------------

icon("titres", "cos.title.petit", "Le Petit", "🏷️",
     "................",
     ".......##.......",
     "......#II#......",
     "......#Ii#......",
     ".....#iIii#.....",
     "....#iiiiCC#....",
     "....#whhhhD#....",
     "....#whhhhD#....",
     "....#wwwwwG#....",
     "....#wwwwsG#....",
     "....#wwwwsG#....",
     "....#wwwwsG#....",
     "....#swwwss#....",
     ".....#ssss#.....",
     "......####......",
     "................")

icon("titres", "cos.title.gourmet", "Le Gourmet", "🏷️",
     "................",
     "................",
     "...####.........",
     "..#JJJJ#........",
     "..#Jyyjj#.......",
     "..#JywajU#......",
     "..#JjaaaU#......",
     "...#jjaaU#......",
     "....#UUU#J#.....",
     ".....###JJJ#....",
     "...##...#JJJ#...",
     "..#aa#...#Jjj#..",
     "..#aa#....#jjj#.",
     "...##......#jj#.",
     "............##..",
     "................")

icon("titres", "cos.title.reveur", "Le Rêveur", "🏷️",
     "................",
     "...#............",
     "..#y#...........",
     ".#ywy#..........",
     "..#y#..####.....",
     "...#..#wwws#....",
     ".....#wwwsss#...",
     "...###wwsssh#...",
     "..#www#sssh#w#..",
     "..#wwss#sh#wss#.",
     "..#wssh#hh#ssh#.",
     "..#ss######shh#.",
     "...#h#hhhh#hh#..",
     "....#########...",
     "................",
     "................")

icon("titres", "cos.title.curieux", "Le Curieux", "🏷️",
     "................",
     "................",
     "....######......",
     "...#aaaaaa#.....",
     "..#aawxxxaa#....",
     "..#awxxxhha#....",
     "..#axxxhhha#....",
     "..#axxhhhha#....",
     "..#axhhhhh##....",
     "..#aahhhh#U#....",
     "...#aaaa#UUU#...",
     "....######UUu#..",
     "..........#uuu#.",
     "...........#uu#.",
     "............##..",
     "................")

icon("titres", "cos.title.dormeur", "Le Dormeur", "🏷️",
     "................",
     "............##..",
     "...........#ws#.",
     "..........#E#s#.",
     ".........#ww##..",
     "........#wwE#...",
     ".......#wEEE#...",
     ".....##EEEww#...",
     "....#EEEwwwE#...",
     "...#EEwwwEEE#...",
     "..#EwwwEEEww#...",
     ".#w#########w#..",
     ".#sssssssssss#..",
     "..###########...",
     "................",
     "................")

icon("titres", "cos.title.mysterieux", "Le Mystérieux", "🏷️",
     "................",
     "................",
     "................",
     "...##########...",
     "..#nVVVVVVVVn#..",
     ".#VnnVVVVVnnVV#.",
     ".#V##VVVV##VVV#.",
     ".#VVVVVVVVVVVV#.",
     "..#VVVn##nVVV#..",
     "...#VV#..#VV#...",
     "....##....##....",
     "................",
     "................",
     "................",
     "................",
     "................")

icon("titres", "cos.title.farceur", "Le Farceur", "🏷️",
     "................",
     "..#..........#..",
     ".#y##......##y#.",
     ".#yEE#....#aay#.",
     "..#EEE#..#aaa#..",
     "..#EEEE##aaaa#..",
     "...#EEEEaaaa#...",
     "...#EEEEaaaa#...",
     "..#EEEEEaaaaa#..",
     "..#EEEEEaaaaa#..",
     ".#wwwwwwwwwwww#.",
     ".#ssssssssssss#.",
     "..############..",
     "................",
     "................",
     "................")

icon("titres", "cos.title.aventurier", "L'Aventurier", "🏷️",
     "................",
     ".........###....",
     "........#ccc#...",
     "........#####...",
     ".......#eweeE#..",
     "......#eeeeEEw#.",
     "......#eeewEEc#.",
     "......#weEEEcc#.",
     "......##EEEwcc#.",
     ".....#uu#Eccc#..",
     "....#uu######...",
     "...#uu#.........",
     "..#uu#..........",
     "..#u#...........",
     "...#............",
     "................")

icon("titres", "cos.title.champion", "Le Champion", "🏷️",
     "................",
     "....##....##....",
     "...#EE#..#cc#...",
     "...#EEE##ccc#...",
     "...#EEE##ccc#...",
     "....#EE##cc#....",
     "....#E#yy#c#....",
     "....##wyaa##....",
     "...#yyyooaao#...",
     "...#yyoooooo#...",
     "...#yaaooooo#...",
     "...#aaoaoooo#...",
     "....#aaoooo#....",
     ".....#oooo#.....",
     "......####......",
     "................")

icon("titres", "cos.title.sage", "Le Sage", "🏷️",
     "................",
     "...#........#...",
     "..#U#......#U#..",
     "..#UU######UU#..",
     "..#UjjjjjjjjU#..",
     "..#jwwjjjjwwj#..",
     ".#jwyywjjwyywj#.",
     ".#jwy#wjjwy#wj#.",
     ".#Ujwwjaajwwju#.",
     ".#UjjJJaaJJjju#.",
     ".#UUjJjJjJjuuu#.",
     "..#UUJjJjJjuu#..",
     "...#uuaaaauu#...",
     "....########....",
     "................",
     "................")

icon("titres", "cos.title.legendaire", "Le Légendaire", "🏷️",
     "................",
     "................",
     ".......##.......",
     "......#yy#......",
     "......#wy#......",
     "..#####yy#####..",
     ".#yyyyyyyyyyaa#.",
     "..#yyyyyyyyaa#..",
     "...#yyyyyyaa#...",
     "....#yyyyaa#....",
     "....#yyyaaa#....",
     "....#yyaaaa#....",
     "...#yy####aa#...",
     "...#y#....#a#...",
     "....#......#....",
     "................")

icon("titres", "cos.title.chercheur_tresors", "Le Chercheur de trésors", "🏷️",
     "................",
     "...........##...",
     "..........#UU#..",
     ".........#U#UU#.",
     "..........#j##..",
     ".........#j#....",
     "........#j#.....",
     ".......#j#......",
     "....###j#.......",
     "...#ssG#........",
     "..#swGGg#.......",
     ".#ssGGg#........",
     ".#sGGg#.........",
     ".#GGg#..........",
     "..###...........",
     "................")

icon("titres", "cos.title.botaniste", "Le Botaniste", "🏷️",
     "................",
     "................",
     ".........####...",
     "...######llll#..",
     "..#lllLL#LLLL#..",
     "..#LLLL#L#LL#...",
     "...##L#LL###....",
     ".....##LL#......",
     "...####LL####...",
     "..#AAAA##AAAA#..",
     "...#aaaooooo#...",
     "...#aaaooooo#...",
     "...#aaaooooo#...",
     "....#aaoooo#....",
     ".....######.....",
     "................")


# ---- Accessoires -------------------------------------------------------------------------------

icon("accessoires", "cos.accessory.noeud", "un nœud", "🎀",
     "................",
     "................",
     "................",
     "..##.......##...",
     ".#IC#.....#Ci#..",
     ".#IiC#...#CiC#..",
     ".#IiiC###CiiC#..",
     ".#IiiiCIiCiiC#..",
     ".#IiiC#Cc#CiC#..",
     ".#IiC##CC##CC#..",
     ".#iC##CcCc##C#..",
     ".#C#.#Cc#Cc##...",
     "..#..#C#.#C#....",
     "......#...#.....",
     "................",
     "................")

icon("accessoires", "cos.accessory.echarpe", "une écharpe", "🧣",
     "................",
     "................",
     "...#########....",
     "..#EwEwEwEwE#...",
     ".#EwEwEwEwEwE#..",
     ".#wE########wE#.",
     ".#Ew########Ew#.",
     ".#wEwEwEwEwEwE#.",
     "..#EwEwEwEwEE#..",
     "...#######wE#...",
     ".........#Ew#...",
     ".........#wE#...",
     ".........#Ew#...",
     "........#s#s#...",
     ".........#.#....",
     "................")

icon("accessoires", "cos.accessory.fleur", "une fleur", "🌼",
     "................",
     "................",
     "......####......",
     "....##wwww##....",
     "...#sswwwsss#...",
     "...#sswwwsss#...",
     "..#wsssyysssw#..",
     "..#wwwyyaawww#..",
     "..#wwwyaaawww#..",
     "..#wwwsaasssw#..",
     "...#ssswwwss#...",
     "...#ssswwwss#...",
     "....##wwww##....",
     "......####......",
     "................",
     "................")

icon("accessoires", "cos.accessory.casquette", "une casquette", "🧢",
     "................",
     "................",
     ".......##.......",
     ".....######.....",
     "....#BBbBBB#....",
     "...#BBBbBBBB#...",
     "..#BBBBbBBBBb#..",
     "..#BBBBbBBBbb#..",
     "..#BBBBbBBbbb#..",
     "..############..",
     ".#bbbbbbbbbbbb#.",
     ".#dddddddddddd#.",
     "..##dddddddd##..",
     "....########....",
     "................",
     "................")

icon("accessoires", "cos.accessory.ballon", "un ballon", "🎈",
     "................",
     "......####......",
     ".....#eeee#.....",
     "....#IeeeEE#....",
     "...#IIeeEEEE#...",
     "...#eeeEEEEc#...",
     "...#eeEEEEcc#...",
     "...#eEEEEccc#...",
     "...#EEEEcccc#...",
     "....#EEcccc#....",
     "....#Eccccc#....",
     ".....######.....",
     "......#s#.......",
     ".......#s#......",
     "........#.......",
     "................")

icon("accessoires", "cos.accessory.lunettes", "des lunettes de soleil", "🕶️",
     "................",
     "................",
     "................",
     "................",
     "..############..",
     ".#kkkkkkkkkkkk#.",
     ".#kwpppkkwpppk#.",
     ".#kppppkkppppk#.",
     "..#kppk##kppk#..",
     "...#kk#..#kk#...",
     "....##....##....",
     "................",
     "................",
     "................",
     "................",
     "................")

icon("accessoires", "cos.accessory.sac_a_dos", "un petit sac à dos", "🎒",
     "................",
     "......####......",
     ".....#UUUU#.....",
     "....#U####U#....",
     "...#lLLLLLLt#...",
     "..#lLLLLLLLLt#..",
     "..#lLUlLLlULt#..",
     "..#lLUlLLlULt#..",
     "..#lLUtttLULt#..",
     "..#lLUlLLtULt#..",
     "..#lLUlLLtULt#..",
     "..#lLUtttLULt#..",
     "..#tLLLLLLLtt#..",
     "...#tttttttt#...",
     "....########....",
     "................")

icon("accessoires", "cos.accessory.casque_audio", "un casque audio", "🎧",
     "................",
     "................",
     "................",
     ".....######.....",
     "....#GGGGGG#....",
     "...#gg####gg#...",
     "..#gg#....#gg#..",
     "..#g#......#g#..",
     ".#g#g#....#g#g#.",
     ".##kE#....#Ek##.",
     ".#kkE#....#Ekk#.",
     ".#kkE#....#Ekk#.",
     ".#kkk#....#kkk#.",
     "..###......###..",
     "................",
     "................")

icon("accessoires", "cos.accessory.haut_de_forme", "un haut-de-forme", "🎩",
     "................",
     "....#######.....",
     "...#Gkkkkkk#....",
     "...#Gkkkkkk#....",
     "...#gkkkkkk#....",
     "...#gkkkkkk#....",
     "...#gkkkkkk#....",
     "...#EEEEEEc#....",
     "...#EEEEEEc#....",
     "..##gkkkkkk##...",
     ".#Gggkkkkkkkk#..",
     ".#gkkkkkkkkkk#..",
     "..###########...",
     "................",
     "................",
     "................")

icon("accessoires", "cos.accessory.baguette", "une baguette magique", "🪄",
     "................",
     "........###.....",
     "......##yyy##...",
     ".....#yyyyyyy#..",
     "......#yyyyy#...",
     "......#yy#yy#...",
     "..#....##w##.#..",
     ".#w#...#wk#.#w#.",
     "..#...#wk#..##..",
     ".....#wk#..#w#..",
     "....#wk#....#...",
     "...#wk#.........",
     "..#wk#..........",
     "..#k#...........",
     "...#............",
     "................")

icon("accessoires", "cos.accessory.couronne", "une petite couronne", "👑",
     "................",
     "................",
     "................",
     "...#...#...#....",
     "..#y#.#y#.#y#...",
     "..#ay#yyy#ya#...",
     "..#ayyyyyyya#...",
     "..#ayyyByyya#...",
     "..#ayyyyyyao#...",
     "..#ooooooooo#...",
     "...#########....",
     "................",
     "................",
     "................",
     "................",
     "................")

icon("accessoires", "cos.accessory.tulipe", "une tulipe", "🌷",
     "................",
     "....#..#..#.....",
     "...#E##E##E#....",
     "...#EE#eE#EE#...",
     "...#eEEEEEEc#...",
     "...#eEEEEEEc#...",
     "...#eEEEEEcc#...",
     "....#EEEEcc#....",
     ".....#cccc#.....",
     "...#..#L##......",
     "..#l#.#L#.##....",
     "..#lL##L##tL#...",
     "...#LL#L#LL#....",
     "....#LLLLL#.....",
     ".....#####......",
     "................")

icon("accessoires", "cos.accessory.glace", "une glace", "🍦",
     "................",
     "................",
     "......####......",
     ".....#wIIi#.....",
     "....#wIIiii#....",
     "...#IIIiiiiC#...",
     "...#IIiiiiC##...",
     "...########j##..",
     "....#JJjJJj##...",
     "....#JjJJjJ#....",
     ".....#JJjJ#.....",
     "......#jJ#......",
     "......#JJ#......",
     ".......##.......",
     "................",
     "................")

icon("accessoires", "cos.accessory.moufles", "des moufles", "🧤",
     "................",
     "...###....###...",
     "..#eEE#..#eEE#..",
     ".#eEEEE##eEEEE#.",
     ".#eEEEE##eEEEE#.",
     ".#eEEEE##eEEEE#.",
     ".#eEEEc##eEEEc#.",
     ".#EEEEc##eEEEE#.",
     ".#EEEcc##EEEcc#.",
     ".#wwwww##wwwww#.",
     ".#sssss##sssss#.",
     "..#####..#####..",
     "................",
     "................",
     "................",
     "................")

icon("accessoires", "cos.accessory.plume_doree", "une plume d'or", "🪶",
     "................",
     "..........###...",
     ".........#yya#..",
     "........#yyaoa#.",
     ".......#yyaoaa#.",
     "......#yyaoaaa#.",
     ".....#yyaoaao#..",
     "....#yyaoaao#...",
     "...#yaaoaao#....",
     "...#aaoaoo#.....",
     "...#aoaoo#......",
     "..#ko####.......",
     ".#k##...........",
     "..##b#..........",
     "....#...........",
     "................")

icon("accessoires", "cos.accessory.collier_coquillages", "un collier de coquillages", "🐚",
     "................",
     "....########....",
     "...#UUUUUUUU#...",
     "..#UU######UU#..",
     "..#U#......#U#..",
     ".#UU#......#UU#.",
     ".#U#........#U#.",
     ".#u#........#u#.",
     ".#uu##....##uu#.",
     "..#u#w####w#u#..",
     "..#u#wI#I#I#u#..",
     "...#wI#II#Ii#...",
     "....#i#Ii#i#....",
     ".....#.##.#.....",
     "................",
     "................")


# ---- Cadres -------------------------------------------------------------------------------------

icon("cadres", "cos.grave.bougies", "Bougies", "🕯️",
     "................",
     "....#...........",
     "...#y#..........",
     "..#yay#.....#...",
     "..#yay#....#y#..",
     "...#a#....#yay#.",
     "...#k##...#yay#.",
     "..#wwss#...#a#..",
     "..#wwss#...#k#..",
     "..#wwss#..#wss#.",
     "..#wwss#..#wss#.",
     "..#wwss#.##wss#.",
     ".#GGGGGG#GGGGG#.",
     "..######.#####..",
     "................",
     "................")

icon("cadres", "cos.grave.couronne_fleurs", "Couronne de fleurs", "💐",
     "................",
     ".......##.......",
     ".....##ll##.....",
     "....#lwllIL#....",
     "...#lllllLLL#...",
     "..#lll####LLL#..",
     "..#yl#....#Ly#..",
     ".#lll#....#ttt#.",
     ".#lll#....#ttt#.",
     "..#IL#....#tI#..",
     "..#LLL####ttt#..",
     "...#LLLttttt#...",
     "....#Lwttyt#....",
     ".....##tt##.....",
     ".......##.......",
     "................")

icon("cadres", "cos.grave.feuilles", "Feuilles", "🍂",
     "................",
     "................",
     "................",
     ".......##.......",
     "......#ya#......",
     "......#ya#......",
     "..#..#yyaa#..#..",
     ".#o###yyaa###A#.",
     ".#RRo#yyaa#ARR#.",
     ".#aRRo#ya#ARRa#.",
     ".#aaRR#ya#RRaa#.",
     "..#aaaR##Rooa#..",
     "...#aaa##ooo#...",
     "....########....",
     "................",
     "................")

icon("cadres", "cos.grave.galets", "Galets", "🪨",
     "................",
     "................",
     "................",
     "......####......",
     ".....#wsss#.....",
     "....#wsssGG#....",
     ".....######.....",
     "....#JJjjjj#....",
     "...#JJjjjjUU#...",
     "....########....",
     "...#ssGGGGGg#...",
     "..#ssGGGGGggg#..",
     "..#sGGGGGgggg#..",
     "...##GGGggg##...",
     ".....######.....",
     "................")

icon("cadres", "cos.grave.ble", "Blé", "🌾",
     "................",
     "...#...##...#...",
     "..#y#.#ya#.#a#..",
     "..#ay#yaya#ay#..",
     "..#yay#ya#aya#..",
     "..#aya#ay#yay#..",
     "...##y####a##...",
     "...#j#jJjJ#J#...",
     "....#JjJjJj#....",
     ".....#jJjJ#.....",
     ".....#UUUU#.....",
     ".....#jJjJ#.....",
     "....#JjJjJj#....",
     "...#jJjJjJjJ#...",
     "....########....",
     "................")

icon("cadres", "cos.grave.etoiles", "Étoiles", "⭐",
     "................",
     "................",
     ".....#..........",
     "....#y#.........",
     "..###yy###......",
     ".#yywyyyya#.....",
     "..#yyyyya#......",
     "...#yyya#.......",
     "...#yyaa#..#....",
     "..#yy##a###y##..",
     "...##..##yyaaa#.",
     ".........#aaa#..",
     ".........#aaa#..",
     "..........###...",
     "................",
     "................")

icon("cadres", "cos.grave.colombes", "Colombes", "🕊️",
     "................",
     "..........##....",
     ".........#ww#...",
     "........#wws#...",
     "...##..#wwss#...",
     "..#ww#.#wws#....",
     ".#akw##wwss##...",
     "..#wwwwwwwssw#..",
     "...#wwwwwwsssw#.",
     "....#sswwwsss#..",
     ".....#ssssss#...",
     "......######....",
     "................",
     "................",
     "................",
     "................")

icon("cadres", "cos.grave.papillons", "Papillons", "🦋",
     "................",
     "..##...##.......",
     ".#yy#.#yy#......",
     ".#yAy#yAy#......",
     ".#yAAUAAy#......",
     "..#yAUAy#.......",
     "..#yA#Ay#.......",
     "...#y#y##...##..",
     "....#.#yy#.#yy#.",
     "......#yAy#yAy#.",
     "......#yAAUAAy#.",
     ".......#yAUAy#..",
     ".......#yA#Ay#..",
     "........#y#y#...",
     ".........#.#....",
     "................")

icon("cadres", "cos.grave.clair_de_lune", "Clair de lune", "🌙",
     "................",
     "................",
     ".........##.....",
     "........#ss##...",
     ".........#sww#..",
     ".........#sww#..",
     ".........#swww#.",
     ".........#swww#.",
     ".........#ssss#.",
     "........##ssss#.",
     "......##hhsss#..",
     ".....#hhhhsss#..",
     "......#hhhs##...",
     ".......####.....",
     "................",
     "................")

icon("cadres", "cos.grave.lanternes", "Lanternes", "🏮",
     "................",
     ".......##.......",
     ".....##kk##.....",
     "....#aa##aa#....",
     ".....######.....",
     "....#eeeeEE#....",
     "...#cccccccc#...",
     "..#eeyeEEEEcc#..",
     "..#eeeEEEEccc#..",
     "...#cccccccc#...",
     "...#EEEEcccc#...",
     "....##Eccc##....",
     "....#a####a#....",
     ".....######.....",
     ".......##.......",
     "................")

icon("cadres", "cos.grave.aura_doree", "Aura dorée", "✨",
     "................",
     "....#...........",
     "...#w#......#...",
     "..#www#....#y#..",
     "...#########wy#.",
     "..##yyyyyyyy##..",
     ".#yyyyy##yyyyy#.",
     ".#yy###..###yy#.",
     ".#aa#......#aa#.",
     ".#aa###..###aa#.",
     ".#aaaaa##aaaaa#.",
     "..##aaaaaaaa##..",
     ".#yw########w#..",
     "..#y#.....#www#.",
     "...#.......###..",
     "................")

icon("cadres", "cos.grave.cristaux", "Cristaux", "💎",
     "................",
     ".......##.......",
     "......#wx#......",
     ".....#wxBb#.....",
     "..##.#wxBb###...",
     ".#wI##wxBb#Cn#..",
     ".#Ii##xxBb#Cn#..",
     ".#Ii##xxBb#nV#..",
     ".#Ii##xBBb#nV#..",
     ".#iC##xBbb#nV#..",
     ".#iC##BBbb#VM#..",
     ".#CM##Bbbd#VM#..",
     ".#gGgGgGgGgGg#..",
     "..###########...",
     "................",
     "................")

icon("cadres", "cos.grave.cercle_fees", "Cercle de fées", "🍄",
     "................",
     ".......#........",
     "......#y#.......",
     ".....#ywy#......",
     "....###y####....",
     "...#EEE##EEE##..",
     "..#EwEEE#EwEEE#.",
     "..#cEEEc#cEEEc#.",
     "..###ww#.#ww##..",
     ".#EE#ww###wwEE#.",
     ".#lLllLLllLLlL#.",
     ".#LLLLLLLLLLLL#.",
     "..#tttttttttt#..",
     "...##########...",
     "................",
     "................")


# ---- Traits -------------------------------------------------------------------------------------
# A Plynling trait is a tile, as in CK3: a framed square whose rim and background say the kind,
# with the symbol on it. Only the symbol is drawn by hand; tile() composes the frame.

TRAIT_KINDS = {
    # kind: (rim lit, rim shaded, background, background shaded)
    "childhood": ("y", "a", "r", "z"),
    "personality": ("J", "j", "t", "T"),
    "coping": ("s", "G", "P", "p"),
}


def outlined(*fill):
    """A symbol's fill (at most 8×8) wrapped in the 1-pixel outline: every empty cell touching the
    fill becomes "#". Holes of one or two cells come out dark, like a shadow."""
    w = max(len(r) for r in fill) + 2
    rows = ["." * w] + ["." + r.ljust(w - 2, ".") + "." for r in fill] + ["." * w]
    def filled(x, y):
        return 0 <= y < len(rows) and 0 <= x < w and rows[y][x] != "."
    return ["".join(c if c != "." or not any(filled(x + dx, y + dy) for dx, dy in ((1, 0), (-1, 0), (0, 1), (0, -1)))
                    else "#" for x, c in enumerate(r)) for y, r in enumerate(rows)]


def tile(kind, *symbol, at=None, glints=()):
    """A 16×16 trait tile: a 1-pixel outline, a rim lit from the top left, a two-tone background,
    and the symbol (at most 10×10, "." where the background shows) centred in the 10×10 inside —
    or with its top left at `at`. glints are (x, y, char) in tile coordinates, set last, for
    details that take no outline (steam, sparkles)."""
    lit, shade, bg, bg_shade = TRAIT_KINDS[kind]
    rows = [r for r in symbol if r.strip(".")]
    left = min(len(r) - len(r.lstrip(".")) for r in rows)
    width = max(len(r.rstrip(".")) for r in rows) - left
    rows = [r[left:left + width].ljust(width, ".") for r in rows]
    assert width <= 10 and len(rows) <= 10, f"a trait symbol is at most 10×10, not {width}×{len(rows)}"
    ox, oy = at or (3 + (10 - width) // 2, 3 + (10 - len(rows)) // 2)
    assert 3 <= ox and ox + width <= 13 and 3 <= oy and oy + len(rows) <= 13, "the symbol leaves the inside"
    grid = []
    for y in range(16):
        row = []
        for x in range(16):
            if not (1 <= x <= 14 and 1 <= y <= 14) or (x in (1, 14) and y in (1, 14)):
                row.append(".")
            elif x in (1, 14) or y in (1, 14) or (x in (2, 13) and y in (2, 13)):
                row.append("#")
            elif x in (2, 13) or y in (2, 13):
                row.append(lit if x == 2 or y == 2 else shade)
            else:
                sx, sy = x - ox, y - oy
                c = rows[sy][sx] if 0 <= sy < len(rows) and 0 <= sx < width else "."
                row.append(c if c != "." else bg if x + y <= 18 else bg_shade)
        grid.append(row)
    for x, y, c in glints:
        assert 3 <= x <= 12 and 3 <= y <= 12, f"glint ({x},{y}) outside the inside"
        grid[y][x] = c
    return ["".join(r) for r in grid]


# Enfance

icon("traits_enfance", "trait.bossy", "Autoritaire", "📣", *tile("childhood",
     ".....####.",
     "...##EEEw#",
     ".##fEEEEw#",
     "#GfEEEEEw#",
     "#GcEEEEEs#",
     ".##cEEEcs#",
     "...##cccG#",
     "....#U###.",
     "....#U#...",
     ".....#...."))

icon("traits_enfance", "trait.charming", "Adorable", "🥺", *tile("childhood",
     "..######..",
     ".#yyyyyy#.",
     "#yyyyyyyA#",
     "#yw#yyw#A#",
     "#y##yy##A#",
     "#iyyyyyiA#",
     "#Ayy##yyA#",
     ".#AyyyyA#.",
     "..######.."))

icon("traits_enfance", "trait.curious", "Curieux", "🔍", *tile("childhood",
     "..####....",
     ".#xxxh#...",
     "#xwxhhb#..",
     "#wxhhhb#..",
     "#xhhhbb#..",
     "#hhhbbd#..",
     ".#hbbd###.",
     "..####UU#.",
     "......#UU#",
     ".......##."))

icon("traits_enfance", "trait.pensive", "Rêveur", "☁️", *tile("childhood",
     ".y........",
     "yyy.###...",
     ".y.#wws#..",
     ".##wwwss##",
     "#wwwwsssG#",
     "#wwssssGG#",
     "#sssGGGGg#",
     ".########."))

icon("traits_enfance", "trait.rowdy", "Turbulent", "🌪️", *tile("childhood",
     ".########.",
     "#wwsssssG#",
     "#GGGGGggg#",
     ".##ssssG#.",
     "..#GGggg#.",
     "..##ssG#..",
     "...#Ggg#..",
     "....#sG#..",
     "....#g#...",
     ".....#...."))


# Personnalité (1)

icon("traits_perso_1", "trait.brave", "Courageux", "🦁", *tile("personality", *outlined(
     ".o.oo.o.",
     "ooRooRoo",
     "oRyyyyRo",
     "Ry#yy#aR",
     "oyyyyyao",
     "Roy##aoR",
     ".Royyao.",
     "..RooR..")))

icon("traits_perso_1", "trait.craven", "Peureux", "🫣", *tile("personality", *outlined(
     ".wI..wI.",
     ".wI..wI.",
     ".ws..ws.",
     "wwwwwwss",
     "ww#ww#ss",
     "wiwIIwis",
     ".wwwwss.",
     "..ssGG..")))

icon("traits_perso_1", "trait.calm", "Calme", "🍃", *tile("personality", *outlined(
     ".....llY",
     "...lllYL",
     "..lllYLL",
     ".lllYLLL",
     ".llYLLL.",
     ".lYLLL..",
     ".YLL....",
     "Y.......")))

icon("traits_perso_1", "trait.wrathful", "Colérique", "💢", *tile("personality", *outlined(
     "...E....",
     "..EE..E.",
     "..EfE.EE",
     ".EEffEEE",
     "EEfyyfEc",
     "Efyywyfc",
     "Efyyyyfc",
     ".cfyyfc.")))

icon("traits_perso_1", "trait.chaste", "Pudique", "🙈", *tile("personality", *outlined(
     "...ws...",
     "w..ws..s",
     "ww.ws.ss",
     "wwwyysss",
     ".wwyyss.",
     "..wsss..",
     "...LL...",
     "..LL.L..")))

icon("traits_perso_1", "trait.lustful", "Fleur bleue", "💘", *tile("personality", *outlined(
     ".ii..ii.",
     "iwiiiiiC",
     "iiiiiiiC",
     "iiiiiiCC",
     ".iiiiCC.",
     "..iiCC..",
     "...CC..."),
     glints=((12, 3, "s"), (11, 3, "s"), (12, 4, "s"), (11, 4, "U"), (10, 5, "U"), (9, 6, "U"), (8, 7, "U"),
             (7, 8, "U"), (6, 9, "U"), (5, 10, "U"), (4, 11, "w"), (3, 11, "w"), (4, 12, "w"))))

icon("traits_perso_1", "trait.content", "Content", "😌", *tile("personality", *outlined(
     "sUUUUG..",
     "wsssGGGG",
     "wsssGG.G",
     "wsssGGGG",
     ".ssGG..."), at=(3, 6),
     glints=((5, 3, "w"), (6, 4, "w"), (5, 5, "w"), (8, 3, "w"), (9, 4, "w"), (8, 5, "w"))))

icon("traits_perso_1", "trait.ambitious", "Ambitieux", "🏆", *tile("personality", *outlined(
     "yywyyyaa",
     "y.wyyy.a",
     "yywyyyaa",
     "..yyya..",
     "...ya...",
     "...ya...",
     "..aaao..",
     ".UUUUUu.")))

icon("traits_perso_1", "trait.diligent", "Travailleur", "🧺", *tile("personality", *outlined(
     "..UUUU..",
     ".U....U.",
     ".U....U.",
     "sGhGsGhG",
     "jJjJjJjJ",
     "JjJjJjJj",
     ".jJjJjJ.",
     "..uuuu..")))

icon("traits_perso_1", "trait.lazy", "Paresseux", "🛌", *tile("personality", *outlined(
     ".wwwwws.",
     "wwsssssG",
     "wsssssGG",
     ".sGGGGG."), at=(3, 7),
     glints=((8, 3, "w"), (9, 3, "w"), (10, 3, "w"), (11, 3, "w"), (10, 4, "w"), (9, 5, "w"),
             (8, 6, "w"), (9, 6, "w"), (10, 6, "w"), (11, 6, "w"),
             (5, 5, "w"), (6, 5, "w"), (5, 6, "w"), (6, 6, "w"))))

icon("traits_perso_1", "trait.stubborn", "Têtu", "🪨", *tile("personality", *outlined(
     "..sssG..",
     ".ssssGGg",
     "s#GGGG#g",
     "sG#GG#gg",
     "sGGGGggk",
     "GGgggggk",
     ".ggggkk.")))

icon("traits_perso_1", "trait.fickle", "Lunatique", "🌗", *tile("personality", *outlined(
     "..wyPP..",
     ".wyyPPp.",
     "wyyyPPpp",
     "yyyyPPpp",
     "yyyyPppp",
     "ayyyPppp",
     ".aayPpp.",
     "..aaPp..")))

# Personnalité (2)

icon("traits_perso_2", "trait.forgiving", "Indulgent", "🤲", *tile("personality", *outlined(
     ".....ws.",
     "....wws.",
     ".ww.wss.",
     "aw#wwssG",
     "lwwwsssG",
     "l.sssGG.",
     "....GG..")))

icon("traits_perso_2", "trait.vengeful", "Rancunier", "📝", *tile("personality", *outlined(
     "JJJJJ..w",
     "JUUUJ.ws",
     "JJJJJws.",
     "JEEEws..",
     "JJJkJ...",
     "JUUUJ...",
     "JJJJJ...",
     "jjjjj...")))

icon("traits_perso_2", "trait.generous", "Généreux", "🎁", *tile("personality", *outlined(
     ".yy..yy.",
     "..yyyy..",
     "EEEyaEEE",
     "cccyaccc",
     ".EEyaEc.",
     ".EEyaEc.",
     ".EEyaEc.",
     ".ccyacc.")))

icon("traits_perso_2", "trait.greedy", "Radin", "🪙", *tile("personality", *outlined(
     "..jJJj..",
     "...uu...",
     "..JJJj..",
     ".JJJJJj.",
     "JJJyaJjj",
     "JJJaojjj",
     ".JJjjjj.",
     "..jjjj..")))

icon("traits_perso_2", "trait.gregarious", "Sociable", "🗣️", *tile("personality", *outlined(
     "wwwwws..",
     "wkwkws..",
     "swwwss..",
     ".s.hhhhh",
     "...hkhkh",
     "...hhhhD",
     "......D.")))

icon("traits_perso_2", "trait.shy", "Timide", "🫥", *tile("personality", *outlined(
     "jUu.yy..",
     "jUuyyyy.",
     "jUu#yyyA",
     "jUuiyyyA",
     "jUuyyyA.",
     "jUu.AA..",
     "jUu.....",
     "jUu.....")))

icon("traits_perso_2", "trait.honest", "Franc", "🫡", *tile("personality", *outlined(
     "...J.J..",
     ".J.J.J.J",
     ".J.J.J.J",
     ".JJJJJJJ",
     "JJJJJJJj",
     ".JJJJJjj",
     "..JJJjj.",
     "..jjjj..")))

icon("traits_perso_2", "trait.deceitful", "Menteur", "🤥", *tile("personality", *outlined(
     "C......c",
     "CiC..Ccc",
     "C##CC##c",
     "C##CC##c",
     ".CCccCc.",
     ".....J..",
     ".....J..",
     "....J...")))

icon("traits_perso_2", "trait.humble", "Modeste", "🌱", *tile("personality", *outlined(
     "ll....LL",
     "lll..LLL",
     ".lllLLL.",
     "...l....",
     "...l....",
     ".uUUUUu.",
     "uUUUUUUu")))

icon("traits_perso_2", "trait.arrogant", "Vaniteux", "🪞", *tile("personality", *outlined(
     "..yyyy..",
     ".yxwhhy.",
     ".yxhhby.",
     ".yhhbby.",
     ".yhbbdy.",
     "..yyya..",
     "...ya...",
     "...ya...")))

icon("traits_perso_2", "trait.just", "Juste", "⚖️", *tile("personality", *outlined(
     "...yy...",
     "yyyyyyya",
     "s..ya..s",
     "s..ya..s",
     "ya.ya.ya",
     "...ya...",
     "..yyaa..",
     ".aaaaao.")))

icon("traits_perso_2", "trait.arbitrary", "Capricieux", "🎲", *tile("personality", *outlined(
     ".wwwws.",
     "wkwwwks",
     "wwwwwss",
     "wwwkwss",
     "wwwwwss",
     "wkwwsks",
     ".sssss.")))

# Personnalité (3)

icon("traits_perso_3", "trait.patient", "Patient", "⏳", *tile("personality", *outlined(
     "uUUUUUUu",
     ".hhhhhh.",
     "..yyyy..",
     "...ya...",
     "...ha...",
     "..hyyh..",
     ".hyyaah.",
     "uUUUUUUu")))

icon("traits_perso_3", "trait.impatient", "Impatient", "⏰", *tile("personality", *outlined(
     ".EE..EE.",
     "EEEEEEEc",
     "Ewwkwwsc",
     "Ewwkwwsc",
     "Ewwkkksc",
     "Ewwwwssc",
     ".cEEEEc.",
     ".c....c.")))

icon("traits_perso_3", "trait.temperate", "Frugal", "🥣", *tile("personality", *outlined(
     "...fE...",
     "...Ec...",
     "wwwwwwws",
     "swwwwwsG",
     "sssssGGG",
     ".ssssGG.",
     "..GGGG..")))

icon("traits_perso_3", "trait.gluttonous", "Gourmand", "🍯", *tile("personality", *outlined(
     ".jJJJJj.",
     ".yyyyya.",
     "oyyoyyaR",
     "oyooyoRR",
     "ooooyoRR",
     "ooooooRR",
     ".ooooRR.",
     "..RRRR..")))

icon("traits_perso_3", "trait.trusting", "Confiant", "🤝", *tile("personality", *outlined(
     ".sss....",
     "s...s...",
     "s...s...",
     "....s...",
     "..yyyyya",
     "..yy#yaa",
     "..yy#aaa",
     "..aaaaao")))

icon("traits_perso_3", "trait.paranoid", "Méfiant", "👀", *tile("personality", *outlined(
     "..ssss..",
     ".wwwbbs.",
     "wwwbk#bs",
     "wwwb##bs",
     ".wwwbbs.",
     "..ssss..")))

icon("traits_perso_3", "trait.zealous", "Superstitieux", "🍀", *tile("personality", *outlined(
     ".ll#lL.",
     "lll#lLL",
     "lll#LLL",
     "###Y###",
     "lll#LLL",
     "llL#LLL",
     ".lL#LL.",
     "....L..")))

icon("traits_perso_3", "trait.cynical", "Sceptique", "🤨", *tile("personality", *outlined(
     "..yyyy..",
     ".y##yyyA",
     "yyyyy##A",
     "yy#yyy#A",
     "yyyyyyyA",
     "yyy###yA",
     ".yyyyyA.",
     "..AAAA..")))

icon("traits_perso_3", "trait.compassionate", "Bienveillant", "💗", *tile("personality", *outlined(
     ".ii..ii.",
     ".iwiiiC.",
     ".iiiiCC.",
     "J.iiCC.J",
     "JJ.CC.JJ",
     "JJJJJJJj",
     ".jjjjjj.")))

icon("traits_perso_3", "trait.callous", "Froid", "🧊", *tile("personality", *outlined(
     ".xxxxxx.",
     "xwwxxxxh",
     "xwxxxxhh",
     "xxxxxhhB",
     "xxxxhhBB",
     "xxxhhBBB",
     "hhhhBBBb",
     ".hBBBbb.")))

icon("traits_perso_3", "trait.sadistic", "Moqueur", "😏", *tile("personality", *outlined(
     "...Eb...",
     ".EEEbbb.",
     "EEEEbbbb",
     "E.EEbb.b",
     "y.EEbb.y",
     ".yyyyyy.",
     ".aaaaaa.")))

icon("traits_perso_3", "trait.eccentric", "Excentrique", "🎩", *tile("personality", *outlined(
     ".nVVVVz.",
     ".nVVVVz.",
     ".nVVVVz.",
     ".lLlYLl.",
     ".nVVVVz.",
     "nVVVVVVz",
     ".zzzzzz.")))

# Coping

icon("traits_coping", "trait.comfort_eater", "Mange ses émotions", "🍪", *tile("coping", *outlined(
     "..JJJ...",
     ".JJuJj..",
     "JJJJJuj.",
     "JuJJJJjj",
     "JJJJujjj",
     "JJujjjuj",
     ".jjjjuj.",
     "..jjjj..")))

icon("traits_coping", "trait.inappetetic", "Sans appétit", "🥄", *tile("coping", *outlined(
     "......s.",
     ".....s..",
     "....s...",
     "wkkkkkks",
     "swwwwwsG",
     ".sssssG.",
     "..GGGG..")))

icon("traits_coping", "trait.contrite", "Repentant", "🙏", *tile("coping", *outlined(
     "...y....",
     "..yfy...",
     "..fEf...",
     "...k....",
     "..wwss..",
     "..wwss..",
     "..wsss..",
     ".GGGGGG.")))

icon("traits_coping", "trait.improvident", "Imprévoyant", "💸", *tile("coping", *outlined(
     "w......s",
     "ww.yy.ss",
     ".wywyas.",
     "..yyya..",
     "..aaoo..",
     "...oo...")))

icon("traits_coping", "trait.reclusive", "Reclus", "🐚", *tile("coping", *outlined(
     "..UUUU..",
     ".UjUUjU.",
     ".UjwwjU.",
     ".UjwsjU.",
     ".UjUUjy.",
     ".UjUUjU.",
     ".UjUUjU.",
     "GGGGGGGG")))

icon("traits_coping", "trait.irritable", "Irritable", "🌩️", *tile("coping", *outlined(
     "..GGG...",
     ".GsGGGG.",
     "GGGGGGGg",
     "GGgggggg",
     ".gggggg.",
     "....y...",
     "...yy...",
     "...y....")))

icon("traits_coping", "trait.profligate", "Dépensier", "🛍️", *tile("coping", *outlined(
     "..wwww..",
     "..w..w..",
     "iiiiiiiC",
     "iIiiiiiC",
     "iiiiiiCC",
     "iiiiiiCC",
     "iiiiiCCC",
     "CCCCCCCC")))

icon("traits_coping", "trait.confider", "Confident", "🫂", *tile("coping", *outlined(
     ".wwwwww.",
     "wwiwiwws",
     "wwiiiwss",
     "wwwiwsss",
     ".wwssss.",
     ".ws.....",
     ".s......")))

icon("traits_coping", "trait.journaller", "Écrit son journal", "📔", *tile("coping", *outlined(
     ".LLLLLLl",
     "sLlLLLLl",
     ".LwwwwLl",
     "sLLLLLLl",
     ".LLLLLLl",
     "sLLLLLLl",
     ".LLLLLLl",
     ".lllllll")))

icon("traits_coping", "trait.athletic", "Sportif", "🏃", *tile("coping", *outlined(
     "EE......",
     "EEE.....",
     "EwEE....",
     "EEwEEE..",
     "EEEwEEEE",
     "EEEEEEEc",
     "wwwwwwww",
     ".GGGGGG.")))
