"""Every item icon as a 16×16 grid in palette characters (palette.py), keyed by its icon key: the
item key (col.galet, cos.accessory.noeud) or set.<set key>. GROUPS orders them into the batches
the owner judges, one sheet each. name and unicode are only for the sheet: the bot's catalog is
the truth for both."""
from dataclasses import dataclass


@dataclass(frozen=True)
class Icon:
    name: str
    unicode: str
    grid: tuple


ICONS: dict = {}
GROUPS: dict = {}


def icon(group, key, name, unicode, *rows):
    assert key not in ICONS, f"{key} drawn twice"
    ICONS[key] = Icon(name, unicode, tuple(rows))
    GROUPS.setdefault(group, []).append(key)


# ---- Cailloux ---------------------------------------------------------------------------------

icon("cailloux", "col.galet", "Galet", "🪨",
     "................",
     "................",
     ".....######.....",
     "...##swsssG##...",
     "..#sswssGGGGG#..",
     ".#sswsGGGGGGGg#.",
     ".#ssGGGGgGGGgg#.",
     ".#sGGgGGGGGGgg#.",
     ".#GGGGGGGgGggg#.",
     ".#GGGGGGGGgggk#.",
     ".#GgGGGGGggggk#.",
     "..#GGGGggggkk#..",
     "...##gggggk##...",
     ".....######.....",
     "................",
     "................")

icon("cailloux", "col.caillou_plat", "Caillou plat", "🥏",
     "................",
     "................",
     "................",
     "....########....",
     "..##sswwsssh##..",
     ".#sswssshhhhGG#.",
     ".#shsshhhhGGGG#.",
     ".#hhhhhGGGGGGg#.",
     ".#GhhGGGGGGGgg#.",
     ".#gGGGGGGGGggT#.",
     "..#ggggggggTT#..",
     "...##TTTTTT##...",
     ".....######.....",
     "................",
     "................",
     "................")

icon("cailloux", "col.silex", "Silex", "🔪",
     "................",
     "................",
     "......#####.....",
     "....##wwssJ#....",
     "...#wwsJsJkk#...",
     "..#wsJsJkTTgk#..",
     "..#sJsJkTGTTk#..",
     ".#wsJsJkThTTTk#.",
     ".#sJsJkTGhTGTk#.",
     ".#JsJkTTGTTGTk#.",
     ".#sJJkTGTTGTkk#.",
     "..#JjkTTGTTkk#..",
     "..#jjjkTTTkkk#..",
     "...##jjkkkk##...",
     ".....######.....",
     "................")

icon("cailloux", "col.quartz", "Quartz", "🔷",
     "................",
     ".....##.........",
     "....#ww#........",
     "...#wwsh#.......",
     "..#wwwshh#......",
     "..#wwwshD####...",
     "..#wwwshD#wsh#..",
     "..#wswshD#wsh#..",
     "..#wwwshD#wsD#..",
     "..#wwsshD#whD#..",
     "..#wwwshD#shD#..",
     "..#swwshD#shD#..",
     "..#sswsDD#sDD#..",
     "..#ssssDD#sDd#..",
     "...##########...",
     "................")

icon("cailloux", "col.agate", "Agate", "🟠",
     "................",
     "................",
     ".....######.....",
     "...##awoooa##...",
     "..#aJwaaaaJJa#..",
     ".#JJJJJJJJJaoR#.",
     ".#aaaaaaaaaoRo#.",
     ".#oooooooooRoa#.",
     ".#oRRRRRoRRoaJ#.",
     ".#RooooRRooaJo#.",
     ".#oaaaaoooaJoo#.",
     "..#JJJaaaaJoo#..",
     "...##aJJJJo##...",
     ".....######.....",
     "................",
     "................")

icon("cailloux", "col.amethyste", "Améthyste", "🟣",
     "................",
     ".......##.......",
     "......#IC#......",
     ".....#ICnV#.....",
     ".....#CCnV####..",
     "..##.#CCnV#InV#.",
     ".#IC##CCnV#CnV#.",
     ".#Cn##CCnV#CnV#.",
     ".#Cn##CCnV#CnV#.",
     ".#CV##CnnV#nnV#.",
     ".#nV##nnVV#nVz#.",
     ".#GGssGGGGGGGg#.",
     ".#sGGGGGGgggkk#.",
     "..############..",
     "................",
     "................")

icon("cailloux", "col.opale", "Opale", "🌈",
     "................",
     "................",
     "................",
     ".....######.....",
     "...##BxxBbb##...",
     "..#wBxlxBbPbP#..",
     ".#BBxllBiibPPP#.",
     ".#bBxBiiIibbPP#.",
     ".#bbBxxibBllPp#.",
     ".#PbbBxxBlllPp#.",
     "..#PbbBBbllPp#..",
     "...##PPbbPp##...",
     ".....######.....",
     "................",
     "................",
     "................")

icon("cailloux", "col.meteorite", "Météorite", "☄️",
     "................",
     "............##..",
     "..........##w#..",
     "........##aAy#..",
     "......##EaAyy#..",
     "...####EEaAy#...",
     "..#gGgkkEEa#....",
     ".#gGwGgkgkE#....",
     ".#gGGgTgkkk#....",
     ".#GgTgggkTk#....",
     ".#gggkggkkk#....",
     ".#ggkkgTkkk#....",
     "..#gkkTkkk#.....",
     "...#######......",
     "................",
     "................")


def recolour(key, mapping, glints=()):
    """Another icon's grid with its colours swapped (mapping: char → char) and a few pixels set:
    glints is (x, y, char)."""
    rows = [list(r) for r in ICONS[key].grid]
    rows = [[mapping.get(c, c) for c in r] for r in rows]
    for x, y, c in glints:
        rows[y][x] = c
    return ["".join(r) for r in rows]


# ---- Nature -----------------------------------------------------------------------------------

icon("nature", "col.feuille_chene", "Feuille de chêne", "🍂",
     "................",
     ".......##.......",
     "......#AA#......",
     ".....#AAaa#.....",
     "....#AAaRao#....",
     "...#AAaaRaoo#...",
     "....#AaaRao#....",
     "...#AAaoRoao#...",
     "..#AAaaaRaaoo#..",
     "...#AaaoRoao#...",
     "..#AAaaaRaaoo#..",
     "...#aaaaRaoo#...",
     "....#aaaRoo#....",
     ".....###R##.....",
     "........#.......",
     "................")

icon("nature", "col.gland", "Gland", "🌰",
     "................",
     "........#.......",
     ".......#j#......",
     "....####j####...",
     "...#JjJjUjUu#...",
     "..#JjUjUjUjUu#..",
     "..#jUjUjUjUuu#..",
     "..##uuuuuuuu##..",
     "...#aAoooooR#...",
     "...#AaoooooR#...",
     "...#aoooooRR#...",
     "....#oooRRR#....",
     ".....#oRRR#.....",
     "......#RR#......",
     ".......##.......",
     "................")

icon("nature", "col.plume", "Plume", "🪶",
     "................",
     "..........###...",
     ".........#wws#..",
     "........#wwsGs#.",
     ".......#wwsGss#.",
     "......#wwsGsss#.",
     ".....#wwsGssG#..",
     "....#wwsGssG#...",
     "...#wssGssG#....",
     "...#ssGsGG#.....",
     "...#sGsGG#......",
     "..#jG####.......",
     ".#j##...........",
     "..#.............",
     "................",
     "................")

icon("nature", "col.trefle", "Trèfle", "☘️",
     "................",
     "......#####.....",
     ".....#llLLL#....",
     ".....#lLLLL#....",
     ".....#LLLLt#....",
     "..####LLtt####..",
     ".#llLL#Lt#lLLL#.",
     ".#lLLLt##LLLLt#.",
     ".#LLLLtt#LLLtt#.",
     "..#LLtt##Ltt##..",
     "...#####L####...",
     ".......#L#......",
     ".......#L#......",
     "........#L#.....",
     ".........#......",
     "................")

icon("nature", "col.pomme_pin", "Pomme de pin", "🌲",
     "................",
     "......####......",
     ".....#uUUU#.....",
     "....#uJuUuj#....",
     "...#ujjUuUuu#...",
     "...#Jujujuuu#...",
     "..#jjjuUUUuuu#..",
     "..#ujuJuUujuu#..",
     "...#ujjUuUuu#...",
     "...#Jujujuuu#...",
     "....#juUUUu#....",
     ".....#JuUu#.....",
     ".....#jUuU#.....",
     "......#uj#......",
     ".......##.......",
     "................")

icon("nature", "col.coquille_escargot", "Coquille d'escargot", "🐌",
     "................",
     ".....######.....",
     "....#AAAAaa#....",
     "...#AwRRRRRa#...",
     "..#AwRAaaaaRo#..",
     ".#AARAaaRaaoRo#.",
     ".#AARaRRaRooRo#.",
     ".#AARaRaaoRooR#.",
     ".#AaRaRRRoRooR#.",
     ".#aaRaaoooRooR#.",
     ".#RaaRoooRooRo#.",
     "..#aaoRRRoooR#..",
     "...#oooooooR#...",
     "....#RRRRRR#....",
     ".....######.....",
     "................")


icon("nature", "col.trefle_quatre", "Trèfle à quatre feuilles", "🍀",
     "................",
     "......####......",
     ".....#lwlL#.....",
     ".....#llLL#.....",
     "..####lLLt####..",
     ".#lYlL#lL#lYlL#.",
     ".#llLLtLLtlLLt#.",
     ".#LLLttLtLLLtt#.",
     "..#Ltt#tt#Ltt#..",
     "...###lLLt###...",
     ".....#lLLt#.....",
     ".....#LLtt#.....",
     "......####......",
     "................",
     "................",
     "................")

icon("nature", "col.plume_doree", "Plume dorée", "✨",
     *recolour("col.plume", {"w": "y", "s": "a", "G": "o", "j": "o"},
               glints=[(10, 2, "w"), (9, 4, "w"), (6, 7, "w"), (4, 9, "w")]))


# ---- Trésors ----------------------------------------------------------------------------------

icon("tresors", "col.bouton", "Bouton", "🔘",
     "................",
     ".....######.....",
     "...##EEEEEE##...",
     "..#EIeeeEEEcc#..",
     "..#IeeeEEEEEc#..",
     ".#EeeeEEEEEEEc#.",
     ".#EeeE#EE#EEEc#.",
     ".#EeEEEEEEEEcc#.",
     ".#EEEEEEEEEccc#.",
     ".#EEEE#EE#cccc#.",
     ".#EEEEEEEccccc#.",
     "..#cEEEEccccc#..",
     "..#ccEEcccccc#..",
     "...##cccccc##...",
     ".....######.....",
     "................")

icon("tresors", "col.bille", "Bille", "🔮",
     "................",
     ".....######.....",
     "....#BBBBBB#....",
     "...#BBBBBBbb#...",
     "..#BwwBBBbbbb#..",
     ".#BBwxBBbbbbbb#.",
     ".#BxxxxbbbbbbP#.",
     ".#BBBBbxbbbbPP#.",
     ".#BBBbbbxbbPPP#.",
     ".#BBbbbbbhhhhP#.",
     ".#BbbbbbbPhhPP#.",
     "..#bbbbbPPPPP#..",
     "...#bbbPPPPP#...",
     "....#bPPPPP#....",
     ".....######.....",
     "................")

icon("tresors", "col.cle_rouillee", "Clé rouillée", "🗝️",
     "................",
     "...####.........",
     "..#AAaa#........",
     ".#AAaaaa#.......",
     ".#Aa##ao#.......",
     ".#aa##oo#.......",
     ".#aaaooo#.......",
     "..#aooRo#.......",
     "...####oa#......",
     ".......#Ra#.....",
     "........#oo#....",
     "........#oRa#...",
     ".......#R##oa#..",
     "........##RoRo#.",
     "..........####..",
     "................")

icon("tresors", "col.piece_ancienne", "Pièce ancienne", "🪙",
     "................",
     ".....######.....",
     "...##aaaaaa##...",
     "..#awyyyyaaaa#..",
     "..#wyyyyaaaaa#..",
     ".#ayyAAAAAoaao#.",
     ".#ayyAaaaaoaao#.",
     ".#ayyAa##aoaoo#.",
     ".#ayaAa##aoooo#.",
     ".#aaaAaaaaoooo#.",
     ".#aaaooooooooo#.",
     "..#aaaaaooooo#..",
     "..#aaaaoooooo#..",
     "...##oooooo##...",
     ".....######.....",
     "................")

icon("tresors", "col.bague", "Bague", "💍",
     "................",
     ".......##.......",
     "......#Ii#......",
     ".....#Iwii#.....",
     ".....#iiCC#.....",
     ".....##CC##.....",
     "....#yyyyaa#....",
     "...#yyyyaaaa#...",
     "..#yyyyaaaaaa#..",
     ".#yyy######aoo#.",
     ".#yyy#....#ooo#.",
     "..#ya######oo#..",
     "..#aaaaaaoooo#..",
     "...##aaaooo##...",
     ".....######.....",
     "................")

icon("tresors", "col.boussole", "Boussole", "🧭",
     "................",
     ".....######.....",
     "....#aaaaaa#....",
     "...#aaawwaoo#...",
     "..#aawwEEwwoo#..",
     ".#aawwwEEwwwoo#.",
     ".#aawwwEEwwsoR#.",
     ".#awwwwE#wsssR#.",
     ".#awwww#GssssR#.",
     ".#aawwwGGsssRR#.",
     ".#aowwwGGsssRR#.",
     "..#oowsGGssRR#..",
     "...#ooossRRR#...",
     "....#oRRRRR#....",
     ".....######.....",
     "................")

icon("tresors", "col.carte_tresor", "Carte au trésor", "🗺️",
     "................",
     "................",
     "..###########...",
     ".#jJJJJJJJJJj#..",
     ".#jwJJoJJJJJj#..",
     ".#jJJJJoJJJJj#..",
     ".#jJJJJJJoJJj#..",
     ".#jJJoJJJJJJj#..",
     ".#jJoJJJJEJEj#..",
     ".#jJJoJJJJEJj#..",
     ".#jJJJJoJEJEj#..",
     ".#jJJJJJJJJJj#..",
     "..###########...",
     "................",
     "................",
     "................")

icon("tresors", "col.couronne", "Couronne", "👑",
     "................",
     "................",
     "..#....#....#...",
     ".#w#..#w#..#y#..",
     ".#y#.#yyy#.#a#..",
     ".#ya##yEya##ao#.",
     ".#yaayyyyaaaao#.",
     ".#yyayayyaaaao#.",
     ".#yEyyaEyaaEao#.",
     ".#yyyyaayaaaao#.",
     ".#aaaaaaaaaooo#.",
     ".#oooooooooooR#.",
     "..############..",
     "................",
     "................",
     "................")


# ---- Saisons ----------------------------------------------------------------------------------

icon("saisons", "col.primevere", "Primevère", "🌼",
     "................",
     "......####......",
     ".....#wwyy#.....",
     "....##wyyy##....",
     "...#wayyyyay#...",
     "..#wwyayyayyy#..",
     "..#wyyyaayyyA#..",
     "..#yyyy##yyAA#..",
     "...#aayooyaa#...",
     "...#yyyyyAAA#...",
     "...#yyyyAAAA#...",
     "...#yyyAAAAA#...",
     "..#LLL####LLL#..",
     "..#tt#....#tt#..",
     "...##......##...",
     "................")

icon("saisons", "col.cerise", "Cerise", "🍒",
     "................",
     ".........###....",
     "........#llL#...",
     ".......#L#LLt#..",
     "......#L#L###...",
     ".....#L##L#.....",
     "....#L#..#L#....",
     "...##L#..#L##...",
     "..#EEEE##EEEE#..",
     ".#EIIEEEEIIEEE#.",
     ".#EIIEEcEIIEEc#.",
     ".#EEEEccEEEEcc#.",
     ".#EEEcccEEEccc#.",
     "..#Eccc##Eccc#..",
     "...####..####...",
     "................")

icon("saisons", "col.coquelicot", "Coquelicot", "🌺",
     "................",
     "......####......",
     "....##eeeE##....",
     "...#eeppppEE#...",
     "..#eeecppcEEE#..",
     ".#eeeeEEEEEEcc#.",
     ".#eeeEEEEEEccc#.",
     ".#eeEEEEEEcccc#.",
     "..#EEEEEEcccc#..",
     "...#EEEEcccc#...",
     "....#EEcccc#....",
     ".....###L#l#....",
     ".......#LLl#....",
     ".......#L##.....",
     "........#.......",
     "................")

icon("saisons", "col.coquillage", "Coquillage", "🐚",
     "................",
     "................",
     "....########....",
     "..##IIwwIIII##..",
     ".#wwIIwwIiIIii#.",
     ".#wwIIwwiiIIii#.",
     ".#IwwIIIiIIiiI#.",
     ".#IIwIiIiIIiII#.",
     ".#IIwIiIiIiiII#.",
     ".#wwiIiIiIiIii#.",
     "..#IIiIIiiIii#..",
     "...##IiiIIi##...",
     ".....#iiii#.....",
     "....#ii##ii#....",
     ".....##..##.....",
     "................")

icon("saisons", "col.chataigne", "Châtaigne", "🌰",
     "................",
     ".......#........",
     ".....##R###.....",
     "....#AAAooo#....",
     "....#wAoooo#....",
     "...#AAoooooR#...",
     "...#AoooooRR#...",
     "..##oooooRRR##..",
     ".#l#ooooRRRR#l#.",
     ".#lllJJJJJJttt#.",
     "..#lLLJJJJttt#..",
     ".#lLLLLLLttttl#.",
     "..##LLLLtttt##..",
     "...#lLLttttl#...",
     "....########....",
     "................")

icon("saisons", "col.citrouille", "Citrouille", "🎃",
     "................",
     ".......###......",
     "......#tLl#.....",
     "......#tL#......",
     "....##AAAa##....",
     "...#oAAAaaao#...",
     "..#AoAAoaaaoa#..",
     ".#AAoAaoaaaoao#.",
     ".#AAoaaoaaaooo#.",
     ".#AAoaaoaaaooo#.",
     ".#Aaoaaoaaoooo#.",
     ".#aaoaaoaooooo#.",
     "..#aoaaoooooo#..",
     "...##aaoooo##...",
     ".....######.....",
     "................")

icon("saisons", "col.flocon", "Flocon", "❄️",
     "................",
     ".......#........",
     "......#h#.......",
     ".....#xwx#......",
     "..#.#x#w#x#.#...",
     ".#h####w####h#..",
     "..#ww##w##ww#...",
     "...##wwxww##....",
     "..#ww##w##ww#...",
     ".#h####w####h#..",
     "..#.#x#w#x#.#...",
     ".....#xwx#......",
     "......#h#.......",
     ".......#........",
     "................",
     "................")

icon("saisons", "col.cristal_givre", "Cristal de givre", "💎",
     "................",
     ".......##.......",
     "......#wx#......",
     ".....#wxBb#.....",
     "..##.#wxBb###...",
     ".#wx##wxBb#xB#..",
     ".#xB##xxBb#xb#..",
     ".#xB##xxBb#Bb#..",
     ".#xb##xBBb#Bb#..",
     ".#Bb##xBbb#Bb#..",
     ".#Bb##BBbb#bd#..",
     ".#bd##Bbbd#bd#..",
     ".#wswswswsws#...",
     "..###########...",
     "................",
     "................")


# ---- Insectes ---------------------------------------------------------------------------------

icon("insectes", "col.fourmi", "Fourmi", "🐜",
     "................",
     "................",
     "................",
     "..........#..#..",
     "...........##...",
     "...........##...",
     "...###..#.#jU#..",
     "..#jUU##U#jUwu#.",
     ".#jUUUuUUuUUuu#.",
     ".#UUUuu#u##uu#..",
     ".#UUuuu###.##...",
     "..#####.#.#.....",
     ".....#..#..#....",
     "................",
     "................",
     "................")

icon("insectes", "col.mouche", "Mouche", "🪰",
     "................",
     "................",
     ".....##..##.....",
     "....#EE##EE#....",
     "...#EIEkkIEc#...",
     "...#EEckkEcc#...",
     "...####Gg####...",
     "...###Gggg###...",
     "..#sshgggksss#..",
     "..#shhgkkksss#..",
     "..#hhhgggghss#..",
     "..#hhhkkkkhhs#..",
     "..#hhhgggghhh#..",
     "...####kk####...",
     ".......##.......",
     "................")

icon("insectes", "col.moustique", "Moustique", "🦟",
     "................",
     "................",
     "................",
     ".........###....",
     "........#whh##..",
     ".......#wwhhhh#.",
     "...#####wwhhh#..",
     "..#gEgGG#####...",
     "..##gGGGgsg###..",
     ".#..#####sgsgs#.",
     ".....#.#.###gs#.",
     "....#..#..#.##..",
     "...#...#...#....",
     "...#...#....#...",
     "................",
     "................")

icon("insectes", "col.chenille", "Chenille", "🐛",
     "................",
     "................",
     "................",
     "................",
     "......#####.....",
     ".....#llllL#....",
     "....#lYLlYLL#...",
     "...#llLLLLllL#..",
     "..#lYLLt#LYLL#..",
     "..#LLLt#.#LLt#..",
     ".#lYLt#..#llLL#.",
     ".#lLLt#..#lL#L#.",
     ".#LLtt#..#LCLL#.",
     "..####....#LL#..",
     "...........##...",
     "................")

icon("insectes", "col.coccinelle", "Coccinelle", "🐞",
     "................",
     "................",
     "......####......",
     ".....#wkkw#.....",
     "....##kkkk##....",
     "...#IIk#kkEE#...",
     "..#IIEE#EEEEE#..",
     "..#I##E#EE##c#..",
     "..#EEEE#EEEcc#..",
     "..#EEEE#EEccc#..",
     "..#E#EE#Ec##c#..",
     "..#EEEE#ccccc#..",
     "...#E#E#c#cc#...",
     "....#Ec#ccc#....",
     ".....######.....",
     "................")

icon("insectes", "col.grillon", "Grillon", "🦗",
     "................",
     "................",
     "..........#.....",
     "...........#....",
     "............#...",
     "...####......##.",
     "..#UUUU#...###..",
     "...#uuuu###LL#..",
     "..#LLLttttuL#t#.",
     "..#LLttttuuttu#.",
     "..#Lttttuuuuu#..",
     "...##ttuu####...",
     "..#.#####.#.....",
     "...#....#..#....",
     "................",
     "................")

icon("insectes", "col.abeille", "Abeille", "🐝",
     "................",
     "................",
     "......###.#.....",
     ".....#www#w#....",
     ".....#wwwwww#...",
     ".....#ssshhh#...",
     ".....#ssshhh#...",
     "..####y#yy#a#...",
     ".#kwkyy#ya#aa#..",
     ".#kk##y#aa#ao#..",
     ".#k###y#aa#oo##.",
     "..###ya#aa#oo#..",
     "...###a#ao#o#...",
     "......######....",
     "................",
     "................")

icon("insectes", "col.morpho_bleu", "Morpho bleu", "🦋",
     "................",
     "....##....##....",
     "..##d##..##d##..",
     ".#ddxBB##xxxdd#.",
     ".#xwBBBkgxxBwB#.",
     ".#xBBBbkgxBBBb#.",
     ".#BBBbbkgBBBbb#.",
     ".#dBbbbkgBBbbd#.",
     "..#ddb#kg#bdd#..",
     "...##dBkgxd##...",
     "...#xBBkgxBB#...",
     "...#wBBkgBBw#...",
     "...#BBbkgBbb#...",
     "....#db##bd#....",
     ".....##..##.....",
     "................")
