// <auto-generated>
// Written by tools/mushroom-emojis/upload.py — do not edit by hand; run the script again.
// </auto-generated>
namespace ProjectSYNCS.Helpers;

// The Champignons collection's pictures: the bot's *application* emojis — owned by its
// application rather than by a server, so it can show them anywhere it is — uploaded from
// tools/mushroom-emojis/sprites. Until that script has run, every one falls back to 🍄 and
// MushroomsUploaded is false. Only ever used in text (embeds, messages), never as a reaction.
public static partial class Emotes
{
    public const bool MushroomsUploaded = false;

    /// <summary>`:shroom_agaric_bohus:`</summary>
    public const string ShroomAgaricBohusId = "";
    public const string ShroomAgaricBohus = "🍄";

    /// <summary>`:shroom_armillaire:`</summary>
    public const string ShroomArmillaireId = "";
    public const string ShroomArmillaire = "🍄";

    /// <summary>`:shroom_bolet_trembles:`</summary>
    public const string ShroomBoletTremblesId = "";
    public const string ShroomBoletTrembles = "🍄";

    /// <summary>`:shroom_cepe_bordeaux:`</summary>
    public const string ShroomCepeBordeauxId = "";
    public const string ShroomCepeBordeaux = "🍄";

    /// <summary>`:shroom_champignon_homard:`</summary>
    public const string ShroomChampignonHomardId = "";
    public const string ShroomChampignonHomard = "🍄";

    /// <summary>`:shroom_champignon_paille:`</summary>
    public const string ShroomChampignonPailleId = "";
    public const string ShroomChampignonPaille = "🍄";

    /// <summary>`:shroom_champignon_paris:`</summary>
    public const string ShroomChampignonParisId = "";
    public const string ShroomChampignonParis = "🍄";

    /// <summary>`:shroom_clitocybe:`</summary>
    public const string ShroomClitocybeId = "";
    public const string ShroomClitocybe = "🍄";

    /// <summary>`:shroom_coprin_chevelu:`</summary>
    public const string ShroomCoprinCheveluId = "";
    public const string ShroomCoprinChevelu = "🍄";

    /// <summary>`:shroom_coprin_encre:`</summary>
    public const string ShroomCoprinEncreId = "";
    public const string ShroomCoprinEncre = "🍄";

    /// <summary>`:shroom_coulemelle:`</summary>
    public const string ShroomCoulemelleId = "";
    public const string ShroomCoulemelle = "🍄";

    /// <summary>`:shroom_enoki:`</summary>
    public const string ShroomEnokiId = "";
    public const string ShroomEnoki = "🍄";

    /// <summary>`:shroom_girolle:`</summary>
    public const string ShroomGirolleId = "";
    public const string ShroomGirolle = "🍄";

    /// <summary>`:shroom_gomphide:`</summary>
    public const string ShroomGomphideId = "";
    public const string ShroomGomphide = "🍄";

    /// <summary>`:shroom_lactaire_delicieux:`</summary>
    public const string ShroomLactaireDelicieuxId = "";
    public const string ShroomLactaireDelicieux = "🍄";

    /// <summary>`:shroom_lactaire_indigo:`</summary>
    public const string ShroomLactaireIndigoId = "";
    public const string ShroomLactaireIndigo = "🍄";

    /// <summary>`:shroom_lentin_chene:`</summary>
    public const string ShroomLentinCheneId = "";
    public const string ShroomLentinChene = "🍄";

    /// <summary>`:shroom_maitake:`</summary>
    public const string ShroomMaitakeId = "";
    public const string ShroomMaitake = "🍄";

    /// <summary>`:shroom_matsutake:`</summary>
    public const string ShroomMatsutakeId = "";
    public const string ShroomMatsutake = "🍄";

    /// <summary>`:shroom_morille_conique:`</summary>
    public const string ShroomMorilleConiqueId = "";
    public const string ShroomMorilleConique = "🍄";

    /// <summary>`:shroom_nonnette_voilee:`</summary>
    public const string ShroomNonnetteVoileeId = "";
    public const string ShroomNonnetteVoilee = "🍄";

    /// <summary>`:shroom_oronge:`</summary>
    public const string ShroomOrongeId = "";
    public const string ShroomOronge = "🍄";

    /// <summary>`:shroom_petit_gris:`</summary>
    public const string ShroomPetitGrisId = "";
    public const string ShroomPetitGris = "🍄";

    /// <summary>`:shroom_pholiote_doree:`</summary>
    public const string ShroomPholioteDoreeId = "";
    public const string ShroomPholioteDoree = "🍄";

    /// <summary>`:shroom_polypore_soufre:`</summary>
    public const string ShroomPolyporeSoufreId = "";
    public const string ShroomPolyporeSoufre = "🍄";

    /// <summary>`:shroom_russule_comestible:`</summary>
    public const string ShroomRussuleComestibleId = "";
    public const string ShroomRussuleComestible = "🍄";

    /// <summary>`:shroom_russule_doree:`</summary>
    public const string ShroomRussuleDoreeId = "";
    public const string ShroomRussuleDoree = "🍄";

    /// <summary>`:shroom_shimeji:`</summary>
    public const string ShroomShimejiId = "";
    public const string ShroomShimeji = "🍄";

    /// <summary>`:shroom_trompette_mort:`</summary>
    public const string ShroomTrompetteMortId = "";
    public const string ShroomTrompetteMort = "🍄";

    /// <summary>`:shroom_truffe_noire:`</summary>
    public const string ShroomTruffeNoireId = "";
    public const string ShroomTruffeNoire = "🍄";
}
