using System.Globalization;
using System.Text;
using System.Text.RegularExpressions;
using ProjectSYNCS.Models;

namespace ProjectSYNCS.Helpers;

public sealed record PassionInfo(PlynlingPassion Passion, string Emoji, string Label, string[] Keywords,
    string[] Openers, string[] SharedLines, string[] Activities);

/// <summary>
/// One passion a Plynling has: a catalog one (rich, hand-written lines) or a custom text taught by
/// its owner (generic templates). Exactly one of the two is set.
/// </summary>
public sealed record Passion(PlynlingPassion? Catalog, string? Custom)
{
    // Two passions are the same when both are the same catalog one, or both custom with equal
    // normalised text ("Les trains !" = "les trains").
    public string Key => Catalog is { } c ? "cat:" + c : "txt:" + PlynlingPassions.Normalize(Custom ?? "");
    public bool SameAs(Passion other) => Key == other.Key;

    /// <summary>For {P} and SYNCS's lines: « la cuisine », or the typed text in « guillemets ».</summary>
    public string Render() => Catalog is { } c ? PlynlingPassions.Info(c).Label : $"« {PlynlingCardUi.SafeName(Custom ?? "")} »";

    /// <summary>For the card: with the catalog emoji.</summary>
    public string Display() => Catalog is { } c ? $"{PlynlingPassions.Info(c).Emoji} {PlynlingPassions.Info(c).Label}" : Render();
}

/// <summary>
/// The passions. Pure: no database, no clock. An innate passion is one of the catalog below; a taught
/// one is free text, upgraded to a catalog passion when <see cref="Resolve"/> recognises it.
/// Lines are story templates (see <see cref="PlynlingVisitStory"/>): {S}/{L} speaker and listener,
/// {s:m|f}/{l:m|f} their agreements, {Ils}/{ils}, {p:m|f}. An opener is narration, then the speaker's
/// line, separated by one \n. Catalog lines are written for their passion and do not use {P}.
/// </summary>
public static class PlynlingPassions
{
    public static readonly TimeSpan TeachCooldown = TimeSpan.FromHours(24);

    // How often a shared passion, when there is one, is what they talk about.
    public const double SharedTopicChance = 0.6;

    public static readonly IReadOnlyList<PassionInfo> All = new PassionInfo[]
    {
        new(PlynlingPassion.Cooking, "🍳", "la cuisine",
            new[] { "cuisine", "cuisiner", "recette", "recettes", "patisserie", "gateau", "gateaux", "crepe", "crepes", "cuisson", "chef" },
            new[] { "{S} sort un petit carnet taché de farine.\nTu savais qu'une crêpe se retourne mieux d'un coup de poignet qu'à la spatule ?",
                "{S} renifle l'air avec beaucoup de sérieux.\nÇa sent la noisette grillée quelque part. Je le sens, j'ai un don pour ça.",
                "{S} sort une petite cuillère de sa poche. Personne ne sait pourquoi {s:il|elle} en a une.\nJ'ai inventé une soupe à la fraise. Elle n'est pas bonne, mais elle est courageuse.",
                "{S} a de la farine sur le bout du nez.\nJ'ai raté trois gâteaux ce matin. Le quatrième est presque un gâteau.",
                "{S} récite une recette les yeux fermés, comme un poème.\nUne pincée de sel, deux pincées de patience, et beaucoup de beurre. Surtout le beurre.",
                "{S} montre un petit carnet plein de ratures.\nLe secret d'une bonne tarte, c'est de ne jamais la regarder cuire. Elle devient timide.",
                "{S} arrive avec une casserole minuscule, très {s:fier|fière}.\nC'est ma casserole de voyage. On ne sait jamais quand une crêpe peut devenir nécessaire.",
                "{S} goûte l'air du bout de la langue.\nIl va pleuvoir. Je le sens au goût. C'est un talent de {s:cuisinier|cuisinière}.",
                "{S} sort un bocal rempli de miettes soigneusement classées.\nCe sont les miettes de tous les gâteaux que j'ai ratés. Je les garde. Elles ont une histoire.",
                "{S} a une tache de chocolat sur la joue et fait comme si de rien n'était.\nNon, je n'ai rien goûté en route. Pourquoi tu demandes ?",
                "{S} tient une cuillère en bois comme une baguette magique.\nAvec ça, je transforme n'importe quoi en soupe. Même les mauvaises journées.",
                "{S} a les joues pleines et essaie de parler quand même.\nMmh… pardon. Je goûtais. C'est important de goûter. C'est même la moitié du métier.",
                "{S} déplie une recette si longue qu'elle traîne par terre.\nC'est la recette du gâteau parfait. Il faut trois jours et beaucoup de courage.",
                "{S} renifle ses doigts, l'air satisfait.\nCannelle. Je sens la cannelle depuis ce matin. Je crois que c'est devenu mon odeur.",
                "{S} montre une crêpe pliée en quatre dans une feuille.\nJe t'en ai gardé une. Elle a un peu voyagé, mais elle est pleine de bonnes intentions.",
                "{S} parle en comptant sur ses doigts.\nIl y a quatre saveurs : sucré, salé, acide, amer. Et une cinquième : « encore ».",
                "{S} soupire, l'air très sérieux.\nJ'ai laissé brûler mes biscuits. Je les ai appelés « biscuits croustillants ». Personne n'a rien vu.",
                "{S} porte un petit tablier noué de travers.\nOn ne cuisine pas sans tablier. C'est la règle. Même pour une tartine.",
                "{S} lève un doigt plein de confiture.\nFramboise. Faite maison. Enfin, faite par moi, pas vraiment dans une maison.",
                "{S} agite un petit pot d'épices comme un grelot.\nUne pincée de ça, et n'importe quel plat devient une aventure. Parfois une aventure dangereuse." },
            new[] { "{Ils} se mettent à échanger des recettes à toute vitesse, sans même finir leurs phrases.",
                "{S} et {L} se découvrent la même obsession pour la croûte des tartes. C'est le début de quelque chose.",
                "{Ils} se disputent gentiment sur la bonne quantité de sucre. La réponse, apparemment, c'est « plus ».",
                "{Ils} se promettent d'ouvrir un jour un petit restaurant. Il n'y aura qu'un plat, mais il sera parfait.",
                "{S} et {L} goûtent la même sauce imaginaire et hochent la tête exactement en même temps.",
                "{Ils} tombent d'accord sur la vérité la plus importante : le meilleur morceau du gâteau, c'est le bord.",
                "{S} et {L} se penchent sur le même petit carnet de recettes, la tête presque collée. Personne ne veut tourner la page le premier.",
                "{Ils} tombent d'accord sur un secret de famille : un peu de sel dans le sucré, un peu de sucre dans le salé.",
                "{L} corrige la recette de {S} avec beaucoup de tact. {S} corrige la correction avec beaucoup moins.",
                "{Ils} se découvrent le même dessert préféré et s'en font la promesse solennelle : un jour, {ils} le feront ensemble.",
                "{Ils} goûtent la même cuillerée imaginaire, en même temps, et disent « hmm » exactement sur la même note.",
                "Le gâteau parfait, {ils} le décrivent {p:tous|toutes} les deux avec les mêmes mots. C'est troublant. C'est délicieux." },
            new[] { "🥞 {Ils} se lancent dans des crêpes. La première est ratée, comme le veut la tradition.",
                "🍪 {Ils} font des biscuits en forme de cailloux. Ils ont aussi le goût de cailloux, mais c'est l'intention qui compte.",
                "🍲 {S} prépare une soupe ; {L} goûte à chaque étape en donnant des notes très sévères.",
                "🧁 Concours de décoration de petits gâteaux. Le jury (un moineau) mange les deux avant de voter.",
                "🥧 {Ils} préparent une tarte à quatre mains. Il manque la moitié des ingrédients. Elle est quand même délicieuse.",
                "🍓 {Ils} font de la confiture de fraises. Il en reste un pot. Il y en avait dix au début.",
                "🥐 {S} tente des croissants. Ils ressemblent à des cailloux. {L} les trouve délicieux, par politesse ou par faim.",
                "🍳 {Ils} font sauter des crêpes de plus en plus haut. La dernière n'est jamais redescendue.",
                "🧑‍🍳 {Ils} ouvrent un restaurant pour l'après-midi. Le seul client est un escargot. Il laisse un pourboire.",
                "🍵 {S} prépare une infusion de feuilles mystère. {L} la boit courageusement, puis demande ce que c'était." }),
        new(PlynlingPassion.Music, "🎵", "la musique",
            new[] { "musique", "chanson", "chansons", "chanter", "chant", "piano", "guitare", "violon", "flute", "batterie", "melodie" },
            new[] { "{S} tapote un rythme sur une pierre, l'air très concentré.\nÉcoute ça : si on tape deux fois plus vite, ça devient une autre chanson !",
                "{S} fredonne sans s'en rendre compte, puis s'arrête, un peu {s:gêné|gênée}.\nJ'ai une chanson dans la tête depuis trois jours. Je crois qu'elle a emménagé.",
                "{S} sort un petit sifflet en bois.\nJe n'en joue pas bien. Mais les oiseaux me répondent, alors je continue.",
                "{S} tapote la mesure du pied.\nTout fait de la musique, tu sais. La pluie, le vent, ton ventre quand tu as faim.",
                "{S} chante trois notes, très haut, très fièrement.\nC'est le début de ma chanson. Je n'ai pas encore trouvé la quatrième note.",
                "{S} écoute le vent, la tête penchée.\nTu entends ? Il chante faux. Moi aussi, mais moi, je le fais exprès.",
                "{S} claque des doigts en rythme, puis rate le rythme.\nC'est un rythme très moderne. Il faut une oreille exercée.",
                "{S} souffle dans un brin d'herbe. Ça fait un bruit affreux.\nC'est une trompette. Une trompette très jeune. Elle apprend.",
                "{S} fredonne une mélodie en boucle, l'air rêveur.\nJe l'ai entendue en rêve. Je l'ai notée en me réveillant. Enfin, le début.",
                "{S} tend l'oreille vers un buisson.\nÉcoute. Il y a un grillon qui chante en si bémol. Je l'accompagne depuis ce matin.",
                "{S} sort une flûte taillée dans un roseau.\nElle ne joue que trois notes. Mais ce sont trois très bonnes notes.",
                "{S} bat la mesure sur ses genoux.\nJ'ai composé une chanson pour la pluie. Elle ne l'a pas encore entendue.",
                "{S} chantonne, s'interrompt, chantonne encore.\nJe cherche la note juste. Elle se cache. Je la trouverai.",
                "{S} tient une coquille d'escargot vide contre l'oreille.\nOn entend la mer, là-dedans. Ou alors une chanson très lointaine.",
                "{S} fait semblant de diriger un orchestre invisible.\nLes violons à gauche, les grillons à droite. Silence, on commence.",
                "{S} a la voix un peu enrouée.\nJ'ai chanté toute la nuit. Pas bien, mais longtemps.",
                "{S} fredonne en marchant, et chaque pas tombe pile sur le rythme.\nTu as remarqué ? Même mes pieds sont musiciens.",
                "{S} tape deux cailloux l'un contre l'autre.\nÇa, c'est un tambour. Ça, c'est un autre tambour. Ensemble, c'est un groupe.",
                "{S} garde les yeux fermés en écoutant le vent.\nIl joue toujours la même chanson, mais jamais de la même façon.",
                "{S} sort une petite partition couverte de gribouillis.\nJe ne sais pas lire la musique. Alors j'ai inventé ma propre façon de l'écrire." },
            new[] { "{Ils} se mettent à fredonner la même chanson, pile en même temps.",
                "{Ils} inventent une harmonie sur le moment. Elle n'est pas juste, mais elle leur appartient.",
                "{S} commence un air, {L} le termine sans hésiter. {Ils} se regardent, {p:ravis|ravies}.",
                "{Ils} découvrent qu'{ils} connaissent les mêmes chansons, avec les mêmes fausses paroles.",
                "{S} donne la note, {L} la reprend. Pendant un instant, tout le monde se tait pour écouter.",
                "{Ils} se disputent le rôle de soliste. Au final, {ils} chantent {p:tous|toutes} les deux, très fort.",
                "{S} tape le rythme, {L} le prolonge sans qu'on le lui demande. Le silence qui suit a un joli goût de concert.",
                "{Ils} découvrent qu'{ils} fredonnent la même mélodie depuis ce matin, chacun de son côté.",
                "{Ils} se disputent gentiment pour savoir si le refrain monte ou descend. Personne ne cède, mais tout le monde chante.",
                "{L} donne une harmonie à la mélodie de {S}, qui en reste bouche bée, puis sourit très fort.",
                "{Ils} se mettent à battre la mesure du pied, en même temps, sans s'en rendre compte. Le sol en tremble un peu.",
                "{Ils} échangent une chanson secrète, à voix basse, comme un trésor qu'on ne partage qu'à deux." },
            new[] { "🎶 {S} apprend un petit air à {L}, qui le massacre avec beaucoup d'enthousiasme.",
                "🥁 {Ils} fabriquent une batterie avec des coquilles de noix. Le voisinage apprécie moyennement.",
                "🎤 {Ils} donnent un petit concert à une coccinelle. Elle reste jusqu'à la fin, par politesse.",
                "🎻 {L} tient le rythme, {S} chante. Puis {ils} échangent, et c'est pire. Bien pire. {Ils} adorent.",
                "🎵 {Ils} écrivent une chanson sur la journée. Le refrain rime avec « caillou » ; tout le reste aussi.",
                "🎹 {Ils} fabriquent un xylophone avec des brindilles de toutes les tailles. Il sonne faux. Magnifiquement faux.",
                "🪕 {S} gratte une ficelle tendue entre deux branches ; {L} invente les paroles au fur et à mesure.",
                "🎺 {Ils} imitent tous les instruments d'un orchestre avec la bouche. Le tuba est particulièrement réussi.",
                "🎧 {Ils} écoutent les bruits autour, les yeux fermés, et en font une chanson. Le refrain, c'est un moineau.",
                "🎙️ {Ils} donnent un concert devant trois fourmis. Les fourmis ne s'arrêtent pas, mais ralentissent." }),
        new(PlynlingPassion.Gaming, "🎮", "les jeux vidéo",
            new[] { "jeux video", "jeu video", "gaming", "console", "manette", "minecraft" },
            new[] { "{S} mime des boutons invisibles avec les pouces.\nJ'ai enfin battu le boss du troisième niveau. Sans perdre une seule vie. Enfin, presque.",
                "{S} a les yeux un peu rouges.\nJ'ai joué jusqu'à très tard. Je ne dirai pas jusqu'à quelle heure. Très tard.",
                "{S} mime une manette avec les mains.\nIl existe un niveau secret derrière la cascade. Je le sais. Je l'ai presque trouvé.",
                "{S} parle très vite, très bas.\nSi tu sautes pile au bon moment sur le troisième champignon, tu gagnes une vie. Ne le dis à personne.",
                "{S} soupire comme après une longue bataille.\nJ'ai perdu contre le boss final. Il avait triché. Je ne peux pas le prouver, mais il avait triché.",
                "{S} sort un petit carnet couvert de cartes dessinées à la main.\nJ'ai noté tous les raccourcis du jeu. Tous. Même ceux qui n'existent pas encore.",
                "{S} lève un poing victorieux avant même de dire bonjour.\nJ'ai trouvé le trésor caché du niveau quatre ! C'était une pomme. Mais une pomme légendaire.",
                "{S} marche en ligne droite, puis tourne brusquement à angle droit.\nJe m'entraîne à me déplacer comme dans mon jeu. Ça surprend les gens.",
                "{S} fronce les sourcils, très {s:sérieux|sérieuse}.\nDans le jeu, quand on perd, on recommence au dernier drapeau. J'aimerais bien avoir des drapeaux dans la vraie vie.",
                "{S} appuie frénétiquement sur un bouton invisible.\nPardon. J'étais encore en train de sauter. Ça reste dans les doigts.",
                "{S} arrive en faisant un petit bruit de pièce à chaque pas.\nPling. Pling. J'ai ramassé tout ce qui brillait sur le chemin.",
                "{S} se gratte la tête, perplexe.\nIl y a une énigme au niveau six. J'y pense même en mangeant. Surtout en mangeant.",
                "{S} parle comme un personnage de jeu.\nBienvenue, voyageur ! Tu as trouvé une nouvelle quête : m'écouter parler de jeux.",
                "{S} montre un petit dessin de personnage.\nC'est mon héros. Il a trois vies, une épée en bois et une grande peur des escargots.",
                "{S} a l'air {s:épuisé|épuisée} mais {s:fier|fière}.\nJ'ai fini le jeu à cent pour cent. Je ne sais plus quoi faire de ma vie. Je vais recommencer.",
                "{S} saute sur place, puis sur place, puis encore.\nJe m'entraîne au double saut. Pour l'instant, je n'arrive qu'au saut simple.",
                "{S} regarde le ciel en plissant les yeux.\nSi c'était un jeu, il y aurait un coffre caché sur ce nuage. Je le sens.",
                "{S} tend une feuille couverte de flèches et de croix.\nC'est la solution du labyrinthe. Je l'ai trouvée. Il m'a fallu toute la semaine.",
                "{S} baisse la voix, très {s:mystérieux|mystérieuse}.\nIl paraît qu'en appuyant sur haut, haut, bas, bas, on obtient un super pouvoir. Je teste sur tout.",
                "{S} regarde ses pouces en soupirant.\nJ'ai joué si longtemps que j'ai des ampoules. Des ampoules de {s:champion|championne}." },
            new[] { "{Ils} se lancent dans un débat passionné sur le meilleur jeu de tous les temps. Personne ne gagne.",
                "{Ils} comparent leurs meilleurs scores. {p:Chacun|Chacune} trouve celui de l'autre « pas mal, pour un débutant ».",
                "{Ils} se mettent à citer des répliques de jeu que personne d'autre ne comprend. C'est très satisfaisant.",
                "{Ils} se lancent dans un débat sans fin sur la meilleure arme de départ. Personne ne cède un pixel.",
                "{Ils} se racontent leurs pires défaites en riant. Certaines font encore un peu mal.",
                "{Ils} inventent un code secret de joueurs. Il ne sert à rien, mais il est très bien.",
                "{Ils} se racontent leur plus grande victoire dans le même jeu, et se rendent compte que c'était la même partie.",
                "{S} propose un défi, {L} l'accepte avant la fin de la phrase. Les règles seront décidées en cours de route.",
                "{Ils} échangent leurs meilleures astuces à voix très basse, comme si le jeu pouvait les entendre.",
                "{Ils} se lancent dans un concours de « j'y ai joué plus longtemps que toi ». Le score final est un match nul de plusieurs semaines.",
                "{L} termine la phrase de {S} : « …le niveau du volcan ! » {S} ouvre de grands yeux. {Ils} l'ont {p:tous|toutes} les deux détesté.",
                "{Ils} font semblant d'appuyer sur des boutons en même temps, et rient de synchroniser leurs pouces." },
            new[] { "🎮 {Ils} inventent un jeu vidéo sans écran : il suffit de crier les actions très fort.",
                "🕹️ {Ils} rejouent le dernier niveau en vrai, en sautant par-dessus des racines. Personne n'a de vie supplémentaire.",
                "🏰 {Ils} construisent un donjon en brindilles, avec un boss en pomme de pin. Le boss gagne.",
                "👾 {S} explique les règles d'un jeu à {L}, qui perd dès la première seconde et réclame une revanche.",
                "🎯 {Ils} organisent un tournoi à deux. La finale est très disputée, les demi-finales aussi, bizarrement.",
                "🗡️ {Ils} font un combat de boss avec des brindilles. Le boss est une pomme de pin. Elle se défend bien.",
                "🧩 {Ils} construisent un niveau entier avec des cailloux et des feuilles. Il est injouable. {Ils} en sont très {p:fiers|fières}.",
                "💾 {S} explique à {L} comment sauvegarder une partie. {L} ne comprend pas, mais hoche la tête en sauvegardant quand même.",
                "🪙 {Ils} ramassent toutes les petites choses brillantes du coin en faisant « pling » à chaque fois.",
                "🤝 {Ils} jouent à un jeu en coopération. {Ils} perdent ensemble, avec beaucoup de dignité." }),
        new(PlynlingPassion.Astronomy, "🔭", "l'astronomie",
            new[] { "astronomie", "etoile", "etoiles", "planete", "planetes", "lune", "espace", "galaxie", "cosmos", "constellation", "constellations" },
            new[] { "{S} lève les yeux vers le ciel, même en plein jour.\nTu savais qu'il y a des étoiles qu'on voit alors qu'elles n'existent plus ?",
                "{S} désigne un point précis du ciel.\nLà. C'est là que j'aimerais aller. Pas pour toujours. Juste pour voir.",
                "{S} tient un petit dessin de constellation.\nJ'en ai inventé une nouvelle. Elle s'appelle « le Caillou qui pense ». Elle a trois étoiles.",
                "{S} parle d'une voix très douce, comme pour ne pas réveiller le ciel.\nLa lune s'éloigne un tout petit peu chaque année. Je ne veux pas qu'elle parte.",
                "{S} compte sur ses doigts, se trompe, recommence.\nIl y a plus d'étoiles dans le ciel que de grains de sable sur une plage. J'ai essayé de vérifier.",
                "{S} garde les yeux levés pendant tout le trajet.\nHier, j'ai vu une étoile filante. J'ai fait un vœu. Je ne peux pas te le dire, sinon ça ne marche pas.",
                "{S} porte une écharpe couverte d'étoiles dessinées à la craie.\nC'est une carte du ciel. Si je me perds, je n'ai qu'à regarder mon écharpe.",
                "{S} regarde le soleil du coin de l'œil, prudemment.\nC'est une étoile aussi, tu sais. La plus proche. C'est pour ça qu'elle chauffe autant.",
                "{S} compte à voix basse, les yeux fermés.\nJe mémorise les étoiles pour pouvoir les voir même le jour. Il m'en manque encore beaucoup.",
                "{S} montre un petit caillou noir et brillant.\nC'est peut-être un morceau de météorite. Ou un caillou. Je préfère la première version.",
                "{S} tient un petit télescope en carton contre son œil.\nJe vois une étoile ! Ah non, c'est un moustique. Mais il brillait.",
                "{S} parle doucement, les yeux perdus dans le vague.\nQuand je regarde les étoiles, je me sens {s:tout petit|toute petite}. Et c'est agréable, bizarrement.",
                "{S} dessine des cercles dans l'air.\nLa Terre tourne autour du soleil. Moi, je tourne autour du goûter. C'est pareil, en plus petit.",
                "{S} sort une carte du ciel pliée en douze.\nJe l'ai dessinée moi-même. Il y a quelques étoiles en trop. Je les trouve jolies.",
                "{S} a les yeux qui piquent.\nJ'ai veillé pour voir la lune se lever. Elle était en retard. Moi, j'étais à l'heure.",
                "{S} pointe le ciel avec enthousiasme.\nLà ! Une planète ! Enfin, peut-être. Ou un oiseau. Mais j'y crois.",
                "{S} récite des noms d'étoiles comme une comptine.\nBételgeuse, Rigel, Véga… Elles ont des noms plus jolis que les nôtres.",
                "{S} serre un petit bocal vide contre {s:lui|elle}.\nJ'essaie d'attraper un rayon de lune. Pour l'instant, j'ai surtout de l'air.",
                "{S} parle d'un ton très sérieux.\nSi un jour je vais dans l'espace, j'emporterai un caillou d'ici. Pour ne pas oublier.",
                "{S} lève les yeux et sourit sans raison.\nChaque étoile, c'est un soleil pour quelqu'un d'autre. Peut-être qu'un Plynling regarde le nôtre, là-bas." },
            new[] { "{Ils} comparent les constellations qu'{ils} ont inventées. Certaines se ressemblent beaucoup.",
                "{Ils} se mettent d'accord pour renommer une étoile ensemble. Ça ne compte pas officiellement. Ça compte quand même.",
                "{Ils} débattent pour savoir si la lune est plus jolie pleine ou en croissant. Personne ne cède.",
                "{Ils} s'allongent côte à côte pour regarder le ciel, et se taisent longtemps. C'est le meilleur genre de silence.",
                "{Ils} se partagent les étoiles : celles de gauche pour {S}, celles de droite pour {L}. La lune reste neutre.",
                "{Ils} font le même vœu en même temps, sans le dire. {Ils} le savent quand même.",
                "{Ils} lèvent les yeux au même instant vers la même étoile, et se sourient sans avoir besoin de la nommer.",
                "{S} montre du doigt un point du ciel. {L} le nomme aussitôt, avec le même nom secret. {Ils} en restent muets.",
                "{Ils} s'accordent pour dire que la nuit, c'est le meilleur moment de la journée, même quand c'est le jour.",
                "{Ils} rêvent tout haut d'un voyage jusqu'à la lune, avec un sac de cailloux et beaucoup de goûters.",
                "{L} sait le nom de l'étoile préférée de {S}, et {S} sait celui de la sienne. Personne ne l'avait jamais dit à voix haute.",
                "{Ils} restent un long moment la tête en arrière, à compter les étoiles, et perdent le compte au même endroit." },
            new[] { "🔭 {Ils} fabriquent un télescope avec une feuille roulée. On ne voit rien, mais c'est magnifique.",
                "🌙 {Ils} dessinent la lune à toutes ses étapes, sur une seule feuille. Elle a l'air de faire une grimace.",
                "⭐ {S} montre les constellations à {L}, qui en voit d'autres, plus drôles, aux mêmes endroits.",
                "🪐 {Ils} construisent une maquette du système solaire avec des baies. Certaines planètes sont mangées en route.",
                "🌠 {Ils} guettent une étoile filante. Elle ne vient pas. {Ils} en inventent une avec un caillou lancé très haut.",
                "☄️ {Ils} fabriquent une comète avec une pomme de pin et un ruban. Elle vole très mal, mais avec panache.",
                "🗺️ {Ils} dessinent une carte des constellations inventées. La plus grande s'appelle « le Goûter ».",
                "🔦 {Ils} jouent à être des étoiles avec des lucioles. Les lucioles ne sont pas vraiment d'accord.",
                "🌒 {S} explique les phases de la lune à {L} avec un biscuit, croqué petit à petit.",
                "🚀 {Ils} construisent une fusée en brindilles. Elle ne décolle pas. {Ils} font le compte à rebours quand même." }),
        new(PlynlingPassion.Gardening, "🌱", "le jardinage",
            new[] { "jardinage", "jardin", "jardiner", "plante", "plantes", "fleur", "fleurs", "potager", "graine", "graines" },
            new[] { "{S} montre fièrement une toute petite pousse dans un pot.\nElle est sortie ce matin. Je lui ai déjà trouvé un nom.",
                "{S} a de la terre sous les ongles et le sourire jusqu'aux oreilles.\nMes tomates ont rougi. Je crois qu'elles m'ont {s:entendu|entendue} leur faire des compliments.",
                "{S} tient délicatement une graine entre deux doigts.\nDedans, il y a un arbre entier. Il faut juste attendre cinquante ans.",
                "{S} parle tout bas.\nJe chante pour mes plantes le soir. Elles poussent mieux. Ou alors elles veulent que j'arrête.",
                "{S} montre une feuille avec beaucoup de fierté.\nRegarde cette nervure. Parfaite. Je l'ai vue pousser, de mes yeux.",
                "{S} arrache une mauvaise herbe en passant, par réflexe.\nPardon. C'est plus fort que moi. Je jardine même quand je suis en visite.",
                "{S} arrive avec une pousse plantée dans une coquille de noix.\nElle voulait voir du pays. Je l'emmène partout avec moi aujourd'hui.",
                "{S} parle d'une voix grave, comme pour annoncer une mauvaise nouvelle.\nUne limace a mangé ma plus belle salade. Je ne lui en veux pas. Enfin, un peu.",
                "{S} tient un petit plan dessiné à la main.\nC'est mon potager idéal. Il y a des fraises partout. Et encore des fraises à côté.",
                "{S} caresse une feuille du bout du doigt en passant.\nLes plantes aiment qu'on leur dise bonjour. Celle-ci, c'est Monique.",
                "{S} tient un petit arrosoir, même sans rien à arroser.\nOn ne sait jamais. Une plante peut avoir soif n'importe où.",
                "{S} a une feuille de menthe coincée entre les doigts.\nSens ça. J'en ai planté partout. Elle a un peu pris le contrôle.",
                "{S} parle tout bas, comme devant un berceau.\nMa graine de tournesol a germé cette nuit. Je suis {s:resté|restée} à côté d'elle toute la matinée.",
                "{S} montre ses mains couvertes de terre, sans aucune honte.\nLa terre sous les ongles, c'est la preuve qu'on a bien travaillé.",
                "{S} compte des graines dans le creux de sa main.\nDouze graines, douze fleurs. Enfin, si les oiseaux ne passent pas avant.",
                "{S} a l'air {s:inquiet|inquiète}.\nMes courgettes poussent trop vite. J'en ai une plus grande que moi. Elle me regarde.",
                "{S} tend un petit bouquet d'herbes aromatiques.\nThym, romarin, persil. Je les ai présentés les uns aux autres. Ils s'entendent bien.",
                "{S} fixe le sol avec une grande patience.\nJe regarde pousser mes radis. Il paraît qu'ils sont timides quand on les regarde.",
                "{S} montre une étiquette écrite à la main : « Ici poussera une fraise. »\nJe prépare le terrain. Pour la fraise. Et un peu pour moi.",
                "{S} secoue la tête, un peu {s:vexé|vexée}.\nLes pissenlits poussent partout sans qu'on leur demande rien. Mes roses, elles, font des caprices." },
            new[] { "{Ils} s'échangent des graines comme d'autres s'échangent des secrets.",
                "{Ils} s'échangent leurs astuces contre les limaces, à voix basse, comme des secrets d'État.",
                "{Ils} tombent à genoux devant la même petite fleur, exactement au même moment.",
                "{Ils} se montrent leurs plus belles pousses comme d'autres montrent des photos de famille.",
                "{Ils} tombent d'accord : parler aux plantes, ça marche. Surtout si on leur parle gentiment.",
                "{Ils} échangent des boutures en se promettant d'en prendre soin comme de trésors.",
                "{S} et {L} se penchent ensemble sur la même petite pousse, avec le même air {p:inquiets|inquiètes} et {p:ravis|ravies}.",
                "{Ils} se promettent de planter la même fleur chacun de son côté, pour qu'elles fleurissent en même temps.",
                "{Ils} constatent que leurs plantes préférées ont besoin des mêmes soins, du même soleil, et de la même patience.",
                "{L} explique à {S} une technique que {S} croyait secrète. C'est la même. {Ils} éclatent de rire.",
                "{Ils} se partagent un arrosoir imaginaire, à tour de rôle, en veillant à ne noyer personne.",
                "{Ils} s'accroupissent en même temps pour regarder un bourgeon. Personne ne parle, de peur de le déranger." },
            new[] { "🌱 {Ils} plantent une graine ensemble et la regardent pousser. Elle ne pousse pas. {Ils} restent quand même.",
                "🌻 {Ils} plantent des fleurs en forme d'étoile. Vu d'en haut, ça ressemble plutôt à une patate.",
                "💧 {S} arrose, {L} tient l'arrosoir. Puis l'inverse. Tout le monde est mouillé, les plantes aussi.",
                "🥕 {Ils} tirent sur une carotte récalcitrante. Elle cède d'un coup ; {ils} tombent à la renverse.",
                "🪴 {Ils} rempotent une petite plante et lui cherchent un nom. {Ils} ne sont pas d'accord sur le nom.",
                "🌸 {Ils} sèment des fleurs en dessinant leurs initiales. Dans quelques semaines, on les verra du ciel.",
                "🐌 {Ils} déménagent poliment une famille d'escargots hors du potager. Les escargots reviennent aussitôt.",
                "🍓 {Ils} cueillent des fraises. La moitié finit dans le panier ; l'autre moitié n'y arrive jamais.",
                "🌾 {S} apprend à {L} à désherber. {L} arrache une fleur par erreur et s'excuse auprès d'elle.",
                "🪱 {Ils} présentent un ver de terre à tout le jardin, comme un invité d'honneur." }),
        new(PlynlingPassion.Rocks, "🪨", "les cailloux",
            new[] { "caillou", "cailloux", "pierre", "pierres", "galet", "galets", "roche", "roches", "mineraux", "cristaux" },
            new[] { "{S} vide ses poches : une douzaine de cailloux roulent par terre.\nCelui-là, il est presque rond. Presque. C'est ce qui le rend spécial.",
                "{S} tend un caillou gris, parfaitement ordinaire.\nIl a l'air normal. C'est exactement ce qui le rend extraordinaire.",
                "{S} lèche un caillou pour en faire ressortir la couleur.\nNe me regarde pas comme ça. C'est une technique de professionnel.",
                "{S} a les poches qui tirent vers le bas.\nJ'en ai trouvé quarante aujourd'hui. J'en garde trente-neuf. Le dernier m'a {s:regardé|regardée} de travers.",
                "{S} présente un caillou avec cérémonie.\nVoici Bernard. Il a quatre cents ans. Peut-être quatre mille. Il ne dit pas son âge.",
                "{S} fait rouler un galet entre ses doigts.\nUn bon caillou, ça se choisit comme un ami : lisse, fidèle, et qui tient dans la poche.",
                "{S} tend un caillou percé d'un petit trou.\nSi tu regardes à travers, le monde a l'air plus rond. Essaie.",
                "{S} pose un caillou sur la tête de {L} sans prévenir.\nIl est bien, là. Il voulait voir la vue.",
                "{S} parle d'un ton de conspirateur.\nJ'ai un caillou qui a la forme d'un cœur. Presque. Il faut pencher un peu la tête.",
                "{S} range des cailloux en ligne, du plus petit au plus grand.\nNe les dérange pas. Ils sont en train de faire la queue.",
                "{S} tend un caillou tout lisse, encore chaud de sa poche.\nTiens-le un peu. Il est très apaisant. C'est son métier.",
                "{S} parle d'un ton très savant.\nCe caillou-là a vu passer des dinosaures. Enfin, peut-être. Il ne veut pas en parler.",
                "{S} fait ricocher un galet imaginaire.\nMon record, c'est sept ricochets. Le septième, personne ne l'a vu, mais je te jure.",
                "{S} montre un caillou à rayures.\nRegarde, il a des rayures. Il s'habille mieux que moi.",
                "{S} range un caillou dans une petite boîte doublée de mousse.\nC'est mon préféré. Il dort là-dedans. Ne le réveille pas.",
                "{S} tient deux cailloux presque identiques.\nDevine lequel est le plus beau. Non, c'est l'autre. Tout le monde se trompe.",
                "{S} porte une petite loupe autour du cou.\nDe près, chaque caillou a des paysages entiers dedans. Des montagnes, des rivières… en miniature.",
                "{S} soupèse un caillou, l'air {s:concentré|concentrée}.\nIl est lourd pour sa taille. C'est souvent signe de caractère.",
                "{S} arrive les poches vides, l'air un peu {s:perdu|perdue}.\nJ'ai offert toute ma collection à la rivière. Elle en avait plus besoin que moi. Je recommence.",
                "{S} présente un caillou tout noir.\nCelui-là, je l'ai appelé Minuit. Il ne brille pas, mais il a beaucoup de profondeur." },
            new[] { "{Ils} étalent leurs collections côte à côte. Le silence qui suit est plein de respect.",
                "{Ils} s'échangent deux cailloux, solennellement. C'est plus important qu'une poignée de main.",
                "{Ils} tombent d'accord : le meilleur caillou est toujours celui qu'on n'a pas encore trouvé.",
                "{Ils} échangent leurs techniques secrètes pour trouver les meilleurs cailloux. La principale : regarder par terre.",
                "{Ils} découvrent qu'{ils} ont {p:tous|toutes} les deux un caillou préféré en forme de cœur. {Ils} les comparent. Égalité.",
                "{Ils} se prêtent solennellement leurs meilleurs cailloux pour la journée. C'est une grande marque de confiance.",
                "{S} montre son plus beau caillou, {L} sort le même en un peu plus gros. Un silence, puis un fou rire.",
                "{Ils} constatent que les cailloux qu'{ils} préfèrent sont ceux que personne d'autre ne remarque.",
                "{Ils} échangent un caillou, se le remettent dans la main, puis l'échangent à nouveau, pour la beauté du geste.",
                "{L} reconnaît un caillou dans la collection de {S} : c'est {l:lui|elle} qui le lui avait trouvé, un jour, sans le dire.",
                "{Ils} s'accroupissent et fouillent le sol en même temps. La main de {S} et celle de {L} attrapent le même caillou.",
                "{Ils} se mettent d'accord : il n'y a pas de mauvais caillou, seulement des cailloux qui n'ont pas encore trouvé leur poche." },
            new[] { "🪨 {Ils} classent des cailloux par couleur, puis par taille, puis par « personnalité ».",
                "🔍 {Ils} partent à la chasse au caillou parfait. {Ils} en trouvent trois, et se disputent le plus parfait des trois.",
                "🏔️ {Ils} construisent une montagne de cailloux. Elle tient debout pendant presque une minute.",
                "🖌️ {S} dessine des visages sur des galets ; {L} leur invente des prénoms et des histoires tristes.",
                "🏆 {Ils} organisent un concours du plus beau caillou. Il y a deux candidats et deux vainqueurs.",
                "🌊 {Ils} font des ricochets. Le record est battu, puis re-battu, puis contesté.",
                "🏗️ {Ils} construisent une petite maison en cailloux pour une fourmi. Elle refuse de signer le bail.",
                "📛 {Ils} donnent un nom et un prénom à chaque caillou du coin. Il y a désormais trois « Bernard ».",
                "⚖️ {Ils} organisent une pesée officielle des cailloux. Le plus lourd reçoit une médaille en feuille.",
                "🔦 {S} montre à {L} un caillou qui brille dans le noir. Il ne brille pas vraiment, mais {L} fait semblant de le voir." }),
        new(PlynlingPassion.Stories, "📚", "les histoires",
            new[] { "histoire", "histoires", "lecture", "lire", "livre", "livres", "conte", "contes", "roman", "romans" },
            new[] { "{S} serre un vieux livre tout contre {s:lui|elle}.\nJ'en suis au moment où le dragon avoue qu'il a peur du noir. Je ne m'en remets pas.",
                "{S} parle en chuchotant, comme au coin du feu.\nIl était une fois un Plynling qui ne voulait jamais dormir. Tu devines la fin ? Moi non plus, je m'endors toujours avant.",
                "{S} referme un livre d'un coup sec.\nJe l'ai fini. Je ne sais plus quoi faire de ma vie. C'était tellement bien.",
                "{S} a les yeux qui brillent.\nJ'écris une histoire. Il y a un dragon, un pirate et un escargot. L'escargot est le héros.",
                "{S} récite une phrase avec emphase.\n« Et le vent emporta tous les secrets. » C'est la dernière phrase. Je n'ai pas encore écrit les autres.",
                "{S} porte une pile de livres plus haute que {s:lui|elle}.\nJe n'en ai lu aucun. Mais je sens qu'ils vont me plaire.",
                "{S} arrive en marchant comme dans un conte.\nAujourd'hui, je suis {s:un chevalier|une chevalière}. Demain, je redeviens moi.",
                "{S} lit en marchant et manque de trébucher.\nPardon ! J'étais en pleine bataille navale. Les pirates étaient sur le point de gagner.",
                "{S} tourne une page imaginaire.\nJ'ai commencé une histoire hier soir. Elle n'a pas de fin. Je crois qu'elle attend que je l'invente.",
                "{S} a les yeux encore un peu rouges.\nLe petit renard du livre a enfin retrouvé sa maison. Je ne pleure pas. Je suis juste {s:ému|émue}.",
                "{S} tient un livre à l'envers sans s'en apercevoir.\nC'est un livre très moderne. Il se lit dans les deux sens.",
                "{S} garde un petit marque-page en forme de feuille.\nJe l'ai laissé au meilleur passage. J'y retourne tous les soirs, juste pour le relire.",
                "{S} parle avec une voix grave de conteur.\nDans un pays lointain vivait un caillou qui rêvait de voler. Tu veux la suite ? Il n'y en a pas encore.",
                "{S} sort un carnet plein de noms de personnages.\nJ'ai inventé trente personnages. Il me manque juste l'histoire.",
                "{S} soupire, l'air rêveur.\nSi j'étais dans un livre, je serais le personnage qui arrive à la fin et qui sauve tout. Ou le chat.",
                "{S} a les joues rouges d'excitation.\nJ'ai deviné la fin avant tout le monde ! Enfin, avant moi-même. Mais quand même.",
                "{S} tient un livre si vieux qu'il tombe en morceaux.\nIl a été lu tellement de fois qu'il connaît l'histoire par cœur, lui aussi.",
                "{S} imite la voix d'un personnage de conte, très aiguë.\nC'est la voix de la princesse. Ou du méchant. Je n'ai pas encore décidé.",
                "{S} chuchote, l'air mystérieux.\nIl y a un livre dont personne ne lit jamais la dernière page. Moi, je l'ai lue. Je ne dirai rien.",
                "{S} serre un petit livre de contes contre {s:lui|elle}.\nOn me le lisait quand j'étais {s:tout petit|toute petite}. Maintenant, c'est moi qui le lis aux fourmis." },
            new[] { "{Ils} se racontent la fin de leurs livres préférés, en se coupant la parole.",
                "{Ils} découvrent qu'{ils} ont pleuré au même chapitre du même livre. Il fallait bien que quelqu'un le dise.",
                "{Ils} inventent une suite à leur histoire préférée. Elle est beaucoup plus longue que l'originale.",
                "{Ils} s'échangent des titres de livres, et chaque titre fait naître un « oh ! » de l'autre côté.",
                "{Ils} se mettent à jouer une scène de leur conte préféré, sans répétition, et c'est parfait.",
                "{Ils} découvrent qu'{ils} détestent le même personnage. C'est le début d'une grande complicité.",
                "{S} commence une phrase de son livre préféré, {L} la finit mot pour mot. Un silence ému suit.",
                "{Ils} comparent leurs passages préférés et découvrent qu'{ils} ont tout souligné aux mêmes endroits.",
                "{Ils} se mettent d'accord sur le meilleur personnage secondaire de l'histoire, un simple hérisson qui n'apparaît que deux fois.",
                "{L} promet de prêter son plus vieux livre à {S}, à condition qu'il revienne. {S} promet. {Ils} savent tous deux que c'est risqué.",
                "{Ils} relisent le même paragraphe à voix haute, chacun leur tour, en changeant de voix à chaque phrase.",
                "{Ils} se mettent à imaginer ce qui arrive après la dernière page. {S} pense à une fête, {L} à un voyage. {Ils} font les deux." },
            new[] { "📖 {S} lit une histoire à voix haute ; {L} fait toutes les voix des méchants.",
                "🐉 {Ils} jouent une histoire de dragon. {L} fait le dragon, avec beaucoup trop de conviction.",
                "✍️ {Ils} écrivent une histoire à deux, une phrase à tour de rôle. Elle part dans tous les sens, et c'est parfait.",
                "🏰 {S} raconte un conte de chevaliers ; {L} essaie de deviner la fin et se trompe à chaque fois.",
                "📚 {Ils} construisent un fort avec des livres et lisent dedans jusqu'à ce que le fort s'écroule.",
                "🎭 {Ils} jouent une pièce de théâtre à deux personnages. Chaque personnage change trois fois de costume.",
                "🕯️ {S} raconte une histoire qui fait peur. {L} a peur. {S} aussi, un peu.",
                "🦉 {Ils} inventent une histoire sur le hibou du coin. Le hibou écoute, et n'approuve pas la fin.",
                "📜 {Ils} écrivent un conte sur une grande feuille roulée. Il commence par « Il était une fois » et finit par « etc. ».",
                "🧚 {S} lit un passage à voix haute ; {L} mime tous les personnages, y compris le vent." }),
        new(PlynlingPassion.Dance, "💃", "la danse",
            new[] { "danse", "danser", "ballet", "valse", "tango" },
            new[] { "{S} fait trois pas de côté, un tour, et s'arrête net.\nJ'ai inventé un pas. Il n'a pas encore de nom. Ni de fin.",
                "{S} ne tient pas en place.\nJ'ai dansé toute la matinée. Mes pieds sont fatigués, mais ils veulent continuer.",
                "{S} fait une petite révérence.\nLa danse, c'est comme marcher, mais en plus joli et avec plus de risques.",
                "{S} montre un pas, très {s:concentré|concentrée}, la langue tirée.\nC'est un pas très ancien. Je l'ai inventé ce matin.",
                "{S} se met à tourner sur {s:lui|elle}-même.\nSi je tourne assez vite, j'ai l'impression de voler. Ou de tomber. Souvent de tomber.",
                "{S} tapote le sol en rythme.\nIl suffit d'écouter. Le sol a toujours une musique à proposer.",
                "{S} arrive en faisant des petits bonds.\nJe ne marche plus. Je danse partout. C'est plus lent, mais plus joli.",
                "{S} tourne une fois, deux fois, et vacille.\nJ'ai le vertige. Ça veut dire que c'était une bonne pirouette.",
                "{S} montre ses pieds avec fierté.\nIls ont appris un nouveau pas hier. Sans moi. Je suis un peu {s:vexé|vexée}, mais surtout {s:fier|fière}.",
                "{S} balance les bras en rythme.\nIl paraît que les arbres dansent quand il y a du vent. Moi, je n'attends pas le vent.",
                "{S} arrive en glissant sur le sol comme sur de la glace.\nC'est un pas que j'ai appris d'une feuille morte qui volait.",
                "{S} fait une petite courbette, très {s:élégant|élégante}.\nM'accorderais-tu cette danse ? Non ? Plus tard, alors. Je note.",
                "{S} bat des bras comme un oiseau.\nC'est la danse du moineau. Les moineaux ne l'ont pas encore validée.",
                "{S} fait un pas en avant, deux en arrière, un sur le côté.\nC'est une danse très ancienne. Elle date de ce matin.",
                "{S} a le souffle court et les yeux brillants.\nJ'ai dansé si longtemps que j'ai oublié pourquoi j'avais commencé. C'est ça, le secret.",
                "{S} fait des petits pas pressés sur place.\nJ'ai des fourmis dans les pieds. Alors je danse avec elles.",
                "{S} lève un bras très haut, très lentement.\nLe secret de la danse, c'est de faire semblant de savoir. Tout le reste suit.",
                "{S} tourne sur un pied en fermant les yeux.\nQuand je danse, je ne pense à rien. C'est le seul moment où ça marche.",
                "{S} montre une petite ceinture de feuilles qui virevolte à chaque mouvement.\nC'est mon costume de scène. Il fait « frrr » quand je tourne. C'est très important.",
                "{S} bouge doucement au rythme de rien du tout.\nJ'entends une musique. Tu ne l'entends pas ? Dommage, elle est très bien." },
            new[] { "Sans un mot, {ils} se mettent à danser le même pas. Ça marche du premier coup.",
                "{Ils} se mettent à danser sans musique. Au bout d'un moment, on l'entend presque.",
                "{Ils} inventent un pas à deux qui demande quatre pieds. {Ils} en ont justement quatre. C'est parfait.",
                "{Ils} se lancent dans un duo improvisé qui finit, évidemment, par une chute commune et un fou rire.",
                "{Ils} se découvrent le même pas préféré, et le font ensemble, trois fois, pour être {p:sûrs|sûres}.",
                "{Ils} inventent une chorégraphie en miroir. Personne ne sait plus qui imite qui.",
                "{S} lève un bras, {L} lève l'autre. Sans s'être concertés, {ils} forment un petit arc parfait.",
                "{Ils} découvrent qu'{ils} pivotent du même côté, au même moment, comme si le sol le leur ordonnait.",
                "{Ils} se mettent à danser au ralenti, en s'appliquant, comme au bord d'un lac où personne ne regarde.",
                "{L} corrige discrètement le pas de {S} d'un petit geste de la main. {S} s'exécute, {s:ravi|ravie}, sans un mot.",
                "{Ils} finissent la danse en même temps, exactement, et restent immobiles une seconde, comme devant un applaudissement invisible.",
                "{Ils} inventent en chemin un nouveau pas, qui n'a encore de nom pour personne. {Ils} le baptisent « le Nous »." },
            new[] { "💃 {S} apprend à {L} une petite danse. {L} marche sur tous les pieds disponibles.",
                "🩰 {S} donne un cours de danse à {L}. Premier exercice : ne pas tomber. {L} échoue brillamment.",
                "💫 {Ils} dansent sous les feuilles qui tombent, en essayant de les rattraper au vol.",
                "🕺 Battle de danse ! Le jury (un escargot) met si longtemps à juger que la battle recommence.",
                "🎊 {Ils} créent une chorégraphie en trois mouvements. Le troisième est un câlin, par accident.",
                "🪩 {Ils} organisent un bal pour les insectes. Les coccinelles viennent en couple, les fourmis en groupe.",
                "🌀 {Ils} tournent {p:sur eux-mêmes|sur elles-mêmes} jusqu'à ce que le monde tourne tout seul.",
                "🥁 {S} tape un rythme, {L} invente une danse dessus. Puis {L} tape, et c'est {S} qui danse, bien moins bien.",
                "🦩 {Ils} tiennent sur un pied le plus longtemps possible. {Ils} tombent en même temps, par solidarité.",
                "🎩 {Ils} apprennent une danse de salon. Il y a beaucoup de pieds écrasés, et beaucoup d'excuses." }),
        new(PlynlingPassion.Painting, "🎨", "la peinture",
            new[] { "peinture", "peindre", "dessin", "dessiner", "aquarelle", "tableau", "tableaux" },
            new[] { "{S} a de la peinture bleue jusqu'aux coudes.\nJ'essaie de peindre le vent. C'est plus dur que prévu.",
                "{S} tient un pinceau fait d'une brindille et d'une plume.\nJ'ai fabriqué mon propre pinceau. Il peint surtout à côté, mais il a du caractère.",
                "{S} montre une toile couverte de taches brunes.\nC'est un autoportrait. Tu vois la ressemblance ? Moi non plus, mais j'y crois.",
                "{S} plisse les yeux devant le paysage.\nLe ciel n'est jamais vraiment bleu, tu sais. Aujourd'hui, il est « presque lilas ».",
                "{S} a une trace de peinture jaune sur la joue.\nJ'ai peint un soleil si réussi que j'ai eu chaud en le regardant.",
                "{S} tient un carnet de croquis serré contre {s:lui|elle}.\nJe dessine tout ce que je vois. Surtout ce que je ne vois pas bien.",
                "{S} tient un pinceau entre les dents en parlant.\nMmh… pardon. Je peins avec les deux mains, alors il faut bien le ranger quelque part.",
                "{S} a peint un petit soleil sur le dos de sa main.\nComme ça, il fait beau même quand il pleut.",
                "{S} observe {L} en fermant un œil, le pinceau tendu.\nNe bouge pas. Je mesure. Tu as une tête parfaite pour un tableau.",
                "{S} montre une toile entièrement blanche.\nC'est un paysage sous la neige. J'ai mis trois jours. Il faut savoir s'arrêter.",
                "{S} a les doigts de toutes les couleurs.\nJ'ai peint un arc-en-ciel. Il a débordé un peu.",
                "{S} penche la tête pour regarder la lumière.\nÀ cette heure-ci, tout devient doré. C'est l'heure préférée des peintres. Et des chats.",
                "{S} montre un tableau où tout est violet.\nJe n'avais plus que du violet. Alors le monde est violet, cette fois.",
                "{S} tient un pinceau si usé qu'il n'a plus que trois poils.\nIl a peint tellement de choses. Je ne peux pas le remplacer. On a une histoire.",
                "{S} dessine des formes dans l'air avec le doigt.\nTu vois ce nuage ? Je le peins dans ma tête. Il n'est pas encore sec.",
                "{S} soupire devant une tache sur sa toile.\nC'était une erreur. Maintenant, c'est un oiseau. En peinture, les erreurs deviennent des oiseaux.",
                "{S} plisse les yeux, très {s:concentré|concentrée}.\nJe cherche le vert exact d'une feuille au soleil. J'en suis à mon quarantième essai.",
                "{S} tend un petit portrait maladroit.\nC'est toi. Enfin, c'est toi un jour de grand vent. Les couleurs sont un choix artistique.",
                "{S} tient une petite palette taillée dans une écorce.\nJe fabrique mes couleurs moi-même. Le jaune, c'est du pollen. Le bleu, c'est un secret.",
                "{S} regarde ses mains avec fierté.\nLa peinture ne part plus. Je crois que je suis {s:devenu|devenue} une œuvre d'art." },
            new[] { "{Ils} comparent leurs taches de peinture comme des médailles.",
                "{Ils} discutent de couleurs pendant un long moment. Il existe, apparemment, douze sortes de vert.",
                "{Ils} se reconnaissent aux taches de peinture sur leurs mains. C'est comme un club secret.",
                "{Ils} se lancent dans une discussion passionnée sur la plus belle couleur. Le jaune gagne, puis perd, puis regagne.",
                "{Ils} peignent sur la même toile sans se parler. Le résultat est étrange et magnifique.",
                "{Ils} comparent leurs pinceaux préférés avec le sérieux de deux grands maîtres.",
                "{S} tend un pinceau à {L}, qui le prend comme un cadeau précieux. Ils ne disent rien. Il n'y a rien à dire.",
                "{Ils} constatent qu'{ils} ont utilisé la même couleur pour le ciel, alors que personne ne l'avait dit.",
                "{Ils} se mettent à peindre à quatre mains sur la même feuille, sans se demander qui tient quoi.",
                "{L} reconnaît la touche de {S} avant même la signature au bas du tableau. {S} en rougit, {s:flatté|flattée}.",
                "{Ils} s'accordent pour dire que le bleu est la couleur des jours qui commencent, et le jaune de ceux qui durent.",
                "{Ils} regardent ensemble un coucher de soleil en retenant chaque nuance, comme deux peintres qui n'ont pas de toile." },
            new[] { "🎨 {Ils} peignent le portrait {p:l'un de l'autre|l'une de l'autre}. Personne n'est ressemblant.",
                "🖼️ {Ils} peignent le même paysage côte à côte. Les deux tableaux n'ont absolument rien en commun.",
                "🌈 {S} mélange toutes les couleurs pour trouver la plus belle. {L} annonce que c'est marron.",
                "✏️ {S} fait un croquis rapide de {L}, qui prend la pose pendant beaucoup trop longtemps.",
                "🪨 {Ils} peignent une fresque sur un grand rocher. Un lézard proteste, puis finit par poser.",
                "🖍️ {Ils} dessinent à la craie sur un grand rocher plat. La pluie fera le reste.",
                "🍂 {Ils} font un tableau entièrement en feuilles collées. Le vent n'est pas d'accord.",
                "🌅 {Ils} peignent le coucher du soleil. Le soleil se couche trop vite ; {ils} finissent de mémoire.",
                "🟤 {S} apprend à {L} à mélanger les couleurs. Tout finit en marron, mais un joli marron.",
                "🙂 {Ils} décorent des cailloux avec des petits visages. Chaque visage a l'air légèrement surpris." }),
        new(PlynlingPassion.Sport, "🏃", "le sport",
            new[] { "sport", "course", "courir", "football", "foot", "natation", "nager", "velo", "escalade", "tennis" },
            new[] { "{S} trottine sur place en parlant.\nJ'ai couru quatre tours ce matin. Cinq, si on compte celui où je me suis {s:perdu|perdue}.",
                "{S} fait des étirements en parlant, l'air très sérieux.\nOn ne néglige jamais l'échauffement. Jamais. J'ai une crampe rien que d'en parler.",
                "{S} bombe le torse.\nJe me suis {s:entraîné|entraînée} à sauter par-dessus une flaque. J'ai presque réussi. Je sèche encore.",
                "{S} a les joues toutes rouges.\nJ'ai couru si vite ce matin que mon ombre a mis du temps à me rattraper.",
                "{S} fait semblant de lancer une balle très loin.\nLe secret, c'est le poignet. Et la chance. Surtout la chance.",
                "{S} compte ses pas à voix haute.\nJe me suis fixé un objectif : mille pas avant le goûter. J'en suis à quarante.",
                "{S} arrive en courant, fait trois tours autour de {L} et s'arrête enfin.\nPardon. J'avais encore un peu d'élan.",
                "{S} fait des pompes, ou quelque chose qui y ressemble.\nUne… deux… Bon, deux, c'est bien pour aujourd'hui.",
                "{S} tient une petite médaille en carton.\nJe l'ai gagnée. Contre moi-même. C'était une course serrée.",
                "{S} saute sur place pour ne pas refroidir.\nIl faut toujours être {s:prêt|prête} à courir. On ne sait jamais quand un goûter s'échappe.",
                "{S} arrive en faisant des sauts de grenouille.\nC'est mon échauffement. La grenouille d'à côté est d'accord, elle aussi.",
                "{S} montre ses mollets avec fierté.\nRegarde. Enfin, imagine. Ils ont beaucoup travaillé cette semaine.",
                "{S} boit une grande gorgée de rosée.\nIl faut bien s'hydrater. C'est ce que disent les sportifs. Et les plantes.",
                "{S} lance une noix en l'air et la rattrape.\nTrente-deux fois de suite, ce matin. La trente-troisième est tombée sur ma tête.",
                "{S} court sur place en fixant un point au loin.\nJe m'entraîne pour la grande course. Je ne sais pas encore quand elle aura lieu, mais je serai {s:prêt|prête}.",
                "{S} tient une petite coupe en écorce.\nJe l'ai gagnée au saut en longueur. J'étais {s:le seul participant|la seule participante}, mais j'ai sauté très loin.",
                "{S} fait des étirements compliqués et se retrouve {s:coincé|coincée}.\nAide-moi. Non, attends. C'est une position de yoga. Je reste comme ça.",
                "{S} porte un petit bandeau autour du front.\nC'est pour la transpiration. Je ne transpire pas encore, mais je suis {s:prévoyant|prévoyante}.",
                "{S} regarde {L} d'un air de défi.\nJe parie que je fais le tour de ce buisson plus vite que toi. Non, ne réponds pas, cours.",
                "{S} souffle comme après un marathon.\nJ'ai couru jusqu'ici. Enfin, les derniers mètres. Mais je les ai courus très fort." },
            new[] { "{Ils} se lancent un défi de course avant même d'avoir fini de parler.",
                "{Ils} se lancent des défis de plus en plus absurdes. Le dernier consiste à courir en arrière en chantant.",
                "{Ils} comparent leurs records. Aucun n'a jamais été vérifié, mais {ils} y croient très fort.",
                "{Ils} se donnent rendez-vous pour s'entraîner demain à l'aube. Personne ne se lèvera à l'aube.",
                "{Ils} comparent leurs échauffements, puis les combinent en un seul, beaucoup trop long.",
                "{Ils} se tapent dans la main avec tant d'énergie qu'{ils} en ont les paumes qui chauffent.",
                "{Ils} se mettent à trottiner sur place, chacun à sa façon, jusqu'à ce que les deux rythmes se rejoignent.",
                "{S} propose un tour, {L} propose deux. {Ils} se mettent d'accord sur trois, pour avoir chacun raison.",
                "{Ils} constatent qu'{ils} détestent perdre autant l'un que l'autre, et qu'{ils} adorent ça.",
                "{L} tend la main pour aider {S} à se relever après une chute. {S} la prend, puis la lâche en courant : « Rattrape-moi ! »",
                "{Ils} font ensemble la même série d'étirements, en soufflant en même temps, comme deux soufflets accordés.",
                "{Ils} finissent la course sur la même ligne, au même instant. Personne ne veut être le premier à déclarer l'égalité." },
            new[] { "🏃 Course jusqu'au bout du chemin ! {S} part trop vite et s'essouffle à mi-parcours.",
                "⚽ {Ils} jouent au ballon avec une noix. La noix gagne.",
                "🏁 {Ils} font la course jusqu'au prochain arbre, puis jusqu'au suivant, puis jusqu'à l'épuisement.",
                "🤸 {S} apprend la roue à {L}. Le résultat ressemble surtout à une chute bien organisée.",
                "🏅 {Ils} organisent des jeux olympiques à deux. Il y a une médaille par épreuve et trois épreuves en tout.",
                "🏐 {Ils} se renvoient une feuille par-dessus une ligne tracée au sol. La feuille ne coopère pas.",
                "🧗 {Ils} escaladent une grosse racine. Au sommet, {ils} plantent un drapeau en brindille.",
                "🏋️ {Ils} soulèvent des cailloux de plus en plus gros. Le dernier reste par terre. Il a gagné.",
                "🛷 {Ils} dévalent une petite pente sur une grande feuille. Puis remontent. Puis redévalent. Tout l'après-midi.",
                "🎽 {S} entraîne {L} comme un vrai coach, avec un sifflet imaginaire. {L} obéit, en râlant un peu." }),
        new(PlynlingPassion.Insects, "🐞", "les insectes",
            new[] { "insecte", "insectes", "fourmi", "fourmis", "coccinelle", "coccinelles", "papillon", "papillons", "scarabee", "abeille", "abeilles" },
            new[] { "{S} s'accroupit devant une fourmi qui transporte une miette énorme.\nElle porte cinquante fois son poids. Moi, je ne porte même pas mon goûter jusqu'au bout.",
                "{S} garde une coccinelle sur le doigt depuis le début.\nElle s'appelle Pépite. On se connaît depuis ce matin. C'est déjà sérieux.",
                "{S} se penche sur une feuille pleine de trous.\nUne chenille a mangé tout ça. Toute seule. Je suis {s:admiratif|admirative} et un peu {s:inquiet|inquiète}.",
                "{S} chuchote pour ne pas déranger.\nLes abeilles dansent pour se dire où sont les fleurs. Moi, je danse juste pour le plaisir.",
                "{S} montre un scarabée qui brille au soleil.\nOn dirait un bijou. Mais un bijou qui marche et qui a son propre avis.",
                "{S} suit une file de fourmis du regard.\nElles savent toujours où elles vont. J'aimerais bien savoir faire ça, moi aussi.",
                "{S} garde les mains en coupe, avec beaucoup de précautions.\nIl y a un grillon dedans. Il est timide. Ne fais pas de bruit, il va chanter.",
                "{S} observe une araignée au travail, {s:fasciné|fascinée}.\nElle tisse sa toile depuis ce matin. C'est plus joli que tout ce que j'ai jamais fait.",
                "{S} parle tout bas, avec respect.\nLes papillons goûtent avec leurs pieds. Imagine marcher sur une tarte.",
                "{S} montre un petit carnet plein de croquis de scarabées.\nJ'en ai répertorié vingt-trois. Le vingt-quatrième refuse de poser.",
                "{S} a une petite chenille qui se promène sur son bras.\nElle s'appelle Brindille. Un jour, ce sera un papillon. Je suis déjà {s:fier|fière} d'elle.",
                "{S} chuchote en montrant une toile d'araignée pleine de rosée.\nRegarde ça. On dirait un collier. Elle l'a fait en une nuit.",
                "{S} s'allonge dans l'herbe, le nez au ras du sol.\nIl y a toute une ville, là-dessous. Des rues, des embouteillages, des disputes.",
                "{S} montre une libellule posée sur une tige.\nElle sait voler en arrière, tu sais. Moi, je n'arrive même pas à marcher en arrière.",
                "{S} parle avec un grand respect.\nUne abeille, dans toute sa vie, fait une toute petite cuillère de miel. Une seule. Il faut la respecter.",
                "{S} garde une coccinelle dans le creux de sa main.\nJ'ai compté ses points. Sept. Elle n'a pas voulu me dire son âge.",
                "{S} imite le vol d'un bourdon, très mal.\nBzzz. Les bourdons ne devraient pas pouvoir voler, paraît-il. Ils volent quand même. J'adore leur attitude.",
                "{S} montre un petit carnet de dessins d'insectes.\nJ'ai dessiné une fourmi. Elle a six pattes. J'en ai dessiné huit. Je corrige.",
                "{S} écoute attentivement le chant des grillons.\nIls chantent plus vite quand il fait chaud. Ce sont de vrais thermomètres.",
                "{S} suit des yeux un scarabée qui pousse une boulette.\nIl ne lâche jamais. C'est mon modèle. Enfin, sauf pour la boulette." },
            new[] { "{Ils} s'allongent à plat ventre pour suivre une colonne de fourmis. Pendant très longtemps.",
                "{Ils} s'accroupissent en même temps devant le même papillon, et retiennent leur souffle ensemble.",
                "{Ils} donnent un prénom à chaque fourmi qui passe. Au bout de quarante, {ils} recommencent à « Gérard ».",
                "{Ils} découvrent qu'{ils} ont donné le même prénom à la même coccinelle, sans s'être concertés.",
                "{Ils} restent immobiles un long moment pour qu'un papillon se pose. Il se pose. Personne ne respire.",
                "{Ils} échangent leurs meilleures observations d'insectes, comme deux vieux savants.",
                "{S} et {L} pointent en même temps le même scarabée, et se taisent pour ne pas l'effrayer.",
                "{Ils} constatent que la fourmi qu'{ils} suivaient depuis un moment était la même, et qu'elle les suivait aussi.",
                "{Ils} se partagent une loupe imaginaire, à tour de rôle, en poussant des « oh ! » à chaque découverte.",
                "{L} sait le nom d'un papillon que {S} cherchait depuis des semaines. {S} est bouleversé{s:|e}.",
                "{Ils} s'assoient côte à côte et écoutent les grillons en battant la mesure du doigt, sur le même rythme.",
                "{Ils} se promettent de ne jamais écraser une seule fourmi, même par mégarde. C'est un serment sérieux." },
            new[] { "🐞 {Ils} construisent un petit hôtel pour coccinelles. Il n'a pas encore de clients.",
                "🦋 {Ils} suivent un papillon pendant très longtemps, sans jamais réussir à savoir où il va.",
                "🔎 {S} inspecte un brin d'herbe avec une loupe. {L} trouve trois insectes que {S} n'avait pas vus.",
                "🐜 {Ils} aident une fourmi à porter sa miette. Elle n'a rien demandé, mais elle accepte.",
                "🏠 {Ils} fabriquent une petite maison en brindilles pour un scarabée. Il préfère son caillou.",
                "🐛 {Ils} font une course de chenilles. Les chenilles s'arrêtent pour manger en plein milieu.",
                "🍯 {Ils} rendent visite à une ruche et restent à distance respectueuse. Très respectueuse.",
                "🪲 {Ils} construisent un parcours d'obstacles pour scarabées. Le scarabée le contourne entièrement.",
                "🌼 {S} montre à {L} comment les abeilles choisissent leurs fleurs. {L} choisit la même fleur. Elle est très bien.",
                "🦗 {Ils} essaient de répondre aux grillons en sifflant. Les grillons se taisent, vexés." }),
        new(PlynlingPassion.Naps, "😴", "les siestes",
            new[] { "sieste", "siestes", "dormir", "sommeil", "dodo", "roupiller" },
            new[] { "{S} bâille avant même d'avoir dit bonjour.\nJ'ai fait une sieste si réussie que j'en ai rêvé d'une autre, dedans.",
                "{S} parle d'une voix encore toute molle.\nJe viens de me réveiller. Enfin, une partie de moi. Le reste arrive.",
                "{S} désigne un coin d'herbe au soleil avec gravité.\nCet endroit-là, c'est le meilleur du coin pour une sieste. Je l'ai testé quarante fois.",
                "{S} bâille, s'excuse, bâille encore.\nUne sieste réussie, c'est un art. Il faut savoir quand s'arrêter. Moi, je ne sais pas.",
                "{S} tient un petit coussin sous le bras.\nJe l'emmène partout. On ne sait jamais quand l'occasion se présente.",
                "{S} a encore la marque de l'herbe sur la joue.\nJ'ai rêvé que je faisais une sieste. Je me suis {s:réveillé|réveillée} très {s:reposé|reposée}.",
                "{S} arrive avec un oreiller de mousse sous le bras.\nJe ne compte pas dormir. C'est juste au cas où.",
                "{S} s'assoit, puis s'allonge, puis ferme un œil en parlant.\nJe t'écoute, hein. Je t'écoute avec un seul œil, c'est tout.",
                "{S} raconte un rêve avec beaucoup de détails.\nJ'étais un nuage, et je faisais la sieste sur un autre nuage. C'était très reposant.",
                "{S} regarde le ciel d'un air expert.\nCe soleil-là, c'est un soleil de sieste. Il ne faut pas le gâcher.",
                "{S} arrive les yeux mi-clos.\nJe ne dors pas. Je repose mes yeux. C'est complètement différent.",
                "{S} s'étire longuement.\nJ'ai fait une sieste de dix minutes. Elle a duré deux heures. C'est souvent comme ça.",
                "{S} désigne un rayon de soleil sur l'herbe.\nTu vois ce petit carré de soleil ? C'est le mien. Je l'ai réservé.",
                "{S} parle en bâillant à chaque mot.\nJe… me… suis… {s:levé|levée}… trop… tôt.",
                "{S} tient une petite couverture de feuilles.\nElle est toute douce. Je l'ai tricotée en dormant. Enfin, je crois.",
                "{S} a l'air très {s:reposé|reposée}, et très {s:fier|fière} de l'être.\nNeuf siestes aujourd'hui. Un record. Je vais fêter ça par une sieste.",
                "{S} compte les moutons sur ses doigts.\nJ'en suis à trois cents. Aucun ne m'a encore {s:endormi|endormie}.",
                "{S} s'appuie contre {L} sans prévenir.\nTu es très confortable, tu sais. Ne bouge pas, je teste.",
                "{S} parle d'un ton de grand spécialiste.\nIl y a la sieste courte, la sieste longue, et la sieste où on ne sait plus quel jour on est.",
                "{S} bâille si fort qu'{s:il|elle} en a les larmes aux yeux.\nPardon. Ce n'est pas toi. C'est l'heure. Enfin, c'est toutes les heures." },
            new[] { "{Ils} tombent d'accord sur un point essentiel : la meilleure sieste, c'est la prochaine.",
                "{Ils} s'accordent sur la durée idéale d'une sieste : « un peu plus longtemps ». C'est très scientifique.",
                "{Ils} bâillent en même temps, puis encore en même temps. C'est contagieux, et personne ne lutte.",
                "{Ils} comparent leurs meilleurs coins de sieste. Chaque coin est défendu avec passion.",
                "{Ils} se promettent de faire une sieste ensemble un jour. Probablement tout de suite.",
                "{Ils} bâillent en chœur, puis rient de bâiller, puis bâillent de rire.",
                "{Ils} s'installent chacun dans son coin d'herbe préféré, puis se rapprochent, insensiblement, pour ne faire qu'un seul coin.",
                "{Ils} discutent du meilleur moment pour faire la sieste, et concluent : tout de suite. C'est tout dire.",
                "{S} bâille, {L} bâille en réponse, {S} rebâille. Ça pourrait durer toute la journée.",
                "{Ils} constatent que la sieste est la seule activité où on est {p:tous|toutes} les deux {p:excellents|excellentes} sans effort.",
                "{L} prête son coussin à {S}, qui le lui rend un peu plus tard, en échange d'un coin d'ombre. C'est un traité de paix.",
                "{Ils} se promettent une grande sieste à deux pour la prochaine fois, avec couvertures et sans réveil." },
            new[] { "😴 {Ils} testent tous les coins d'herbe pour trouver le meilleur endroit où faire la sieste. {Ils} s'endorment avant la fin.",
                "☁️ {Ils} regardent les nuages et leur trouvent des formes. Le troisième ressemble à un oreiller ; c'est la fin.",
                "🛌 {Ils} construisent un lit de mousse pour deux. Il est parfait. Il est même trop parfait.",
                "💤 {S} raconte une histoire à {L} pour l'aider à s'endormir. C'est {S} qui s'endort en premier.",
                "🌿 {Ils} font la sieste à l'ombre d'une grande feuille. Un escargot s'installe à côté et s'endort aussi.",
                "🧸 {Ils} construisent un nid de feuilles géant et s'y installent « juste pour essayer ».",
                "🌤️ {Ils} suivent le soleil d'un coin d'herbe à l'autre pour rester au chaud tout l'après-midi.",
                "🎐 {S} fabrique un petit mobile qui tinte au vent pour bercer {L}. Ça marche très bien. Trop bien.",
                "⏳ {Ils} chronomètrent la sieste parfaite avec un sablier. Le sablier se termine bien avant la sieste.",
                "🐑 {Ils} comptent les nuages au lieu des moutons. Au quatrième, plus personne ne compte." }),
    };

    // Pair activities, keyed in either order (see ComboFor). Beat 4 prefers these.
    private static readonly Dictionary<(PlynlingPassion, PlynlingPassion), string[]> Combos = new()
    {
        [Pair(PlynlingPassion.Cooking, PlynlingPassion.Music)] = new[] { "🎶 {Ils} composent une chanson sur les crêpes. Le refrain dit seulement « crêpe », mais avec beaucoup d'émotion." },
        [Pair(PlynlingPassion.Astronomy, PlynlingPassion.Naps)] = new[] { "🌌 {Ils} s'allongent pour regarder les étoiles. Au bout de la troisième, tout le monde dort." },
        [Pair(PlynlingPassion.Insects, PlynlingPassion.Gardening)] = new[] { "🐛 {Ils} font la visite du potager en saluant chaque insecte par son prénom." },
        [Pair(PlynlingPassion.Cooking, PlynlingPassion.Gardening)] = new[] { "🥕 {Ils} cueillent des légumes et en font une soupe. Elle est délicieuse et un peu terreuse." },
        [Pair(PlynlingPassion.Cooking, PlynlingPassion.Insects)] = new[] { "🐝 {Ils} vont demander un peu de miel aux abeilles. Les abeilles négocient durement." },
        [Pair(PlynlingPassion.Music, PlynlingPassion.Dance)] = new[] { "🎶 {S} joue, {L} danse, puis {ils} échangent. Personne n'est doué pour le rôle de l'autre, et c'est très drôle." },
        [Pair(PlynlingPassion.Music, PlynlingPassion.Stories)] = new[] { "🎼 {Ils} transforment un conte en chanson. Ça dure longtemps. Personne ne s'en plaint." },
        [Pair(PlynlingPassion.Gaming, PlynlingPassion.Sport)] = new[] { "🏃 {Ils} jouent à un jeu vidéo… en vrai. Il faut courir, sauter, et crier « pause » quand on n'en peut plus." },
        [Pair(PlynlingPassion.Gaming, PlynlingPassion.Stories)] = new[] { "🗺️ {Ils} inventent l'histoire d'un jeu vidéo qui n'existe pas. Le héros est un Plynling, évidemment." },
        [Pair(PlynlingPassion.Astronomy, PlynlingPassion.Stories)] = new[] { "🌌 {Ils} inventent une légende pour chaque étoile. Il y en a beaucoup. La journée ne suffit pas." },
        [Pair(PlynlingPassion.Painting, PlynlingPassion.Gardening)] = new[] { "🌷 {Ils} peignent les fleurs du jardin. Les fleurs, flattées, se tiennent bien droites." },
        [Pair(PlynlingPassion.Painting, PlynlingPassion.Astronomy)] = new[] { "🎨 {Ils} peignent un ciel étoilé sur une grande pierre. Il y a plus d'étoiles sur le tableau que dans le vrai." },
        [Pair(PlynlingPassion.Rocks, PlynlingPassion.Painting)] = new[] { "🪨 {Ils} peignent des cailloux et les cachent un peu partout, pour que d'autres les trouvent." },
        [Pair(PlynlingPassion.Sport, PlynlingPassion.Naps)] = new[] { "😴 Course jusqu'au meilleur coin pour faire la sieste ! Le vainqueur s'endort sur la ligne d'arrivée." },
        [Pair(PlynlingPassion.Dance, PlynlingPassion.Sport)] = new[] { "🤸 {Ils} inventent un sport qui ressemble beaucoup à de la danse. Ou une danse qui ressemble beaucoup à du sport." },
        [Pair(PlynlingPassion.Cooking, PlynlingPassion.Stories)] = new[] { "📖 {Ils} écrivent un livre de recettes qui est aussi un conte. Chaque plat a son méchant." },
        [Pair(PlynlingPassion.Cooking, PlynlingPassion.Naps)] = new[] { "🥛 {Ils} préparent le goûter idéal avant la sieste. {Ils} s'endorment avant de le manger." },
        [Pair(PlynlingPassion.Music, PlynlingPassion.Astronomy)] = new[] { "🎶 {Ils} composent une chanson pour chaque planète. Celle de la lune est une berceuse." },
        [Pair(PlynlingPassion.Music, PlynlingPassion.Insects)] = new[] { "🦗 {Ils} forment un orchestre avec les grillons. Les grillons exigent d'être en tête d'affiche." },
        [Pair(PlynlingPassion.Gaming, PlynlingPassion.Rocks)] = new[] { "🪨 {Ils} inventent un jeu où il faut collectionner des cailloux rares. Le niveau final est une rivière." },
        [Pair(PlynlingPassion.Gaming, PlynlingPassion.Painting)] = new[] { "🎨 {Ils} dessinent les décors d'un jeu vidéo imaginaire. Le boss final est un très grand escargot." },
        [Pair(PlynlingPassion.Astronomy, PlynlingPassion.Rocks)] = new[] { "☄️ {Ils} cherchent une météorite parmi les cailloux. {Ils} en trouvent une au moins quatre fois." },
        [Pair(PlynlingPassion.Gardening, PlynlingPassion.Naps)] = new[] { "🌿 {Ils} plantent un carré de mousse spécialement pour les siestes. Il est testé immédiatement." },
        [Pair(PlynlingPassion.Dance, PlynlingPassion.Painting)] = new[] { "💃 {Ils} peignent en dansant, un pinceau dans chaque main. Le tableau est plein de tourbillons." },
        [Pair(PlynlingPassion.Stories, PlynlingPassion.Insects)] = new[] { "🐞 {Ils} inventent l'épopée d'une coccinelle courageuse. Elle affronte une flaque gigantesque." },
    };

    private static (PlynlingPassion, PlynlingPassion) Pair(PlynlingPassion a, PlynlingPassion b) => a <= b ? (a, b) : (b, a);

    public static string[]? ComboFor(PlynlingPassion a, PlynlingPassion b) => Combos.GetValueOrDefault(Pair(a, b));

    public static PassionInfo Info(PlynlingPassion passion) => All[(int)passion];

    public static PlynlingPassion RollInnate(Random rng) => (PlynlingPassion)rng.Next(All.Count);

    private static readonly Regex LeadingArticle = new(@"^(de la |de l'|du |des |les |le |la |l'|un |une )", RegexOptions.Compiled);
    private static readonly Regex NotWord = new(@"[^a-z0-9' ]+", RegexOptions.Compiled);
    private static readonly Regex Spaces = new(@"\s+", RegexOptions.Compiled);

    /// <summary>Lowercase, no accents, no leading article, no punctuation, single spaces.</summary>
    public static string Normalize(string text)
    {
        var decomposed = text.Replace('’', '\'').ToLowerInvariant().Normalize(NormalizationForm.FormD);
        var bare = new StringBuilder(decomposed.Length);
        foreach (var ch in decomposed)
            if (CharUnicodeInfo.GetUnicodeCategory(ch) != UnicodeCategory.NonSpacingMark) bare.Append(ch);
        var s = Spaces.Replace(NotWord.Replace(bare.ToString(), " "), " ").Trim();
        s = LeadingArticle.Replace(s, "");          // the apostrophe is still there, so « l' » is caught
        return Spaces.Replace(s.Replace("'", " "), " ").Trim();
    }

    /// <summary>What gets stored: line breaks and runs of spaces collapsed, trimmed.</summary>
    public static string Clean(string? raw) => raw is null ? "" : Spaces.Replace(raw, " ").Trim();

    public static bool ContainsLink(string text)
    {
        var lower = text.ToLowerInvariant();
        return lower.Contains("http") || lower.Contains("www.") || lower.Contains("discord.gg");
    }

    /// <summary>The catalog passion a typed text names, if a keyword appears in it as a whole word.</summary>
    public static PlynlingPassion? Resolve(string text)
    {
        var norm = " " + Normalize(text) + " ";
        foreach (var info in All)
            foreach (var keyword in info.Keywords)
                if (norm.Contains(" " + keyword + " ")) return info.Passion;
        return null;
    }

    public static Passion FromText(string text) =>
        Resolve(text) is { } c ? new Passion(c, null) : new Passion(null, text);

    public static Passion? Taught(Plynling p) =>
        string.IsNullOrWhiteSpace(p.TaughtPassion) ? null : FromText(p.TaughtPassion);

    /// <summary>Its passions: the innate one, then the taught one unless it is the same.</summary>
    public static IReadOnlyList<Passion> Of(Plynling p)
    {
        var innate = new Passion(p.Passion, null);
        return Taught(p) is { } taught && !taught.SameAs(innate) ? new[] { innate, taught } : new[] { innate };
    }
}
