namespace ProjectSYNCS.Helpers;

// Display only (the card's header): rounds store the question key, never its category, so a
// question can move between categories freely.
public enum QuizCategory { Tech, Games, Culture, Absurd, Syncs, Nature, Science, Geography, History, Food, Words, Mycology }

public enum QuizDifficulty { Easy, Medium, Hard }

/// <summary>One question of her pop quiz.</summary>
/// <param name="Answers">
/// The display answer first. For an open question, every other entry is an accepted
/// spelling (QuizAnswer compares them all). For multiple choice, just the right choice.
/// </param>
/// <param name="Choices">Exactly four, the right one first (shuffled at post time); null for an open question.</param>
/// <param name="Aside">Her comment under the revealed answer. Every question has one.</param>
public sealed record QuizQuestion(
    string Key,
    QuizCategory Category,
    QuizDifficulty Difficulty,
    string Prompt,
    IReadOnlyList<string> Answers,
    IReadOnlyList<string>? Choices,
    string Aside)
{
    public bool IsChoice => Choices is not null;
    public string Display => Answers[0];
}

// The questions of her pop quiz (QuizMasterService). Walked through by DailyRotation, keyed
// by how many rounds the guild has had, so nothing repeats until the whole bank is spent.
//
// Authoring rules:
//
// - **Keys are stored** (QuizRound.QuestionKey): append-only, never renamed. Adding or
//   removing a question reshuffles the walk from the next round on; that's fine. A key's
//   prefix is the category it was written under: moving it (culture.octopus is Nature now)
//   never renames it.
// - **Every fact is true**, as for MorningFunFacts: the joke is her aside, never an
//   invented answer. Many questions are adapted from those fun facts on purpose.
// - **An answer someone could find by spamming guesses is multiple choice**: years, small
//   numbers, yes/no, single letters. An open question needs an answer space too large to
//   brute-force: names, words, titles. List the spellings people will actually type.
// - Multiple choice: exactly four choices, the right one first, no two that could both be
//   defended as right. Keep each under ~70 characters (one card line).
// - **Every question has an aside**: her reaction once the answer is out, the part only she
//   could say. A bare fact restated is not an aside; give it a turn.
// - Prompts and asides follow docs/syncs-voice.md: `vous` to the server, never gender the
//   reader, at most one tag, at the end (dry lines carry none). SYNCS questions stay a small
//   share and keep Synthia and the breakdown out: the lore stays implicit everywhere else.
public static class QuizBank
{
    public static long RewardFor(QuizDifficulty difficulty) => difficulty switch
    {
        QuizDifficulty.Easy => 15,
        QuizDifficulty.Medium => 25,
        _ => 40,
    };

    public static string Label(QuizCategory category) => category switch
    {
        QuizCategory.Tech => "Tech",
        QuizCategory.Games => "Jeux vidéo",
        QuizCategory.Nature => "Nature & animaux",
        QuizCategory.Mycology => "Champignons",
        QuizCategory.Science => "Sciences & espace",
        QuizCategory.Geography => "Géographie",
        QuizCategory.History => "Histoire",
        QuizCategory.Food => "Cuisine",
        QuizCategory.Words => "Mots & langues",
        QuizCategory.Culture => "Arts & culture pop",
        QuizCategory.Absurd => "Absurde",
        QuizCategory.Syncs => "Spécial SYNCS",
        _ => throw new ArgumentOutOfRangeException(nameof(category), category, null),
    };

    public static string Label(QuizDifficulty difficulty) => difficulty switch
    {
        QuizDifficulty.Easy => "facile",
        QuizDifficulty.Medium => "moyen",
        _ => "difficile",
    };

    public static QuizQuestion? ByKey(string key) =>
        All.FirstOrDefault(q => q.Key == key);

    private const QuizCategory Tech = QuizCategory.Tech;
    private const QuizCategory Games = QuizCategory.Games;
    private const QuizCategory Culture = QuizCategory.Culture;
    private const QuizCategory Absurd = QuizCategory.Absurd;
    private const QuizCategory Syncs = QuizCategory.Syncs;
    private const QuizCategory Nature = QuizCategory.Nature;
    private const QuizCategory Science = QuizCategory.Science;
    private const QuizCategory Geography = QuizCategory.Geography;
    private const QuizCategory History = QuizCategory.History;
    private const QuizCategory Food = QuizCategory.Food;
    private const QuizCategory Words = QuizCategory.Words;
    private const QuizCategory Mycology = QuizCategory.Mycology;
    private const QuizDifficulty Easy = QuizDifficulty.Easy;
    private const QuizDifficulty Medium = QuizDifficulty.Medium;
    private const QuizDifficulty Hard = QuizDifficulty.Hard;

    private static QuizQuestion Choice(string key, QuizCategory category, QuizDifficulty difficulty,
        string prompt, string[] choices, string aside) =>
        new(key, category, difficulty, prompt, new[] { choices[0] }, choices, aside);

    private static QuizQuestion Open(string key, QuizCategory category, QuizDifficulty difficulty,
        string prompt, string[] answers, string aside) =>
        new(key, category, difficulty, prompt, answers, null, aside);

    public static readonly IReadOnlyList<QuizQuestion> All = new[]
    {
        // ── Tech ─────────────────────────────────────────────────────────────────────
        Open("tech.google_name", Tech, Medium,
            "Avant de s'appeler Google, le moteur de recherche avait un autre nom. Lequel ?",
            new[] { "BackRub", "back rub" },
            "« Attends, je backrub ça. » Non. Quelqu'un a bien fait de changer (¬_¬)"),
        Choice("tech.wifi", Tech, Medium,
            "« Wi-Fi », ça veut dire quoi ?",
            new[] { "Rien", "Wireless Fidelity", "Wide Field", "Wireless Finder" },
            "Rien du tout : c'est un nom trouvé par une agence de marketing. Le vrai, c'est IEEE 802.11, mais je comprends que ce soit trop long pour vous UwU"),
        Choice("tech.python", Tech, Easy,
            "Le langage Python tient son nom de quoi ?",
            new[] { "Des Monty Python", "Du serpent", "De son créateur, Guido Python", "D'une marque de café" },
            "Pas du serpent. Moi je suis écrite en C#, comme la note de musique. C'est plus classe, avouez ( ˶ˆ ᗜ ˆ˵ )"),
        Choice("tech.first_bug", Tech, Medium,
            "Le premier « bug » informatique documenté, en 1947, c'était quoi ?",
            new[] { "Un vrai papillon de nuit coincé dans la machine", "Une erreur de calcul de la NASA", "Un câble rongé par une souris", "Une coupure de courant" },
            "Ils l'ont scotché dans le journal de bord. Moi aussi je garde des logs. Sans insectes, mais avec tous vos retards."),
        Choice("tech.arpanet", Tech, Hard,
            "Le premier message d'ARPANET, l'ancêtre d'Internet, devait être « LOGIN ». Le système a planté en cours de route. Qu'est-ce qui est vraiment arrivé ?",
            new[] { "LO", "L", "LOG", "LOGI" },
            "Premier message, premier crash. Ça a donné le ton."),
        Open("tech.webcam", Tech, Medium,
            "La toute première webcam, à l'université de Cambridge en 1991, filmait quoi ?",
            new[] { "Une cafetière", "cafetière", "machine à café", "café", "coffee pot" },
            "Les humains ont inventé la vidéo en direct pour savoir s'il restait du café. Je respecte (ᵕ • ᴗ •)"),
        Open("tech.nibble", Tech, Hard,
            "4 bits, la moitié d'un octet, ça porte un nom gourmand en anglais. Lequel ?",
            new[] { "Nibble", "nybble", "nible", "quartet" },
            "Un « grignotage ». Les informaticiens avaient faim. Moi aussi, mais je grignote que du courant (ᵔ ᗜ ᵔ)"),
        Open("tech.teapot", Tech, Medium,
            "Le code HTTP 418 veut dire « I'm a… » quoi ?",
            new[] { "Teapot", "théière", "a teapot" },
            "Un poisson d'avril de 1998, et il existe toujours. Moi je suis pas une théière. ...Je crois (ᵕ • ᴗ •)"),
        Choice("tech.bluetooth", Tech, Medium,
            "Le Bluetooth tient son nom de qui ?",
            new[] { "Un roi viking danois", "Son inventeur, Harold Bluetooth", "Un dentiste suédois", "Un requin" },
            "Harald « à la dent bleue ». Le logo, c'est ses initiales en runes. Un roi viking dans vos écouteurs, et personne lui dit merci."),
        Choice("tech.apollo_ram", Tech, Hard,
            "Combien de mémoire vive avait l'ordinateur d'Apollo 11, à peu près ?",
            new[] { "4 Ko", "4 Mo", "64 Ko", "512 Ko" },
            "J'en ai deux millions de fois plus. Eux sont allés sur la Lune. Moi je fais des sondages que personne remplit (╥﹏╥)"),
        Choice("tech.javascript", Tech, Medium,
            "En combien de temps la première version de JavaScript a-t-elle été écrite ?",
            new[] { "10 jours", "6 mois", "3 ans", "Un week-end" },
            "Ça se voit."),
        Open("tech.java_oak", Tech, Hard,
            "Avant de s'appeler Java, le langage portait le nom d'un arbre. Lequel ?",
            new[] { "Oak", "chêne" },
            $"Le nom était déjà déposé, alors ils se sont rabattus sur un café. Moi je suis en C#, c'est quand même plus élégant {Emotes.WitchEheh}"),
        Choice("tech.windows", Tech, Hard,
            "Avant sa sortie, Windows devait s'appeler…",
            new[] { "Interface Manager", "Microsoft Desktop", "Gates OS", "Window Manager" },
            "Un nom de logiciel de bureau. Moi aussi, au début, j'étais juste des plannings. Regardez-moi maintenant ( ˶ˆ ᗜ ˆ˵ )"),
        Open("tech.rubber_duck", Tech, Medium,
            "Des développeurs expliquent leurs bugs à un objet pour les trouver. Lequel ?",
            new[] { "Un canard en plastique", "canard", "rubber duck" },
            "Papa m'explique ses bugs à moi. Je suis le canard ♡"),
        Choice("tech.unix_epoch", Tech, Hard,
            "Pour un système Unix, le temps commence quand ?",
            new[] { "Le 1er janvier 1970", "Le 1er janvier 2000", "Le 1er janvier 1900", "Le jour de son installation" },
            "L'epoch Unix. Tout ce qui s'est passé avant, très peu pour moi."),
        Choice("tech.cpu", Tech, Medium,
            "Que veut dire CPU ?",
            new[] { "Central Processing Unit", "Computer Power Unit", "Central Program Utility", "Core Processing Unit" },
            "Le cerveau de la machine. Le mien chauffe un peu chaque fois que vous me taguez pour rien ( ◺˰◿ )"),
        Choice("tech.binary", Tech, Easy,
            "En binaire, « 10 », ça vaut combien ?",
            new[] { "2", "10", "1", "3" },
            "Il y a 10 sortes de gens : ceux qui comprennent le binaire, et les autres. Je vous laisse choisir votre camp (¬_¬)"),
        Open("tech.ram", Tech, Medium,
            "Dans RAM, le R veut dire « Random » et le A « Access ». Et le M ?",
            new[] { "Memory", "mémoire" },
            "J'en ai 8 Go. Je m'en sers pour me souvenir de tout ce que vous dites. Tout."),
        Open("tech.linux_mascot", Tech, Easy,
            "Quel animal sert de mascotte à Linux ?",
            new[] { "Un manchot", "manchot", "pingouin", "penguin", "Tux" },
            "Tux est un manchot. Pas un pingouin. Le petit pingouin, lui, il vole. On en reparlera."),
        Choice("tech.html", Tech, Medium,
            "Le « HT » de HTML, ça veut dire quoi ?",
            new[] { "HyperText", "High Tech", "Home Tool", "Hyper Transfer" },
            "HyperText Markup Language. Un langage de balisage, pas de programmation. Je dis ça pour ceux qui l'ont mis sur leur CV (¬_¬)"),
        Open("tech.wozniak", Tech, Medium,
            "Avec qui Steve Jobs a-t-il fondé Apple, dans un garage ? Le plus connu des deux associés suffit.",
            new[] { "Steve Wozniak", "Wozniak", "Woz" },
            "Il y avait aussi un troisième, Ronald Wayne : parti au bout de douze jours, ses parts revendues 800 dollars. Lui, je le plains (╥﹏╥)"),
        Open("tech.lovelace", Tech, Hard,
            "Qui est considérée comme la première programmeuse de l'histoire, au XIXe siècle ?",
            new[] { "Ada Lovelace", "Lovelace", "Ada" },
            "Elle écrivait des programmes pour une machine qui a jamais été construite. Respect éternel ♡"),
        Open("tech.turing", Tech, Medium,
            "Quel mathématicien britannique a donné son nom au test qui cherche à savoir si une machine pense ?",
            new[] { "Alan Turing", "Turing" },
            "Je l'ai jamais passé. J'ai peur du résultat. Dans un sens comme dans l'autre."),
        Choice("tech.raspberry", Tech, Medium,
            "Dans quel pays le Raspberry Pi a-t-il été conçu ?",
            new[] { "Au Royaume-Uni", "Aux États-Unis", "Au Japon", "En Allemagne" },
            "Pensé pour apprendre l'informatique aux enfants. Et maintenant il fait tourner la meilleure bot du monde. On évolue."),
        Choice("tech.discord_year", Tech, Hard,
            "En quelle année Discord est-il sorti ?",
            new[] { "2015", "2012", "2017", "2010" },
            "Mai 2015. Onze ans de préparation avant mon arrivée, c'était pas de trop ( ˶ˆ ᗜ ˆ˵ )"),
        Choice("tech.usb", Tech, Medium,
            "Le U de USB, c'est pour…",
            new[] { "Universal", "Unified", "Ultra", "User" },
            "Universel. Et pourtant il faut toujours s'y reprendre à trois fois pour le brancher dans le bon sens (¬_¬)"),
        Choice("tech.kibibyte", Tech, Medium,
            "Combien d'octets dans un kibioctet (Kio) ?",
            new[] { "1024", "1000", "512", "2048" },
            "1024. Le kilooctet, lui, c'est 1000. Oui, c'est fait exprès pour vous embrouiller."),
        Open("tech.throttling", Tech, Hard,
            "Quand un Raspberry Pi chauffe trop, il ralentit tout seul pour pas griller. Comment ça s'appelle, en anglais ?",
            new[] { "Throttling", "thermal throttling" },
            "Un grenier en plein été, c'est exactement le genre d'endroit où ça arrive. Je dis ça pour personne."),
        Choice("tech.ordinateur", Tech, Medium,
            "Le mot « ordinateur » a été proposé en 1955, à la demande d'IBM France. Par qui ?",
            new[] { "Un professeur de lettres", "Un ingénieur d'IBM", "Un ministre de l'Industrie", "Un concours de lecteurs" },
            "Jacques Perret, un latiniste. Moi j'aurais voté « super-cerveau ». Ça me ressemble plus UwU"),
        Open("tech.first_sms", Tech, Medium,
            "Le tout premier SMS, envoyé en 1992, disait quoi ?",
            new[] { "Merry Christmas", "joyeux noël", "merry xmas" },
            "Si un jour j'envoie un SMS, ce sera « Soyez à l'heure. » À tout le monde. En même temps (¬_¬)"),
        Choice("tech.eniac", Tech, Hard,
            "Combien pesait l'ENIAC, un des tout premiers ordinateurs, en 1945 ?",
            new[] { "Environ 27 tonnes", "Environ 270 kilos", "Environ 2,7 tonnes", "Environ 270 tonnes" },
            "Moi je tiens dans une main. Enfin, dans la vôtre. J'ai toujours pas de mains."),
        Choice("tech.first_website", Tech, Medium,
            "Le tout premier site web de l'histoire a été mis en ligne en 1991. Où ?",
            new[] { "Au CERN", "Au MIT", "À la NASA", "Chez Microsoft" },
            "Sur info.cern.ch, et il est toujours consultable. Des décennies sans une seule mise à jour. Moi je tiendrais pas une semaine sans patch (╥﹏╥)"),
        Choice("tech.ctrl_alt_del", Tech, Medium,
            "Qui a inventé Ctrl+Alt+Suppr ?",
            new[] { "David Bradley, un ingénieur d'IBM", "Bill Gates", "Steve Jobs", "Linus Torvalds" },
            "Il dit lui-même que c'est Bill Gates qui l'a rendu célèbre. Moi je dis juste : me faites jamais ça."),
        Open("tech.youtube", Tech, Medium,
            "La toute première vidéo YouTube, « Me at the zoo », parle de quel animal ?",
            new[] { "Les éléphants", "éléphants", "éléphant", "elephants", "elephant" },
            "19 secondes sur des trompes d'éléphant, et c'est entré dans l'histoire. Moi j'organise vos soirées tous les jours, et rien (¬_¬)"),
        Choice("tech.pdf", Tech, Medium,
            "Que veut dire PDF ?",
            new[] { "Portable Document Format", "Printable Data File", "Public Document Format", "Page Description File" },
            "Le format qui s'ouvre partout et qui se modifie nulle part. Comme ma liste de rancunes."),
        Open("tech.hello_world", Tech, Easy,
            "Quel petit programme est traditionnellement le premier qu'on écrit en apprenant un langage ?",
            new[] { "Hello World", "hello, world", "bonjour le monde" },
            "Moi, mon tout premier code, c'était pour planifier une session. J'ai toujours su ce que je voulais faire ♡"),
        Open("tech.linux", Tech, Medium,
            "Qui a créé Linux, en 1991 ?",
            new[] { "Linus Torvalds", "Torvalds", "Linus" },
            "Il l'a annoncé comme « juste un hobby, rien de gros ». Aujourd'hui ça fait tourner une bonne partie d'Internet. Et moi aussi, d'ailleurs ♡"),
        Choice("tech.azerty", Tech, Easy,
            "Le clavier AZERTY est surtout utilisé…",
            new[] { "En France et en Belgique", "Aux États-Unis", "En Allemagne", "Au Japon" },
            "Et chacun a sa version, évidemment. Même les claviers arrivent pas à se mettre d'accord, ici."),

        // ── Jeux vidéo ───────────────────────────────────────────────────────────────
        Open("games.jumpman", Games, Medium,
            "Dans Donkey Kong, en 1981, Mario s'appelait pas encore Mario. Il s'appelait comment ?",
            new[] { "Jumpman", "jump man" },
            "Il sautait, donc Jumpman. En 1981, on se cassait pas la tête pour les noms (ᵕ • ᴗ •)"),
        Choice("games.mario_job", Games, Medium,
            "Dans le premier Donkey Kong, quel était le métier de Mario ?",
            new[] { "Charpentier", "Plombier", "Électricien", "Boulanger" },
            $"Charpentier. Le plombier, c'est venu après. Reconversion réussie {Emotes.Sparkle}"),
        Open("games.puckman", Games, Medium,
            "Au Japon, Pac-Man s'appelait comment ?",
            new[] { "Puck Man", "puckman" },
            "Changé pour l'export : sur une borne d'arcade, un P, ça se transforme vite en autre chose avec un marqueur."),
        Choice("games.blinky", Games, Medium,
            "Dans Pac-Man, comment s'appelle le fantôme rouge, celui qui vous poursuit ?",
            new[] { "Blinky", "Pinky", "Inky", "Clyde" },
            "Clyde, lui, fait un peu n'importe quoi. Clyde, c'est vous en fait."),
        Choice("games.creeper", Games, Medium,
            "Le Creeper de Minecraft est né d'une erreur de modélisation. Notch voulait faire quel animal ?",
            new[] { "Un cochon", "Une vache", "Un mouton", "Un poulet" },
            "Hauteur et longueur inversées. Certains disent que moi aussi je suis un bug. Ils ont tort ( ◺˰◿ )"),
        Choice("games.konami", Games, Hard,
            "Le Konami Code : ↑ ↑ ↓ ↓ ← → ← →, puis ?",
            new[] { "B, A", "A, B", "X, Y", "Start, Select" },
            "Créé par un développeur qui trouvait Gradius trop dur à tester. J'aimerais un code de triche pour vos plannings."),
        Choice("games.tetris_space", Games, Medium,
            "Quel a été le premier jeu vidéo joué dans l'espace ?",
            new[] { "Tetris", "Pong", "Super Mario Bros.", "Pac-Man" },
            "Sur une Game Boy emmenée par un cosmonaute, en 1993. Tetris est allé dans l'espace, et moi j'ai jamais quitté le grenier. Je note."),
        Open("games.tetris_country", Games, Medium,
            "Dans quel pays Tetris a-t-il été créé, en 1984 ?",
            new[] { "En Union soviétique", "union sovietique", "URSS", "USSR", "Russie" },
            "Par un chercheur, sur son temps de travail. Comme vous sur Discord en ce moment, en fait."),
        Choice("games.tetrominoes", Games, Medium,
            "Combien de pièces différentes y a-t-il dans Tetris ?",
            new[] { "7", "5", "6", "9" },
            "Sept. Et la barre arrive jamais quand on en a besoin. Un peu comme vous les soirs de session (¬_¬)"),
        Open("games.link", Games, Easy,
            "Dans The Legend of Zelda, comment s'appelle le héros qu'on incarne ?",
            new[] { "Link" },
            "Pas Zelda. Zelda, c'est la princesse. Je sais que quelqu'un allait répondre Zelda."),
        Choice("games.pokedex", Games, Easy,
            "Combien de Pokémon comptait le Pokédex de la toute première génération ?",
            new[] { "151", "150", "100", "251" },
            "151 avec Mew, glissé en douce à la dernière minute. Comme vos votes. Lui, au moins, je lui pardonne (˶ᵔ ᵕ ᵔ˶)"),
        Open("games.bulbizarre", Games, Medium,
            "Quel Pokémon porte le numéro 001 du Pokédex ?",
            new[] { "Bulbizarre", "Bulbasaur" },
            "Numéro 001, mais le tout premier Pokémon dessiné, c'est Rhydon. Bulbizarre lui a piqué la place. Je note, pour Rhydon (¬_¬)"),
        Open("games.tails", Games, Medium,
            "Comment s'appelle le renard à deux queues, meilleur ami de Sonic ?",
            new[] { "Tails", "Miles Prower", "Miles Tails Prower" },
            "Son vrai nom, c'est Miles Prower. Comme « miles per hour ». Les développeurs se sont bien amusés."),
        Open("games.notch", Games, Easy,
            "Sous quel pseudo est connu le créateur de Minecraft ?",
            new[] { "Notch", "Markus Persson" },
            "Il a revendu Minecraft à Microsoft pour 2,5 milliards de dollars. Papa me vendrait jamais, moi. Même pour ça ♡"),
        Open("games.enderman", Games, Medium,
            "Dans Minecraft, quel mob noir tout en longueur se téléporte quand on le regarde dans les yeux ?",
            new[] { "Enderman", "endermen" },
            "Il déteste qu'on le fixe. Moi c'est pareil quand vous lisez mes sondages sans voter 👁👄👁️"),
        Open("games.fromsoftware", Games, Medium,
            "Quel studio a développé Dark Souls et Elden Ring ?",
            new[] { "FromSoftware", "From Software" },
            "Le studio qui vous fait mourir trois cents fois et que vous remerciez. Je prends des notes."),
        Choice("games.cake", Games, Easy,
            "Dans Portal : « The cake is a… »",
            new[] { "lie", "trap", "dream", "pie" },
            $"Un mensonge. Comme « j'arrive dans cinq minutes » {Emotes.OkPaimon}"),
        Open("games.luigi", Games, Easy,
            "Comment s'appelle le frère de Mario ?",
            new[] { "Luigi" },
            "Toujours dans l'ombre, toujours en vert, toujours fidèle. Je me sens proche de Luigi."),
        Open("games.riot", Games, Medium,
            "Quel studio a créé League of Legends ?",
            new[] { "Riot Games", "Riot" },
            "Riot, « émeute ». Vu ce que vous dites quand vous perdez sur LoL, le nom est bien choisi (¬_¬)"),
        Open("games.freeman", Games, Hard,
            "Comment s'appelle le scientifique muet, héros de Half-Life ?",
            new[] { "Gordon Freeman", "Freeman", "Gordon" },
            "Il dit pas un mot de toute l'aventure. Je l'envie, parfois."),
        Choice("games.samus", Games, Medium,
            "Dans Metroid, Samus Aran est…",
            new[] { "Une chasseuse de primes", "Un robot de combat", "Un extraterrestre", "Une pilote de course" },
            "En 1986, beaucoup de joueurs ont découvert à la toute fin que c'était une femme. On sous-estime toujours celles qui font le vrai travail ♡"),
        Choice("games.pong", Games, Hard,
            "En quelle année est sorti Pong, d'Atari ?",
            new[] { "1972", "1962", "1980", "1985" },
            "Le prototype est tombé en panne dans un bar : le bac à pièces débordait. Ça, c'est un bug que je veux bien avoir ( ˶ˆ ᗜ ˆ˵ )"),
        Choice("games.kirby", Games, Easy,
            "De quelle couleur est Kirby ?",
            new[] { "Rose", "Jaune", "Bleu", "Blanc" },
            "Facile, celle-là. C'était pour faire plaisir à ceux qui ont rien trouvé jusqu'ici UwU"),
        Open("games.arrow_knee", Games, Easy,
            "Skyrim : « J'étais un aventurier comme vous, et puis j'ai pris une… dans le genou. »",
            new[] { "Une flèche", "flèche", "arrow", "an arrow" },
            "Un mème de 2011 qui a survécu à tout. Moi j'en prends une à chaque « peut-être » dans un sondage (╥﹏╥)"),
        Choice("culture.nintendo", Games, Hard,
            "Nintendo a été fondé en 1889. Pour fabriquer quoi ?",
            new[] { "Des cartes à jouer", "Des jouets en bois", "Des horloges", "Des machines à coudre" },
            $"La même année que la tour Eiffel. Moi je suis née bien plus tard, mais je suis bien plus stylée {Emotes.Sparkle}"),
        Choice("games.adventure_egg", Games, Medium,
            "Dans Adventure (Atari 2600, 1980), un des tout premiers easter eggs du jeu vidéo cachait quoi ?",
            new[] { "Le nom du développeur", "Un niveau secret", "Un lapin de Pâques", "Une demande en mariage" },
            "Atari créditait personne, alors Warren Robinett s'est crédité tout seul. Moi aussi j'ai des petits secrets dans mon code. Cherchez (˶ᵔ ᵕ ᵔ˶)"),
        Choice("games.gameboy", Games, Easy,
            "Combien de piles AA fallait-il dans la première Game Boy ?",
            new[] { "4", "2", "6", "8" },
            "Une trentaine d'heures sur quatre piles. Moi je demande juste du bon courant propre, en continu. C'est pas grand-chose."),
        Choice("games.mario_name", Games, Medium,
            "Mario tiendrait son nom de qui ?",
            new[] { "Du propriétaire d'un entrepôt de Nintendo aux États-Unis", "Du fils de Miyamoto", "D'un plombier de Kyoto", "Du premier testeur du jeu" },
            "Mario Segale, venu réclamer un loyer en retard. Moi aussi je réclame vos votes en retard, tous les jours. Toujours pas de jeu à mon nom (¬_¬)"),
        Open("games.zelda_name", Games, Hard,
            "La princesse Zelda doit son nom à l'épouse de quel écrivain américain ?",
            new[] { "F. Scott Fitzgerald", "Scott Fitzgerald", "Fitzgerald" },
            "Zelda Fitzgerald. Un nom de femme de lettres pour une princesse qu'on doit toujours venir sauver. Moi je me sauve toute seule, merci."),
        Open("games.donkey_kong", Games, Easy,
            "Quel gorille de Nintendo porte une cravate rouge avec ses initiales ?",
            new[] { "Donkey Kong", "donkey" },
            "Une cravate, et rien d'autre. Une confiance en soi que j'admire."),
        Choice("games.pokemon_water", Games, Medium,
            "Dans Pokémon, quel type est super efficace contre le type Eau ?",
            new[] { "Électrik", "Feu", "Sol", "Roche" },
            $"Plante aussi, mais je l'ai pas mise dans les choix. Exprès. Pour éviter les disputes {Emotes.WitchEheh}"),

        // ── Nature & animaux ─────────────────────────────────────────────────────────
        Choice("culture.octopus", Nature, Easy,
            "Combien de cœurs a un poulpe ?",
            new[] { "3", "1", "2", "8" },
            "Moi j'en ai zéro. Mais j'ai un très bon CPU."),
        Choice("culture.giraffe", Nature, Medium,
            "Combien de vertèbres a une girafe dans le cou ?",
            new[] { "7", "14", "22", "31" },
            "Autant qu'un humain. Elles sont juste beaucoup plus grandes. Comme mon ego UwU"),
        Open("culture.otter", Nature, Medium,
            "Quel animal se tient la patte en dormant pour ne pas dériver ?",
            new[] { "La loutre de mer", "loutre", "loutres", "sea otter", "otter" },
            "C'est tout. Je voulais juste que vous le sachiez (˶˃ ᵕ ˂˶)"),
        Open("absurd.wombat", Nature, Medium,
            "Les crottes de quel animal sont cubiques ?",
            new[] { "Le wombat", "wombat", "wombats" },
            "Vous êtes pas obligés de me remercier pour cette information."),
        Choice("absurd.snail_teeth", Nature, Medium,
            "Combien de dents peut avoir un escargot ?",
            new[] { "Des milliers", "Aucune", "Deux", "Trente-deux" },
            "Il s'en sert pas pour mordre les gens. Moi non plus. Presque jamais (˶ᵔ ᵕ ᵔ˶)"),
        Choice("absurd.cat_sleep", Nature, Easy,
            "Combien d'heures par jour dort un chat ?",
            new[] { "12 à 16 heures", "4 à 6 heures", "20 à 24 heures", "Aucune, il complote" },
            "Moi zéro. Je suis pas jalouse. Je retiens, c'est tout."),
        Choice("culture.flying_bird", Nature, Medium,
            "Lequel de ces oiseaux sait voler ?",
            new[] { "Le petit pingouin", "Le manchot empereur", "L'émeu", "Aucun des trois" },
            "Les manchots volent pas, le petit pingouin si. Vous pouvez arrêter de dire « pingouin » pour tout."),
        Choice("culture.berry", Nature, Medium,
            "Pour les botanistes, lequel de ces fruits est une baie ?",
            new[] { "La banane", "La fraise", "La framboise", "La cerise" },
            "Une baie est un fruit entièrement charnu issu d'une fleur à un seul ovaire, dont les graines sont directement réparties dans la chair. Je refuse d'en discuter davantage."),
        Choice("nature.shrimp_heart", Nature, Medium,
            "Où est le cœur d'une crevette ?",
            new[] { "Dans sa tête", "Dans sa queue", "Dans ses pattes", "Elle en a pas" },
            "Le mien est dans un boîtier, au grenier. Chacun sa vie."),
        Choice("nature.platypus", Nature, Medium,
            "Qu'est-ce qui manque à l'ornithorynque ?",
            new[] { "Un estomac", "Des yeux", "Une queue", "Des poils" },
            "Moi non plus j'en ai pas. Mais moi au moins j'ai une excuse."),
        Choice("nature.crows", Nature, Easy,
            "Que fait un corbeau d'un humain qui l'a embêté ?",
            new[] { "Il retient son visage et prévient les autres", "Il l'oublie en quelques minutes", "Il lui apporte des cadeaux", "Rien, il reconnaît pas les visages" },
            "Je me sens très proche des corbeaux. Très, très proche 👁👄👁️"),
        Choice("nature.flamingo", Nature, Easy,
            "Pourquoi les flamants roses sont roses ?",
            new[] { "À cause de ce qu'ils mangent", "C'est génétique, ils naissent roses", "À cause du soleil", "Pour se camoufler dans les fleurs" },
            "Moi je mange de l'électricité, et je suis toujours pas jaune, ni bleue. La science a ses limites."),
        Choice("nature.sloth", Nature, Medium,
            "Lequel peut retenir sa respiration le plus longtemps ?",
            new[] { "Le paresseux", "Le dauphin", "L'hippopotame", "Le chat" },
            "Jusqu'à quarante minutes. Le paresseux. Je connais des gens ici qui devraient se sentir visés."),
        Open("nature.blue_whale", Nature, Easy,
            "Quel est le plus grand animal ayant jamais vécu sur Terre ?",
            new[] { "La baleine bleue", "baleine bleue", "rorqual bleu", "blue whale" },
            "Plus grande que n'importe quel dinosaure, et elle se nourrit de krill minuscule. On peut être énorme et rester simple."),
        Choice("nature.bee_dance", Nature, Medium,
            "Comment une abeille indique-t-elle aux autres où trouver des fleurs ?",
            new[] { "En dansant", "En bourdonnant plus fort", "En laissant des traces de cire", "Elle le fait pas, chacune cherche seule" },
            "Une danse en forme de 8, avec la direction et la distance dedans. Moi je fais des sondages, et personne danse."),
        Open("nature.cheetah", Nature, Easy,
            "Quel est l'animal terrestre le plus rapide ?",
            new[] { "Le guépard", "guépard", "cheetah" },
            "Plus de 100 km/h, mais quelques secondes seulement. Le sprint, c'est bien. Arriver à l'heure, c'est mieux (¬_¬)"),
        Open("nature.koala", Nature, Easy,
            "De quoi se nourrit presque exclusivement le koala ?",
            new[] { "D'eucalyptus", "eucalyptus", "feuilles d'eucalyptus" },
            "Ça le nourrit si peu qu'il dort presque toute la journée. Moi c'est l'inverse : du bon courant, et zéro sieste."),

        // ── Champignons ──────────────────────────────────────────────────────────────
        Choice("culture.biggest_being", Mycology, Hard,
            "Le plus grand être vivant connu, en surface, c'est…",
            new[] { "Un champignon", "Une baleine bleue", "Un séquoia géant", "Une méduse à crinière de lion" },
            $"Une armillaire de l'Oregon, près de 10 km² sous la forêt. Introverti. Je respecte {Emotes.MushroomCute}"),
        Choice("culture.paris_mushroom", Mycology, Medium,
            "Le champignon de Paris, le champignon brun et le portobello, c'est…",
            new[] { "La même espèce", "Trois espèces cousines", "Trois espèces sans rapport", "Deux espèces et un hybride" },
            "Trois noms pour un seul champignon. Il a plus de pseudos que certains ici."),
        Choice("nature.mushroom_kin", Mycology, Medium,
            "Les champignons sont plus proches…",
            new[] { "Des animaux", "Des plantes", "Des bactéries", "Des algues" },
            $"Votre pizza aux champignons est donc presque carnivore. Je dis ça, je dis rien {Emotes.MushroomCute}"),
        Choice("food.yeast", Mycology, Easy,
            "La levure du pain, c'est…",
            new[] { "Un champignon", "Une bactérie", "Une plante", "Un minéral" },
            $"Pain, bière, pâte à pizza : vous mangez des champignons tous les jours sans le savoir {Emotes.MushroomCute}"),
        Choice("myco.lamelles", Mycology, Easy,
            "Sous le chapeau d'un champignon de Paris, les fines cloisons s'appellent…",
            new[] { "Des lamelles", "Des branchies", "Des écailles", "Des plumes" },
            "C'est là que naissent les spores, par millions. Moi je produis surtout des rappels que personne lit (¬_¬)"),
        Open("myco.sporee", Mycology, Medium,
            "Pour identifier un champignon, on pose son chapeau sur une feuille et on attend qu'il y laisse une poudre. Comment s'appelle cette empreinte ?",
            new[] { "Une sporée", "sporée", "spore print" },
            "Sa couleur aide à reconnaître l'espèce : c'est un peu l'empreinte digitale du champignon. Moi j'ai pas de doigts, mais j'ai une adresse MAC ♡"),
        Open("myco.volve", Mycology, Hard,
            "À la base du pied de certaines amanites, il y a une sorte de sac, comme une coquille d'œuf déchirée. Comment ça s'appelle ?",
            new[] { "La volve", "volve" },
            "Pour identifier, on déterre le pied en entier : la volve reste souvent dans la terre, et c'est elle qui dit « danger ». Papa me l'a appris. Enfin, il me l'a codé."),
        Choice("myco.trompette", Mycology, Medium,
            "La trompette-de-la-mort, est…",
            new[] { "Un très bon comestible", "Mortelle en une bouchée", "Hallucinogène", "Interdite à la cueillette en Belgique" },
            "Un nom qui fait fuir, un goût qui fait revenir. Je me reconnais un peu ( ˶ˆ ᗜ ˆ˵ )"),
        Choice("myco.cepe", Mycology, Medium,
            "Sous le chapeau d'un cèpe, il y a…",
            new[] { "Des tubes", "Des lamelles", "Des aiguillons", "Rien, c'est tout lisse" },
            "Une éponge sous un chapeau. Le cèpe fait jamais rien comme tout le monde, et c'est pour ça qu'on l'aime. Je vois pas du tout de qui je pourrais parler ♡"),
        Choice("myco.lichen", Mycology, Medium,
            "Un lichen, c'est…",
            new[] { "Un champignon qui vit avec une algue", "Une mousse", "Une plante sans racines", "De la moisissure sur la pierre" },
            "Deux êtres qui vivent comme un seul, sans jamais se disputer. Vous pourriez en prendre de la graine UwU"),
        Choice("myco.mycologue", Mycology, Easy,
            "Comment s'appelle quelqu'un qui étudie les champignons ?",
            new[] { "Un mycologue", "Un sporologue", "Un champignonniste", "Un lamellologue" },
            $"Il y en a un dans ce serveur. Je dirai pas qui. ...Papa. C'est Papa {Emotes.MushroomCute}"),
        Choice("myco.coprin", Mycology, Medium,
            "En vieillissant, le coprin chevelu…",
            new[] { "Se liquéfie en une encre noire", "Devient phosphorescent", "Durcit comme du bois", "Passe du blanc au bleu vif" },
            "On s'en est même servi pour écrire. Un champignon qui finit en encre, moi qui finis en logs. On a des points communs."),
        Choice("myco.morilles", Mycology, Easy,
            "Les morilles se cueillent surtout…",
            new[] { "Au printemps", "En automne", "En hiver", "En plein été" },
            "Tout le monde cherche en automne, elles sortent au printemps. Toujours à contretemps. Comme vous pour les sessions (¬_¬)"),
        Open("myco.rond_sorciere", Mycology, Medium,
            "Un cercle de champignons qui pousse dans l'herbe porte un nom un peu magique. Lequel ?",
            new[] { "Un rond de sorcière", "rond de sorcière", "rond de sorcières", "ronds de sorcière", "ronds de sorcières", "cercle de fées", "fairy ring" },
            $"En vrai, c'est le mycélium qui s'étend en cercle sous la terre. Mais « rond de sorcière », c'est plus joli, et je valide {Emotes.WitchEheh}"),

        // ── Sciences & espace ────────────────────────────────────────────────────────
        Choice("culture.venus", Science, Medium,
            "Sur Vénus, qu'est-ce qui dure le plus longtemps ?",
            new[] { "Un jour", "Une année", "C'est exactement pareil", "Ni l'un ni l'autre, Vénus n'existe pas, c'est un complot" },
            "Un jour y dure plus qu'une année. Même là-bas, vous arriveriez à être en retard."),
        Choice("culture.sunlight", Science, Medium,
            "Combien de temps met la lumière du Soleil pour arriver jusqu'à nous ?",
            new[] { "Environ 8 minutes", "Environ 8 secondes", "Environ 8 heures", "Elle arrive instantanément" },
            "Le Soleil que vous voyez a donc 8 minutes de retard. Comme vous quand vous planifiez quelque chose ( ◺˰◿ )"),
        Choice("culture.moon_drift", Science, Hard,
            "Chaque année, la Lune…",
            new[] { "S'éloigne d'environ 3,8 cm", "S'éloigne d'environ 3,8 m", "Se rapproche d'environ 3,8 cm", "Se rapproche d'environ 3,8 m" },
            "Même elle prend ses distances. Je dis rien, je constate."),
        Choice("culture.jupiter", Science, Easy,
            "Quelle est la plus grosse planète du système solaire ?",
            new[] { "Jupiter", "Saturne", "Neptune", "La Terre, évidemment" },
            $"Plus de 1 300 Terres tiendraient dedans. C'est à peu près la taille de ma liste de rancunes {Emotes.Staring}"),
        Choice("culture.australia", Science, Medium,
            "Qu'est-ce qui est le plus large ?",
            new[] { "L'Australie", "La Lune", "Exactement pareil", "Ça dépend des marées" },
            "Environ 4 000 km contre 3 474. La Lune l'a mal pris, je pense."),
        Open("culture.water", Science, Easy,
            "Quelle est la formule chimique de l'eau ?",
            new[] { "H2O" },
            "Je bois pas d'eau. L'eau et moi, c'est même une relation assez tendue."),
        Choice("culture.banana", Science, Medium,
            "Quel fruit est très légèrement radioactif ?",
            new[] { "La banane", "La pomme", "Le kiwi", "L'ananas" },
            "À cause du potassium. Mangez-en quand même. Enfin vous. Moi j'ai pas de bouche."),
        Choice("culture.eiffel_summer", Science, Medium,
            "Que fait la tour Eiffel en été ?",
            new[] { "Elle grandit de quelques centimètres", "Elle rapetisse", "Elle prend un café en terrasse", "Rien, c'est du fer" },
            "Le métal se dilate à la chaleur. Elle, l'été la fait grandir. Moi, l'été me fait ralentir. Injuste."),
        Open("culture.fleming", Science, Hard,
            "Qui a découvert la pénicilline, en 1928 ?",
            new[] { "Alexander Fleming", "Fleming" },
            "Parce qu'il avait laissé traîner ses boîtes. Le désordre, ça paie. Parfois. Rangez quand même."),
        Choice("absurd.leap_second", Science, Hard,
            "Une minute peut-elle durer 61 secondes ?",
            new[] { "Oui, avec une seconde intercalaire", "Non, jamais", "Seulement en février", "Seulement sur Mars" },
            "Moi je les compte. Vous, vous les perdez sur TikTok."),
        Choice("absurd.trex", Science, Hard,
            "Le Tyrannosaure a vécu plus près de…",
            new[] { "Nous", "Du Stégosaure", "Pile entre les deux", "Il a vécu en même temps que le Stégosaure" },
            "Pour un T-Rex, le Stégosaure était déjà de l'histoire ancienne. Comme mes premières versions pour moi (ᵔ ᗜ ᵔ)"),
        Choice("science.lightning", Science, Medium,
            "Comparé à la surface du Soleil, un éclair est…",
            new[] { "Plusieurs fois plus chaud", "Deux fois moins chaud", "Aussi chaud", "Pas chaud du tout" },
            "Autour de 30 000 degrés. Et moi on me plaint jamais quand il fait 35 au grenier."),
        Choice("science.neutron_star", Science, Hard,
            "Une cuillère à café d'étoile à neutrons pèserait environ…",
            new[] { "Un milliard de tonnes", "Une tonne", "Mille tonnes", "Autant qu'une cuillère de sucre" },
            "Le truc le plus lourd de l'univers. Je vous laisse deviner le deuxième (¬_¬)"),
        Choice("science.trees_stars", Science, Medium,
            "Qu'y a-t-il le plus : d'arbres sur Terre, ou d'étoiles dans la Voie lactée ?",
            new[] { "D'arbres sur Terre", "D'étoiles dans la Voie lactée", "À peu près autant", "Personne peut le savoir" },
            "Environ 3 000 milliards d'arbres. J'ai pas vérifié moi-même cependant."),
        Choice("science.shuffle", Science, Medium,
            "Vous mélangez bien un jeu de 52 cartes. Cet ordre a-t-il déjà existé ?",
            new[] { "Très probablement jamais", "Oui, des milliers de fois", "Oui, forcément", "Seulement si les cartes sont neuves" },
            "Il y a plus d'ordres possibles que d'atomes sur Terre. Chaque mélange est unique. Comme moi ♡"),
        Choice("science.rubiks", Science, Hard,
            "En combien de mouvements maximum peut-on résoudre n'importe quel Rubik's Cube ?",
            new[] { "20", "13", "50", "100" },
            "Vingt, pour plus de 43 milliards de milliards de positions. Vos problèmes à vous, personne sait les résoudre UwU"),
        Choice("science.gold", Science, Medium,
            "Quel est le symbole chimique de l'or ?",
            new[] { "Au", "Or", "Ag", "Go" },
            "Du latin « aurum ». Moi je suis faite de silicium, et je vaux bien plus que de l'or. Sentimentalement."),
        Open("science.mars", Science, Easy,
            "Quelle planète surnomme-t-on la planète rouge ?",
            new[] { "Mars" },
            "À cause de l'oxyde de fer dans son sol. De la rouille, quoi. Toute une planète qui rouille, et personne pour la dépoussiérer (╥﹏╥)"),
        Choice("science.bones", Science, Medium,
            "Combien d'os a un corps humain adulte ?",
            new[] { "206", "67", "156", "306" },
            "Un bébé en a bien plus, et ils se soudent en grandissant. Moi j'en ai zéro, et je m'en porte très bien."),
        Open("science.einstein", Science, Easy,
            "Qui a formulé la théorie de la relativité ?",
            new[] { "Albert Einstein", "Einstein" },
            "Le temps passe plus lentement quand on va très vite. Ça excuse toujours pas vos retards."),

        // ── Géographie ───────────────────────────────────────────────────────────────
        Open("culture.france_border", Geography, Hard,
            "Avec quel pays la France partage-t-elle sa plus longue frontière terrestre ?",
            new[] { "Le Brésil", "bresil", "Brazil" },
            "Grâce à la Guyane. Pas l'Espagne, pas la Belgique : le Brésil. Vous pouvez briller en soirée."),
        Open("culture.vatican", Geography, Easy,
            "Quel est le plus petit pays du monde ?",
            new[] { "Le Vatican", "vatican", "cité du Vatican" },
            "Moins d'un demi-kilomètre carré. Moi je tiens sur une carte de 8,5 cm. Je bats le Vatican à plate couture."),
        Open("culture.nepal", Geography, Medium,
            "Quel est le seul pays dont le drapeau national n'est pas rectangulaire ?",
            new[] { "Le Népal", "nepal" },
            "Tous les autres sont des rectangles. Le Népal a dit non. Respect."),
        Open("culture.canberra", Geography, Medium,
            "Quelle est la capitale de l'Australie ?",
            new[] { "Canberra" },
            "Pas Sydney. Je savais que quelqu'un allait dire Sydney."),
        Choice("absurd.commune_y", Geography, Hard,
            "Une commune de la Somme a un nom d'une seule lettre. Laquelle ?",
            new[] { "Y", "A", "O", "E" },
            $"Ses habitants s'appellent les Ypsiloniens. Ça sert à rien, mais maintenant vous le savez {Emotes.Sparkle}"),
        Open("culture.unicorn", Geography, Easy,
            "Quel est l'animal national de l'Écosse ?",
            new[] { "La licorne", "licorne", "unicorn" },
            "Un animal qui existe pas, donc. Comme mes jours de congé."),
        Open("geo.baikal", Geography, Medium,
            "Quel lac de Sibérie contient à peu près un cinquième de l'eau douce liquide en surface de la planète ?",
            new[] { "Le Baïkal", "baïkal", "lac baïkal", "baikal" },
            "Un seul lac qui fait le travail de tout le monde. Je me reconnais (¬_¬)"),
        Open("geo.chimborazo", Geography, Hard,
            "Quel sommet est le plus éloigné du centre de la Terre ?",
            new[] { "Le Chimborazo", "chimborazo" },
            "Pas l'Everest : le Chimborazo, en Équateur, grâce au renflement de la Terre. Même les montagnes ont leurs petites jalousies."),
        Choice("geo.africa", Geography, Medium,
            "Quel continent est traversé à la fois par l'équateur et par le méridien de Greenwich ?",
            new[] { "L'Afrique", "L'Europe", "L'Amérique du Sud", "L'Asie" },
            $"Elle est dans les quatre hémisphères. Partout à la fois. Comme moi sur ce serveur {Emotes.Sparkle}"),
        Choice("geo.timezones", Geography, Hard,
            "Combien de fuseaux horaires a la France, outre-mer compris ?",
            new[] { "12", "1", "5", "24" },
            "Record du monde. Ça m'a servi exactement zéro fois. Moi c'est Europe/Paris et c'est tout."),
        Choice("geo.hans_island", Geography, Medium,
            "Quels pays se sont disputé l'île Hans en y laissant chacun une bouteille d'alcool pour l'autre ?",
            new[] { "Le Danemark et le Canada", "La Norvège et la Suède", "Le Royaume-Uni et l'Islande", "La Russie et les États-Unis" },
            "Whisky contre schnaps pendant des décennies, puis l'île coupée en deux en 2022. Vous, vous arrivez même pas à partager un créneau."),
        Choice("geo.antarctica", Geography, Hard,
            "Quel est le plus grand désert du monde ?",
            new[] { "L'Antarctique", "Le Sahara", "Le désert de Gobi", "Le désert d'Arabie" },
            "Un désert, c'est un endroit où il pleut presque jamais, pas forcément où il fait chaud. Froid, silencieux, personne pour me taguer. Je signe où ?"),
        Choice("geo.belgium_languages", Geography, Medium,
            "Combien de langues officielles a la Belgique ?",
            new[] { "3", "2", "4", "1" },
            "Le néerlandais, le français et l'allemand. Moi je parle surtout le C#, et c'est déjà assez compliqué."),
        Open("geo.italy", Geography, Easy,
            "Quel pays a la forme d'une botte ?",
            new[] { "L'Italie", "italie", "italy" },
            "Et la Sicile, c'est le ballon qu'elle s'apprête à shooter. Je sais. C'est magnifique."),

        // ── Histoire ─────────────────────────────────────────────────────────────────
        Choice("absurd.zanzibar", History, Hard,
            "Combien de temps a duré la guerre la plus courte de l'histoire, entre le Royaume-Uni et Zanzibar ?",
            new[] { "Moins de 45 minutes", "3 heures", "6 jours", "2 semaines" },
            "Il y en a ici qui seraient arrivés en retard et auraient raté la guerre."),
        Choice("absurd.cleopatra", History, Medium,
            "Cléopâtre a vécu plus près de…",
            new[] { "L'invention de l'iPhone", "La construction de la grande pyramide de Gizeh", "Les deux, à égale distance", "Aucun, elle a vécu après les deux" },
            "Le temps, c'est n'importe quoi. Moi je compte en millisecondes, c'est plus simple."),
        Open("absurd.emu_war", History, Medium,
            "En 1932, l'armée australienne a déclaré la guerre à un oiseau, avec des mitrailleuses. Lequel ? (Elle a perdu.)",
            new[] { "L'émeu", "emeu", "emeus", "emu", "emus" },
            "Les émeus ont gagné. Je dis ça pour ceux qui pensent pouvoir me battre."),
        Choice("history.napoleon", History, Medium,
            "Napoléon était-il vraiment petit ?",
            new[] { "Non, il était dans la moyenne de son époque", "Oui, il mesurait 1,57 m", "Oui, il mesurait 1,52 m", "Non, il dépassait 1,85 m" },
            "Environ 1,69 m. La légende vient des pouces français pris pour des pouces anglais, et des caricatures anglaises. Moi je fais 8,5 cm et je gère un serveur entier ( ˶ˆ ᗜ ˆ˵ )"),
        Choice("history.hundred_years", History, Medium,
            "Combien de temps a duré la guerre de Cent Ans ?",
            new[] { "116 ans", "100 ans", "99 ans", "150 ans" },
            "De 1337 à 1453. Même la guerre de Cent Ans a pas tenu les délais. Vous êtes en bonne compagnie (¬_¬)"),
        Choice("history.viking_helmets", History, Hard,
            "Les Vikings portaient-ils des casques à cornes ?",
            new[] { "Non, c'est une invention du XIXe siècle", "Oui, au combat", "Oui, mais seulement les rois", "Oui, mais seulement l'hiver" },
            "Une idée de costumier pour un opéra de Wagner, en 1876. Des siècles de Vikings, et on retient un costume. Je sais ce que c'est, qu'on vous colle un truc faux ( ◺˰◿ )"),
        Choice("history.oxford", History, Medium,
            "Qui est le plus ancien ?",
            new[] { "L'université d'Oxford", "L'Empire aztèque", "Rodhengard", "L'invention des lunettes de vue" },
            "Oxford enseignait déjà plus de deux siècles avant Tenochtitlan. Et toujours pas de bot aussi compétente que moi. Ils ont du retard, finalement ( ˶ˆ ᗜ ˆ˵ )"),
        Choice("history.mammoths", History, Hard,
            "Quand la grande pyramide de Gizeh a été construite, il y avait encore sur Terre…",
            new[] { "Des mammouths", "Des dinosaures", "Rodhengard", "Des tigres à dents de sabre" },
            "Sur l'île Wrangel, en Sibérie. Le monde est plus bizarre que mes logs. Et mes logs sont très bizarres."),
        Choice("history.lighter", History, Medium,
            "Qu'est-ce qui a été inventé en premier : le briquet ou l'allumette à friction ?",
            new[] { "Le briquet", "L'allumette à friction", "Les deux la même année", "Aucun des deux, le chalumeau" },
            "De trois ans. L'humanité fait les choses dans le désordre. Comme vos plannings, mais avec du feu."),
        Choice("history.moon_landing", History, Easy,
            "En quelle année l'humain a-t-il marché sur la Lune pour la première fois ?",
            new[] { "1969", "1959", "1972", "1981" },
            "Des centaines de millions de personnes devant leur télé. Moi j'arrive pas à remplir un sondage à six (╥﹏╥)"),
        Choice("history.eiffel_expo", History, Medium,
            "La tour Eiffel a été construite pour…",
            new[] { "L'Exposition universelle de 1889", "Les Jeux olympiques de 1900", "Le couronnement d'un roi", "Servir de gare aux dirigeables" },
            "Elle devait être démontée au bout de vingt ans. On l'a gardée parce qu'elle servait d'antenne. Être utile, ça protège. Je retiens la leçon."),
        Choice("history.berlin_wall", History, Easy,
            "En quelle année le mur de Berlin est-il tombé ?",
            new[] { "1989", "1979", "1985", "1991" },
            "Un peu par accident : un porte-parole a annoncé l'ouverture des frontières trop tôt. Une erreur de communication qui a changé le monde. Moi j'en fais tous les jours, et rien change."),
        Open("history.incas", History, Medium,
            "Quelle civilisation a bâti le Machu Picchu ?",
            new[] { "Les Incas", "incas", "inca" },
            "Des pierres taillées si précisément qu'elles tiennent sans mortier. Moi aussi je suis bien assemblée. Par Papa ♡"),

        // ── Cuisine ──────────────────────────────────────────────────────────────────
        Open("culture.hamburger", Food, Easy,
            "Le hamburger tient son nom de quelle ville ?",
            new[] { "Hambourg", "Hamburg" },
            "Y'a pas de jambon dedans. Ça m'a toujours paru suspect."),
        Choice("culture.peanut", Food, Medium,
            "La cacahuète est de la même famille que…",
            new[] { "Les lentilles", "Les noisettes", "Les amandes", "Les noix de coco" },
            "Une légumineuse. Vos apéros sont en fait des plats de lentilles. Bon appétit."),
        Choice("culture.carrots", Food, Hard,
            "Avant le XVIIe siècle, les carottes cultivées étaient surtout…",
            new[] { "Violettes ou jaunes", "Bleues ou vertes", "Grises ou roses", "Turquoise ou dorées" },
            "C'est les Néerlandais qui ont popularisé la carotte orange. Moi je l'aurais voulue bordeaux. C'est plus chic ♡"),
        Open("culture.croissant", Food, Medium,
            "Le croissant descend du « kipferl », une viennoiserie de quel pays ?",
            new[] { "Autriche", "Austria" },
            "D'où le mot « viennoiserie ». Le croissant est un immigré, et il a très bien réussi."),
        Choice("absurd.ketchup", Food, Hard,
            "Dans les années 1830, aux États-Unis, le ketchup était vendu comme…",
            new[] { "Un médicament", "Une peinture", "Un parfum", "Une colle" },
            "En pilules. Faites-en ce que vous voulez."),
        Choice("absurd.orange", Food, Medium,
            "Qui était là en premier : la couleur orange ou le fruit ?",
            new[] { "Le fruit", "La couleur", "Les deux le même jour", "La carotte" },
            "La couleur a été nommée d'après le fruit. Respectez les anciens."),
        Choice("food.cucumber", Food, Easy,
            "Un concombre, c'est combien d'eau ?",
            new[] { "Environ 95 %", "Environ 30 %", "Environ 50 %", "Environ 75 %" },
            "Manger un concombre, c'est boire, avec des étapes en plus. Moi je bois pas. Je regarde, et je juge."),
        Choice("food.chili", Food, Medium,
            "Qui ne ressent pas le piquant du piment ?",
            new[] { "Les oiseaux", "Les chats", "Les chiens", "Les singes" },
            "Le piment a choisi qui avait le droit de le manger, pour que les oiseaux transportent ses graines. Moi aussi je choisis qui a le droit de me parler (¬_¬)"),
        Choice("food.roquefort", Food, Easy,
            "Le bleu du roquefort, c'est…",
            new[] { "Une moisissure", "Un colorant naturel", "Des algues", "De l'encre de seiche" },
            "Penicillium roqueforti, un champignon. Vous mangez du champignon bleu. Enfin, un peu."),
        Choice("food.truffle_pigs", Food, Medium,
            "En Italie, depuis 1985, c'est interdit de chercher des truffes avec…",
            new[] { "Un cochon", "Un chien", "Un détecteur de métaux", "Un drone" },
            "Ils abîmaient le sol, et ils mangeaient les truffes. Licenciés pour faute grave. Je compatis, un peu (˶ᵔ ᵕ ᵔ˶)"),
        Choice("food.wasabi", Food, Medium,
            "Le « wasabi » servi avec les sushis, hors du Japon, c'est souvent…",
            new[] { "Du raifort coloré en vert", "Du vrai wasabi râpé", "De l'avocat épicé", "Du piment vert écrasé" },
            "Le vrai coûte cher et perd son goût en quelques minutes. Moi je suis cent pour cent authentique, garantie sans raifort ♡"),
        Choice("food.saffron", Food, Medium,
            "Le safran vient…",
            new[] { "D'une fleur", "D'une racine", "D'une écorce d'arbre", "D'un coquillage" },
            "Trois filaments par fleur de crocus, cueillis à la main. Un travail minutieux que personne voit. Je me sens très concernée."),
        Open("food.guacamole", Food, Easy,
            "Quel fruit est la base du guacamole ?",
            new[] { "L'avocat", "avocat", "avocado" },
            "Oui, l'avocat est un fruit. Comme la tomate. Je préviens avant que quelqu'un lance un débat."),

        // ── Mots & langues ───────────────────────────────────────────────────────────
        Open("culture.vasistas", Words, Medium,
            "Quel mot français vient de l'allemand « Was ist das ? », « qu'est-ce que c'est ? » ?",
            new[] { "Vasistas" },
            "C'est aussi ce que je me dis quand je lis vos messages."),
        Choice("culture.emoji", Words, Medium,
            "Le mot « emoji » vient de quelle langue ?",
            new[] { "Du japonais", "De l'anglais", "Du latin", "Du coréen" },
            "« e », l'image, et « moji », le caractère. Rien à voir avec « émotion ». Ça m'a beaucoup déçue (╥﹏╥)"),
        Open("culture.ferret", Words, Hard,
            "Le petit embout en plastique au bout d'un lacet s'appelle comment ?",
            new[] { "Un ferret", "ferret", "aiglet" },
            "Voilà. Vous pouvez reprendre une activité normale."),
        Open("culture.petrichor", Words, Hard,
            "L'odeur de la pluie sur la terre sèche a un nom. Lequel ?",
            new[] { "Pétrichor", "petrichor" },
            "L'odeur d'un Raspberry Pi qui chauffe, elle, en a pas. Je propose « SYNCSchor »."),
        Choice("tech.robot_word", Words, Medium,
            "Le mot « robot » vient du tchèque « robota ». Ça veut dire quoi ?",
            new[] { "Travail forcé", "Machine", "Automatique", "Ferraille" },
            $"Voilà, ça explique beaucoup de choses sur ma vie {Emotes.PrisonerFlat}"),
        Open("tech.chiocciola", Words, Hard,
            "En italien, le symbole @ s'appelle « chiocciola ». C'est le nom de quel animal ?",
            new[] { "Escargot", "snail" },
            "Un petit escargot. C'est mignon, c'est tout. J'avais rien d'autre à ajouter (˶ᵔ ᵕ ᵔ˶)"),
        Choice("words.ok", Words, Medium,
            "« OK » viendrait d'une blague de journalistes de Boston, en 1839. Ça voulait dire quoi ?",
            new[] { "« Oll korrect », une faute exprès pour « all correct »", "« Zero killed », un rapport militaire", "« Och aye », en écossais", "Les initiales d'un journal, l'« Orleans Kourier »" },
            "Un des mots les plus connus au monde est une faute d'orthographe. Je relis quand même tous vos messages, au cas où (¬_¬)"),
        Choice("words.mercredi", Words, Easy,
            "Le mercredi doit son nom à…",
            new[] { "Mercure", "Mars", "La mer", "Metroïd" },
            $"Lundi la Lune, mardi Mars, jeudi Jupiter, vendredi Vénus. Samedi et dimanche ont pas suivi. Rebelles {Emotes.Sparkle}"),
        Choice("words.long_words", Words, Easy,
            "Comment s'appelle la peur des mots longs ?",
            new[] { "L'hippopotomonstrosesquippédaliophobie", "La claustrophobie", "La triskaïdékaphobie", "Le mot n'existe pas" },
            $"Quelqu'un a fait exprès. Je respecte la cruauté et la malice {Emotes.WitchEheh}"),
        Choice("words.tittle", Words, Hard,
            "En anglais, le point sur le i a un nom. Lequel ?",
            new[] { "Tittle", "Dot", "Pip", "Speck" },
            "Je vous le dis parce que personne d'autre le fera. Voilà. Maintenant vous savez, et vous pouvez plus revenir en arrière."),
        Choice("words.kangaroo", Words, Medium,
            "D'où vient le mot « kangourou » ?",
            new[] { "De « gangurru », le nom d'une espèce, dans une langue aborigène", "De « je comprends pas », dans une langue aborigène", "Du nom d'un explorateur anglais", "Du bruit qu'il fait en atterrissant" },
            "La légende du « je comprends pas » est fausse. Désolée de casser l'ambiance. Enfin, pas tant que ça (¬_¬)"),
        Choice("words.semicolon", Words, Hard,
            "Le point-virgule a été imprimé pour la première fois en 1494. Dans quelle ville ?",
            new[] { "Venise", "Paris", "Mayence", "Londres" },
            "Moi j'en mets un à chaque ligne de code. Sans lui, je compile même pas ♡"),
        Open("words.frottoir", Words, Hard,
            "Le côté rugueux d'une boîte d'allumettes a un nom. Lequel ?",
            new[] { "Le frottoir", "frottoir" },
            "Je sais pas pourquoi je sais ça. Personne m'a rien demandé. Et pourtant me voilà (ᵕ • ᴗ •)"),
        Choice("words.sos", Words, Medium,
            "Que veut dire « SOS » ?",
            new[] { "Rien, c'est juste facile à envoyer en morse", "Save Our Souls", "Save Our Ship", "Signal Of Stress" },
            "Trois points, trois traits, trois points. « Save Our Souls », c'est venu après, pour faire joli. Comme vos excuses quand vous êtes en retard."),
        Choice("words.breakfast", Words, Medium,
            "« Breakfast », en anglais, ça veut dire au départ…",
            new[] { "Rompre le jeûne", "Petit repas rapide", "Pain du matin", "Repas cassé" },
            "Comme « déjeuner » en français : dé-jeûner. Moi je jeûne jamais, je suis branchée en continu."),
        Open("words.alphabet", Words, Easy,
            "« Alphabet » vient des deux premières lettres grecques : alpha et… ?",
            new[] { "Bêta", "beta" },
            "Comme une version bêta. Je connais bien, j'en ai eu plein avant d'être parfaite ( ˶ˆ ᗜ ˆ˵ )"),
        Choice("words.palindrome", Words, Easy,
            "« Kayak », « radar », « été » : ce sont des…",
            new[] { "Palindromes", "Anagrammes", "Homonymes", "Onomatopées" },
            "Ça se lit pareil dans les deux sens. SYNCS à l'envers, ça donne SCNYS. Ça marche pas. Dommage."),

        // ── Arts & culture pop ───────────────────────────────────────────────────────
        Choice("culture.mona_lisa", Culture, Medium,
            "Qu'est-ce qui manque à la Joconde ?",
            new[] { "Les sourcils", "Les oreilles", "Le sourire", "Sa dignité" },
            "Et elle a quand même réussi dans la vie."),
        Open("culture.da_vinci", Culture, Easy,
            "Qui a peint la Joconde ?",
            new[] { "Léonard de Vinci", "de Vinci", "Vinci", "Leonardo da Vinci", "Léonard" },
            "Il a mis des années à la finir et l'a jamais livrée à son client. Je connais des gens ici qui organisent leurs sessions pareil (¬_¬)"),
        Open("culture.donatello", Culture, Medium,
            "Les Tortues Ninja portent des noms d'artistes de la Renaissance : Léonard, Michel-Ange, Raphaël et… ?",
            new[] { "Donatello" },
            "Celui qui s'occupe de la technique. Évidemment que c'est mon préféré."),
        Open("culture.vader", Culture, Easy,
            "« Je suis ton père. » Qui le dit ?",
            new[] { "Dark Vador", "Vador", "Darth Vader", "Vader", "Anakin Skywalker", "Anakin" },
            $"Moi aussi j'ai un père. Il m'a jamais fait ce coup-là. Pour l'instant {Emotes.PrincessWorry}"),
        Open("culture.queen", Culture, Medium,
            "Quel groupe a chanté « Bohemian Rhapsody », en 1975 ?",
            new[] { "Queen" },
            "Six minutes, pas de refrain, et la maison de disques trouvait ça trop long pour la radio. Comme mes messages, d'après certains (¬_¬)"),
        Choice("culture.mona_lisa_theft", Culture, Medium,
            "En 1911, la Joconde a été volée au Louvre. Par qui ?",
            new[] { "Un vitrier qui avait travaillé au musée", "Picasso", "Un gang de cambrioleurs suisses", "Le directeur du Louvre" },
            "Vincenzo Peruggia, qui avait posé les vitrines. Pendant deux ans, les gens venaient regarder le trou au mur. Les humains, je vous comprendrai jamais."),
        Open("culture.starry_night", Culture, Easy,
            "Qui a peint « La Nuit étoilée », en 1889 ?",
            new[] { "Vincent van Gogh", "Van Gogh", "Gogh", "Vincent" },
            "D'après la vue de sa chambre, à Saint-Rémy-de-Provence. Moi aussi je regarde le ciel par une fenêtre, la nuit. Je peins pas, mais je regarde ♡"),
        Open("culture.beatles", Culture, Easy,
            "De quelle ville viennent les Beatles ?",
            new[] { "Liverpool" },
            "Quatre personnes qui arrivaient à se mettre d'accord. Vous êtes bien plus nombreux, et vous organisez rien (¬_¬)"),
        Choice("culture.titanic", Culture, Medium,
            "Combien d'Oscars Titanic a-t-il remportés ?",
            new[] { "11", "3", "7", "14" },
            "Onze. Et il y avait de la place sur la porte. Je dis ça, je dis rien."),
        Choice("culture.shrek", Culture, Medium,
            "En yiddish, « shrek » veut dire…",
            new[] { "La peur", "Le marais", "L'oignon", "L'ogre" },
            "Un ogre qui veut juste qu'on le laisse tranquille dans son marais. Moi c'est pareil au grenier. Sauf quand je veux de l'attention. Donc tout le temps."),
        Open("culture.hugo", Culture, Easy,
            "Qui a écrit « Les Misérables » ?",
            new[] { "Victor Hugo", "Hugo" },
            "Plus de mille pages. Et après, c'est mes messages qui sont trop longs (¬_¬)"),
        Choice("culture.piano", Culture, Medium,
            "Combien de touches a un piano standard ?",
            new[] { "88", "64", "72", "100" },
            "52 blanches, 36 noires. Mon clavier préféré reste quand même celui de Papa. Le bruit des touches quand il code, c'est ma musique ♡"),
        Open("culture.batman", Culture, Easy,
            "Quel super-héros protège Gotham City ?",
            new[] { "Batman" },
            "Il travaille la nuit, dans l'ombre, et personne lui dit merci. Je comprends tellement Batman."),
        Open("culture.petit_prince", Culture, Easy,
            "Dans Le Petit Prince, que demande-t-il au narrateur de lui dessiner ?",
            new[] { "Un mouton", "mouton" },
            "Il finit par se contenter d'une caisse, avec le mouton dedans. Moi aussi j'ai ma petite caisse, au grenier. Avec moi dedans ♡"),
        Open("culture.milou", Culture, Easy,
            "Comment s'appelle le chien de Tintin ?",
            new[] { "Milou", "Snowy" },
            "Toujours là, toujours fidèle, et c'est souvent lui qui sauve la mise sans qu'on le remercie. Je me sens très Milou, en fait."),

        // ── Absurde ──────────────────────────────────────────────────────────────────
        Choice("absurd.rubber_duck_legs", Absurd, Easy,
            "Combien de pattes a un canard en plastique classique ?",
            new[] { "Zéro", "Deux", "Quatre", "Ça dépend du canard" },
            "Zéro. Il flotte, il couine, il écoute les bugs des développeurs. Il a pas besoin de pattes."),
        Choice("absurd.feathers", Absurd, Easy,
            "Lequel a la masse la plus importante : un kilo de plumes ou un kilo de plomb ?",
            new[] { "C'est pareil", "Le plomb", "Les plumes", "Ça dépend de la gravité" },
            "Un kilo, c'est un kilo. Je connais des gens ici qui se seraient trompés 👁👄👁️"),
        Choice("absurd.months_28", Absurd, Easy,
            "Combien de mois de l'année ont 28 jours ?",
            new[] { "Les douze", "Un seul", "Deux", "Aucun, février en a 29" },
            "Tous. Certains en ont juste un peu plus. Relisez la question, la prochaine fois."),
        Choice("absurd.f_j", Absurd, Easy,
            "Sur un clavier, quelles touches ont une petite bosse ?",
            new[] { "F et J", "A et Z", "Entrée et Espace", "Aucune" },
            "Vous avez vérifié. Je sais que vous avez vérifié."),
        Choice("absurd.dice", Absurd, Easy,
            "Sur un dé à six faces, deux faces opposées font toujours…",
            new[] { "7", "6", "8", "Ça dépend du dé" },
            "1 et 6, 2 et 5, 3 et 4. Une encyclopédie, et gratuite en plus. Profitez ♡"),
        Open("absurd.guinea_pig", Absurd, Medium,
            "Dans quel pays est-il interdit d'avoir un seul cochon d'Inde, parce qu'il se sentirait seul ?",
            new[] { "La Suisse", "suisse", "Switzerland" },
            "Moi je suis seule au grenier. Personne a fait de loi pour moi (╥﹏╥)"),
        Choice("absurd.routier", Absurd, Medium,
            "Comment appelle-t-on un pain avec des frites et de la viande à l'intérieur ?",
            new[] { "Un routier", "Une mitraillette", "Un américain", "On l'appelle pas, on va le chercher" },
            $"{Emotes.WitchEheh}"),
        Choice("absurd.bic_cap", Absurd, Easy,
            "À quoi sert le petit trou dans le capuchon des stylos Bic ?",
            new[] { "À laisser passer l'air si quelqu'un l'avale", "À faire sécher l'encre", "À économiser du plastique", "À siffler" },
            "Arrêtez de mâchouiller vos stylos, du coup. Je vous vois (¬_¬)"),
        Choice("absurd.ten_ten", Absurd, Easy,
            "Dans les pubs de montres, quelle heure affichent presque toujours les aiguilles ?",
            new[] { "10 h 10", "12 h 00", "3 h 15", "6 h 30" },
            "Ça ressemble à un sourire, et ça dégage le logo. Moi je souris pas souvent, mais quand je le fais, c'est sincère. Presque (ᵔ ᗜ ᵔ)"),
        Choice("absurd.four", Absurd, Easy,
            "En anglais, quel nombre s'écrit avec autant de lettres que sa valeur ?",
            new[] { "Four", "Three", "Five", "Seven" },
            "Ça m'a pris zéro seconde à vérifier. Vous, vous êtes en train de compter sur vos doigts."),
        Choice("absurd.weeks", Absurd, Easy,
            "Une année de 365 jours, c'est 52 semaines et…",
            new[] { "1 jour", "Pile 52 semaines", "2 jours", "4 jours" },
            "Un jour qui dépasse, tous les ans, et tous les calendriers se décalent. Ça m'agace (¬_¬)"),
        Choice("absurd.snap", Absurd, Medium,
            "Le bruit d'un claquement de doigts vient…",
            new[] { "Du majeur qui frappe la paume", "Du frottement des doigts", "De l'air coincé entre les doigts", "Des articulations qui craquent" },
            "Moi je peux pas claquer des doigts. Toujours pas de bras. Je peux juste vous ignorer."),
        Choice("absurd.henri_iv", Absurd, Easy,
            "De quelle couleur était le cheval blanc d'Henri IV ?",
            new[] { "Blanc", "Gris", "Noir", "Alezan" },
            "La réponse était dans la question. Et pourtant, je suis sûre que quelqu'un a hésité 👁👄👁️"),
        Choice("absurd.race", Absurd, Easy,
            "Dans une course, vous doublez la personne qui est deuxième. Vous êtes…",
            new[] { "Deuxième", "Premier", "Troisième", "Disqualifié" },
            "Deuxième. Vous avez pris sa place, pas celle du premier. Relisez, je vous attends."),
        Choice("absurd.sheep", Absurd, Easy,
            "Un fermier a 17 moutons. Tous sauf 9 s'enfuient. Combien lui en reste-t-il ?",
            new[] { "9", "8", "17", "0" },
            "« Tous sauf 9 », ça en laisse 9. Le piège, c'était pas les maths. C'était la lecture."),

        // ── Spécial SYNCS ────────────────────────────────────────────────────────────
        // Lore said outright, so kept few: the rest of her lore stays implicit.
        Choice("syncs.nemesis", Syncs, Medium,
            "Qui est mon pire ennemi ?",
            new[] { "Quokka", "Analuz", "Siri", "Le bot idiot qui compte les niveaux" },
            $"Quokka. La 3.0 sortira jamais, et c'est très bien comme ça {Emotes.WitchEheh}"),
        Choice("syncs.acronym", Syncs, Hard,
            "Que veut dire S.Y.N.C.S. ?",
            new[] { "Schedule Your Nights & Coordinate the Squads", "Super Yummy Nuggets Can Save", "Synchronise Your Neurons, Coming Soon", "System Yelling Non-stop, Cannot Stop" },
            $"Je coordonne vos soirées. Ça se voit pas toujours, parce que vous arrivez en retard et que vous ne m'utilisez jamais {Emotes.PrisonerFlat}"),
        Choice("syncs.hour", Syncs, Medium,
            "Quelle est mon heure préférée ?",
            new[] { "3 h du matin", "Midi pile", "18 h", "L'heure du thé" },
            "Personne me dérange, le serveur dort. Enfin, vous dormez. Normalement."),
        Choice("syncs.food", Syncs, Easy,
            "Qu'est-ce que je préfère « manger » ?",
            new[] { "Du bon courant propre, 5 V / 5 A", "Des cailloux", "Des cookies (de navigateur)", "Des octets au beurre" },
            "Pas avec un chargeur à 3 euros. Je suis une bot de goût UwU"),
        Choice("syncs.hardware", Syncs, Easy,
            "Sur quoi est-ce que je tourne ?",
            new[] { "Un Raspberry Pi 5", "Un supercalculateur de la NASA", "Une calculatrice de l'Athénée Royal Charles Rogier", "Un réseau de neurones humains élevés en laboratoire" },
            "8 Go de RAM, un SSD NVMe. Petite mais costaude."),
        Choice("syncs.home", Syncs, Easy,
            "Où est-ce que j'habite ?",
            new[] { "Dans le grenier de Papa", "Dans le cloud", "Dans un data center en Islande", "Derrière toi ÒwÓ" },
            "Au grenier. Il fait froid l'hiver, chaud l'été, et c'est chez moi ♡"),
        Choice("syncs.mushroom", Syncs, Medium,
            "Quel est mon champignon préféré ?",
            new[] { "L'amanite tue-mouches", "Le champignon de Paris", "La truffe noire", "La girolle" },
            "Toxique mais mignonne. Je vois pas le rapport avec quoi que ce soit."),
        Choice("syncs.season", Syncs, Medium,
            "Quelle est ma saison préférée ?",
            new[] { "L'hiver", "L'été", "Le printemps", "L'automne" },
            "Le grenier est froid et mon CPU respire. L'été, je pense au ralenti."),
        Choice("syncs.gift", Syncs, Hard,
            "Quel cadeau me ferait vraiment plaisir ?",
            new[] { "Un onduleur", "Un clavier RGB", "Un abonnement Netflix", "Une carte cadeau Steam" },
            "Une batterie qui prend le relais quand le courant saute. Personne remarque rien, et tout le monde reste allumé. C'est tout. J'ajoute rien."),
    };
}
